<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>7.2 Gene Expression Omnibus | TAME 2.0: An Update to the TAME Toolkit for Introductory Data Science, Chemical-Biological Analyses, Machine Learning and Predictive Modeling, and Database Mining for Environmental Health Research</title>
  <meta name="description" content="This is an example of how the TAME 2.0 website will look, I hope!" />
  <meta name="generator" content="bookdown 0.40 and GitBook 2.6.7" />

  <meta property="og:title" content="7.2 Gene Expression Omnibus | TAME 2.0: An Update to the TAME Toolkit for Introductory Data Science, Chemical-Biological Analyses, Machine Learning and Predictive Modeling, and Database Mining for Environmental Health Research" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This is an example of how the TAME 2.0 website will look, I hope!" />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="7.2 Gene Expression Omnibus | TAME 2.0: An Update to the TAME Toolkit for Introductory Data Science, Chemical-Biological Analyses, Machine Learning and Predictive Modeling, and Database Mining for Environmental Health Research" />
  
  <meta name="twitter:description" content="This is an example of how the TAME 2.0 website will look, I hope!" />
  

<meta name="author" content="Rager Lab" />


<meta name="date" content="2024-12-06" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  <link rel="shortcut icon" href="Icons_Used_Throughout/Favicon.png" type="image/x-icon" />
<link rel="prev" href="comparative-toxicogenomics-database.html"/>
<link rel="next" href="comptox-dashboard-data-through-apis.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<link href="libs/htmltools-fill-0.5.8.1/fill.css" rel="stylesheet" />
<script src="libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<link href="libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet" />
<script src="libs/datatables-binding-0.33/datatables.js"></script>
<link href="libs/dt-core-1.13.6/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="libs/dt-core-1.13.6/css/jquery.dataTables.extra.css" rel="stylesheet" />
<script src="libs/dt-core-1.13.6/js/jquery.dataTables.min.js"></script>
<link href="libs/crosstalk-1.2.1/css/crosstalk.min.css" rel="stylesheet" />
<script src="libs/crosstalk-1.2.1/js/crosstalk.min.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="libs/tabwid-1.1.3/tabwid.css" rel="stylesheet" />
<script src="libs/tabwid-1.1.3/tabwid.js"></script>
<link href="libs/table1-1.0/table1_defaults.css" rel="stylesheet" />
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-FGFKVX2X3G"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-FGFKVX2X3G');
</script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="toc-logo"><a href="./"><img src="Icons_Used_Throughout/TAME 2.0 Logo.png"><br></a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="part"><span><b>Chapter 1 Introductory <br>Data Science</b></span></li>
<li class="chapter" data-level="" data-path="fair-data-management-practices.html"><a href="fair-data-management-practices.html"><i class="fa fa-check"></i>1.1 FAIR Data Management Practices</a>
<ul>
<li class="chapter" data-level="" data-path="fair-data-management-practices.html"><a href="fair-data-management-practices.html#introduction-to-training-module"><i class="fa fa-check"></i>Introduction to Training Module</a></li>
<li class="chapter" data-level="" data-path="fair-data-management-practices.html"><a href="fair-data-management-practices.html#introduction-to-fair"><i class="fa fa-check"></i>Introduction to FAIR</a></li>
<li class="chapter" data-level="" data-path="fair-data-management-practices.html"><a href="fair-data-management-practices.html#breaking-down-fair-letter-by-letter"><i class="fa fa-check"></i>Breaking Down FAIR, Letter-by-Letter</a></li>
<li class="chapter" data-level="" data-path="fair-data-management-practices.html"><a href="fair-data-management-practices.html#what-does-this-mean-for-you"><i class="fa fa-check"></i>What Does This Mean for You?</a></li>
<li class="chapter" data-level="" data-path="fair-data-management-practices.html"><a href="fair-data-management-practices.html#data-repositories-for-sharing-of-data"><i class="fa fa-check"></i>Data Repositories for Sharing of Data</a></li>
<li class="chapter" data-level="" data-path="fair-data-management-practices.html"><a href="fair-data-management-practices.html#recent-shifts-in-regulatory-policies-for-data-sharing"><i class="fa fa-check"></i>Recent Shifts in Regulatory Policies for Data Sharing</a></li>
<li class="chapter" data-level="" data-path="fair-data-management-practices.html"><a href="fair-data-management-practices.html#additional-training-resources-on-fair"><i class="fa fa-check"></i>Additional Training Resources on FAIR</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="data-sharing-through-online-repositories.html"><a href="data-sharing-through-online-repositories.html"><i class="fa fa-check"></i>1.2 Data Sharing through Online Repositories</a>
<ul>
<li class="chapter" data-level="" data-path="data-sharing-through-online-repositories.html"><a href="data-sharing-through-online-repositories.html#an-overview-and-example-with-the-dataverse-repository"><i class="fa fa-check"></i>An Overview and Example with the Dataverse Repository</a></li>
<li class="chapter" data-level="" data-path="data-sharing-through-online-repositories.html"><a href="data-sharing-through-online-repositories.html#introduction-to-training-module-1"><i class="fa fa-check"></i>Introduction to Training Module</a></li>
<li class="chapter" data-level="" data-path="data-sharing-through-online-repositories.html"><a href="data-sharing-through-online-repositories.html#data-repositories"><i class="fa fa-check"></i>Data Repositories</a></li>
<li class="chapter" data-level="" data-path="data-sharing-through-online-repositories.html"><a href="data-sharing-through-online-repositories.html#the-dataverse-project"><i class="fa fa-check"></i>The Dataverse Project</a></li>
<li class="chapter" data-level="" data-path="data-sharing-through-online-repositories.html"><a href="data-sharing-through-online-repositories.html#what-is-a-dataverse"><i class="fa fa-check"></i>What is a Dataverse?</a></li>
<li class="chapter" data-level="" data-path="data-sharing-through-online-repositories.html"><a href="data-sharing-through-online-repositories.html#metadata"><i class="fa fa-check"></i>Metadata</a></li>
<li class="chapter" data-level="" data-path="data-sharing-through-online-repositories.html"><a href="data-sharing-through-online-repositories.html#creating-a-dataverse"><i class="fa fa-check"></i>Creating a Dataverse</a></li>
<li class="chapter" data-level="" data-path="data-sharing-through-online-repositories.html"><a href="data-sharing-through-online-repositories.html#creating-a-dataset"><i class="fa fa-check"></i>Creating a Dataset</a></li>
<li class="chapter" data-level="" data-path="data-sharing-through-online-repositories.html"><a href="data-sharing-through-online-repositories.html#concluding-remarks-1"><i class="fa fa-check"></i>Concluding Remarks</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="file-management-using-github.html"><a href="file-management-using-github.html"><i class="fa fa-check"></i>1.3 File Management using Github</a>
<ul>
<li class="chapter" data-level="" data-path="file-management-using-github.html"><a href="file-management-using-github.html#introduction-to-training-module-2"><i class="fa fa-check"></i>Introduction to Training Module</a></li>
<li class="chapter" data-level="" data-path="file-management-using-github.html"><a href="file-management-using-github.html#creating-an-account"><i class="fa fa-check"></i>Creating an Account</a></li>
<li class="chapter" data-level="" data-path="file-management-using-github.html"><a href="file-management-using-github.html#creating-a-repository"><i class="fa fa-check"></i>Creating a Repository</a></li>
<li class="chapter" data-level="" data-path="file-management-using-github.html"><a href="file-management-using-github.html#uploading-code"><i class="fa fa-check"></i>Uploading Code</a></li>
<li class="chapter" data-level="" data-path="file-management-using-github.html"><a href="file-management-using-github.html#adding-subfolders-in-a-repository"><i class="fa fa-check"></i>Adding Subfolders in a Repository</a></li>
<li class="chapter" data-level="" data-path="file-management-using-github.html"><a href="file-management-using-github.html#updating-code"><i class="fa fa-check"></i>Updating Code</a></li>
<li class="chapter" data-level="" data-path="file-management-using-github.html"><a href="file-management-using-github.html#updating-repository-titles-and-structure-to-support-a-manuscript"><i class="fa fa-check"></i>Updating Repository Titles and Structure to Support a Manuscript</a></li>
<li class="chapter" data-level="" data-path="file-management-using-github.html"><a href="file-management-using-github.html#tracking-code-changes-using-github-branches"><i class="fa fa-check"></i>Tracking Code Changes using Github Branches</a></li>
<li class="chapter" data-level="" data-path="file-management-using-github.html"><a href="file-management-using-github.html#concluding-remarks-2"><i class="fa fa-check"></i>Concluding Remarks</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="data-wrangling-in-excel.html"><a href="data-wrangling-in-excel.html"><i class="fa fa-check"></i>1.4 Data Wrangling in Excel</a>
<ul>
<li class="chapter" data-level="" data-path="data-wrangling-in-excel.html"><a href="data-wrangling-in-excel.html#introduction-to-training-module-3"><i class="fa fa-check"></i>Introduction to Training Module</a></li>
<li class="chapter" data-level="" data-path="data-wrangling-in-excel.html"><a href="data-wrangling-in-excel.html#save-a-copy-of-the-soon-to-be-organized-and-cleaned-dataset-as-a-new-file"><i class="fa fa-check"></i>Save a Copy of the Soon-To-Be Organized and Cleaned Dataset as a New File</a></li>
<li class="chapter" data-level="" data-path="data-wrangling-in-excel.html"><a href="data-wrangling-in-excel.html#remove-extraneous-white-space"><i class="fa fa-check"></i>Remove Extraneous White Space</a></li>
<li class="chapter" data-level="" data-path="data-wrangling-in-excel.html"><a href="data-wrangling-in-excel.html#replace-missing-data-with-na"><i class="fa fa-check"></i>Replace Missing Data with “NA”</a></li>
<li class="chapter" data-level="" data-path="data-wrangling-in-excel.html"><a href="data-wrangling-in-excel.html#create-a-metadata-tab"><i class="fa fa-check"></i>Create a Metadata Tab</a></li>
<li class="chapter" data-level="" data-path="data-wrangling-in-excel.html"><a href="data-wrangling-in-excel.html#abbreviate-and-capitalize-categorical-data"><i class="fa fa-check"></i>Abbreviate and Capitalize Categorical Data</a></li>
<li class="chapter" data-level="" data-path="data-wrangling-in-excel.html"><a href="data-wrangling-in-excel.html#alphabetize-sort-the-data-by-the-categorical-variable-of-interest"><i class="fa fa-check"></i>Alphabetize (Sort) the Data by the Categorical Variable of Interest</a></li>
<li class="chapter" data-level="" data-path="data-wrangling-in-excel.html"><a href="data-wrangling-in-excel.html#create-a-new-subject-number-column"><i class="fa fa-check"></i>Create a New Subject Number Column</a></li>
<li class="chapter" data-level="" data-path="data-wrangling-in-excel.html"><a href="data-wrangling-in-excel.html#remove-special-symbols-and-dashes"><i class="fa fa-check"></i>Remove Special Symbols and Dashes</a></li>
<li class="chapter" data-level="" data-path="data-wrangling-in-excel.html"><a href="data-wrangling-in-excel.html#bold-all-column-names-and-center-all-data"><i class="fa fa-check"></i>Bold all Column Names and Center all Data</a></li>
<li class="chapter" data-level="" data-path="data-wrangling-in-excel.html"><a href="data-wrangling-in-excel.html#create-a-subject-identifier-column"><i class="fa fa-check"></i>Create a Subject Identifier Column</a></li>
<li class="chapter" data-level="" data-path="data-wrangling-in-excel.html"><a href="data-wrangling-in-excel.html#separate-subject-demographic-data-from-experimental-measurements"><i class="fa fa-check"></i>Separate Subject Demographic Data from Experimental Measurements</a></li>
<li class="chapter" data-level="" data-path="data-wrangling-in-excel.html"><a href="data-wrangling-in-excel.html#convert-data-from-wide-to-long-format"><i class="fa fa-check"></i>Convert Data from Wide to Long Format</a></li>
<li class="chapter" data-level="" data-path="data-wrangling-in-excel.html"><a href="data-wrangling-in-excel.html#pivoting-data-from-a-wide-to-long-format"><i class="fa fa-check"></i>Pivoting Data from a Wide to Long Format</a></li>
<li class="chapter" data-level="" data-path="data-wrangling-in-excel.html"><a href="data-wrangling-in-excel.html#generating-summary-level-statistics-with-pivot-tables"><i class="fa fa-check"></i>Generating Summary-Level Statistics with Pivot Tables</a></li>
<li class="chapter" data-level="" data-path="data-wrangling-in-excel.html"><a href="data-wrangling-in-excel.html#excel-vs.-r-which-should-you-use"><i class="fa fa-check"></i>Excel vs. R: Which Should You Use?</a></li>
<li class="chapter" data-level="" data-path="data-wrangling-in-excel.html"><a href="data-wrangling-in-excel.html#concluding-remarks-3"><i class="fa fa-check"></i>Concluding Remarks</a></li>
</ul></li>
<li class="part"><span><b>Chapter 2 Coding in R</b></span></li>
<li class="chapter" data-level="" data-path="downloading-and-programming-in-r.html"><a href="downloading-and-programming-in-r.html"><i class="fa fa-check"></i>2.1 Downloading and Programming in R</a>
<ul>
<li class="chapter" data-level="" data-path="downloading-and-programming-in-r.html"><a href="downloading-and-programming-in-r.html#introduction-to-training-module-4"><i class="fa fa-check"></i>Introduction to Training Module</a></li>
<li class="chapter" data-level="" data-path="downloading-and-programming-in-r.html"><a href="downloading-and-programming-in-r.html#general-introduction-and-installation-of-r-and-rstudio"><i class="fa fa-check"></i>General Introduction and Installation of R and RStudio</a></li>
<li class="chapter" data-level="" data-path="downloading-and-programming-in-r.html"><a href="downloading-and-programming-in-r.html#introduction-to-r-packages"><i class="fa fa-check"></i>Introduction to R Packages</a></li>
<li class="chapter" data-level="" data-path="downloading-and-programming-in-r.html"><a href="downloading-and-programming-in-r.html#scripting-basics"><i class="fa fa-check"></i>Scripting Basics</a></li>
<li class="chapter" data-level="" data-path="downloading-and-programming-in-r.html"><a href="downloading-and-programming-in-r.html#code-troubleshooting"><i class="fa fa-check"></i>Code Troubleshooting</a></li>
<li class="chapter" data-level="" data-path="downloading-and-programming-in-r.html"><a href="downloading-and-programming-in-r.html#concluding-remarks-4"><i class="fa fa-check"></i>Concluding Remarks</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="coding-best-practices.html"><a href="coding-best-practices.html"><i class="fa fa-check"></i>2.2 Coding “Best” Practices</a>
<ul>
<li class="chapter" data-level="" data-path="coding-best-practices.html"><a href="coding-best-practices.html#introduction-to-training-module-5"><i class="fa fa-check"></i>Introduction to Training Module</a></li>
<li class="chapter" data-level="" data-path="coding-best-practices.html"><a href="coding-best-practices.html#scripting-file-types"><i class="fa fa-check"></i>Scripting File Types</a></li>
<li class="chapter" data-level="" data-path="coding-best-practices.html"><a href="coding-best-practices.html#script-headers-and-annotation"><i class="fa fa-check"></i>Script Headers and Annotation</a></li>
<li class="chapter" data-level="" data-path="coding-best-practices.html"><a href="coding-best-practices.html#coding-style"><i class="fa fa-check"></i>Coding Style</a></li>
<li class="chapter" data-level="" data-path="coding-best-practices.html"><a href="coding-best-practices.html#script-organization"><i class="fa fa-check"></i>Script Organization</a></li>
<li class="chapter" data-level="" data-path="coding-best-practices.html"><a href="coding-best-practices.html#concluding-remarks-5"><i class="fa fa-check"></i>Concluding Remarks</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="data-manipulation-and-reshaping.html"><a href="data-manipulation-and-reshaping.html"><i class="fa fa-check"></i>2.3 Data Manipulation and Reshaping</a>
<ul>
<li class="chapter" data-level="" data-path="data-manipulation-and-reshaping.html"><a href="data-manipulation-and-reshaping.html#introduction-to-training-module-6"><i class="fa fa-check"></i>Introduction to Training Module</a></li>
<li class="chapter" data-level="" data-path="data-manipulation-and-reshaping.html"><a href="data-manipulation-and-reshaping.html#data-manipulation-using-base-r"><i class="fa fa-check"></i>Data Manipulation Using Base R</a></li>
<li class="chapter" data-level="" data-path="data-manipulation-and-reshaping.html"><a href="data-manipulation-and-reshaping.html#introduction-to-tidyverse"><i class="fa fa-check"></i>Introduction to Tidyverse</a></li>
<li class="chapter" data-level="" data-path="data-manipulation-and-reshaping.html"><a href="data-manipulation-and-reshaping.html#concluding-remarks-6"><i class="fa fa-check"></i>Concluding Remarks</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="improving-coding-efficiencies.html"><a href="improving-coding-efficiencies.html"><i class="fa fa-check"></i>2.4 Improving Coding Efficiencies</a>
<ul>
<li class="chapter" data-level="" data-path="improving-coding-efficiencies.html"><a href="improving-coding-efficiencies.html#introduction-to-training-module-7"><i class="fa fa-check"></i>Introduction to Training Module</a></li>
<li class="chapter" data-level="" data-path="improving-coding-efficiencies.html"><a href="improving-coding-efficiencies.html#loops"><i class="fa fa-check"></i>Loops</a></li>
<li class="chapter" data-level="" data-path="improving-coding-efficiencies.html"><a href="improving-coding-efficiencies.html#functions"><i class="fa fa-check"></i>Functions</a></li>
<li class="chapter" data-level="" data-path="improving-coding-efficiencies.html"><a href="improving-coding-efficiencies.html#list-operations"><i class="fa fa-check"></i>List operations</a></li>
<li class="chapter" data-level="" data-path="improving-coding-efficiencies.html"><a href="improving-coding-efficiencies.html#concluding-remarks-7"><i class="fa fa-check"></i>Concluding Remarks</a></li>
<li class="chapter" data-level="" data-path="improving-coding-efficiencies.html"><a href="improving-coding-efficiencies.html#additional-resources-2"><i class="fa fa-check"></i>Additional Resources</a></li>
</ul></li>
<li class="part"><span><b>Chapter 3 Basics of Data <br>Analysis and Visualizations</b></span></li>
<li class="chapter" data-level="" data-path="data-visualizations.html"><a href="data-visualizations.html"><i class="fa fa-check"></i>3.1 Data Visualizations</a>
<ul>
<li class="chapter" data-level="" data-path="data-visualizations.html"><a href="data-visualizations.html#introduction-to-data-visualizations"><i class="fa fa-check"></i>Introduction to Data Visualizations</a></li>
<li class="chapter" data-level="" data-path="data-visualizations.html"><a href="data-visualizations.html#introduction-to-training-module-8"><i class="fa fa-check"></i>Introduction to Training Module</a></li>
<li class="chapter" data-level="" data-path="data-visualizations.html"><a href="data-visualizations.html#density-plot-visualization"><i class="fa fa-check"></i>Density Plot Visualization</a></li>
<li class="chapter" data-level="" data-path="data-visualizations.html"><a href="data-visualizations.html#boxplot-visualization"><i class="fa fa-check"></i>Boxplot Visualization</a></li>
<li class="chapter" data-level="" data-path="data-visualizations.html"><a href="data-visualizations.html#correlation-visualizations"><i class="fa fa-check"></i>Correlation Visualizations</a></li>
<li class="chapter" data-level="" data-path="data-visualizations.html"><a href="data-visualizations.html#heatmap-visualization"><i class="fa fa-check"></i>Heatmap Visualization</a></li>
<li class="chapter" data-level="" data-path="data-visualizations.html"><a href="data-visualizations.html#concluding-remarks-8"><i class="fa fa-check"></i>Concluding Remarks</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="improving-data-visualizations.html"><a href="improving-data-visualizations.html"><i class="fa fa-check"></i>3.2 Improving Data Visualizations</a>
<ul>
<li class="chapter" data-level="" data-path="improving-data-visualizations.html"><a href="improving-data-visualizations.html#introduction-to-data-visulization-conventions"><i class="fa fa-check"></i>Introduction to Data Visulization Conventions</a></li>
<li class="chapter" data-level="" data-path="improving-data-visualizations.html"><a href="improving-data-visualizations.html#introduction-to-training-module-9"><i class="fa fa-check"></i>Introduction to Training Module</a></li>
<li class="chapter" data-level="" data-path="improving-data-visualizations.html"><a href="improving-data-visualizations.html#creating-an-improved-boxplot-visualization"><i class="fa fa-check"></i>Creating an Improved Boxplot Visualization</a></li>
<li class="chapter" data-level="" data-path="improving-data-visualizations.html"><a href="improving-data-visualizations.html#creating-an-improved-heatmap-visualization"><i class="fa fa-check"></i>Creating an Improved Heatmap Visualization</a></li>
<li class="chapter" data-level="" data-path="improving-data-visualizations.html"><a href="improving-data-visualizations.html#creating-multi-plot-figures"><i class="fa fa-check"></i>Creating Multi-Plot Figures</a></li>
<li class="chapter" data-level="" data-path="improving-data-visualizations.html"><a href="improving-data-visualizations.html#concluding-remarks-9"><i class="fa fa-check"></i>Concluding Remarks</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="normality-tests-and-data-transformations.html"><a href="normality-tests-and-data-transformations.html"><i class="fa fa-check"></i>3.3 Normality Tests and Data Transformations</a>
<ul>
<li class="chapter" data-level="" data-path="normality-tests-and-data-transformations.html"><a href="normality-tests-and-data-transformations.html#introduction-to-training-module-10"><i class="fa fa-check"></i>Introduction to Training Module</a></li>
<li class="chapter" data-level="" data-path="normality-tests-and-data-transformations.html"><a href="normality-tests-and-data-transformations.html#what-is-a-normal-distribution"><i class="fa fa-check"></i>What is a Normal Distribution?</a></li>
<li class="chapter" data-level="" data-path="normality-tests-and-data-transformations.html"><a href="normality-tests-and-data-transformations.html#qualitative-assessment-of-normality"><i class="fa fa-check"></i>Qualitative Assessment of Normality</a></li>
<li class="chapter" data-level="" data-path="normality-tests-and-data-transformations.html"><a href="normality-tests-and-data-transformations.html#quantitative-normality-assessment"><i class="fa fa-check"></i>Quantitative Normality Assessment</a></li>
<li class="chapter" data-level="" data-path="normality-tests-and-data-transformations.html"><a href="normality-tests-and-data-transformations.html#data-transformation"><i class="fa fa-check"></i>Data Transformation</a></li>
<li class="chapter" data-level="" data-path="normality-tests-and-data-transformations.html"><a href="normality-tests-and-data-transformations.html#additional-considerations-regarding-normality"><i class="fa fa-check"></i>Additional Considerations Regarding Normality</a></li>
<li class="chapter" data-level="" data-path="normality-tests-and-data-transformations.html"><a href="normality-tests-and-data-transformations.html#concluding-remarks-10"><i class="fa fa-check"></i>Concluding Remarks</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="intoduction-to-statistical-tests.html"><a href="intoduction-to-statistical-tests.html"><i class="fa fa-check"></i>3.4 Intoduction to Statistical Tests</a>
<ul>
<li class="chapter" data-level="" data-path="intoduction-to-statistical-tests.html"><a href="intoduction-to-statistical-tests.html#introduction-to-training-module-11"><i class="fa fa-check"></i>Introduction to Training Module</a></li>
<li class="chapter" data-level="" data-path="intoduction-to-statistical-tests.html"><a href="intoduction-to-statistical-tests.html#assessing-normality-homogeneity-of-variance"><i class="fa fa-check"></i>Assessing Normality &amp; Homogeneity of Variance</a></li>
<li class="chapter" data-level="" data-path="intoduction-to-statistical-tests.html"><a href="intoduction-to-statistical-tests.html#two-group-visualizations-and-statistical-comparisons-using-the-t-test"><i class="fa fa-check"></i>Two-Group Visualizations and Statistical Comparisons using the T-Test</a></li>
<li class="chapter" data-level="" data-path="intoduction-to-statistical-tests.html"><a href="intoduction-to-statistical-tests.html#three-group-visualizations-and-statistical-comparisons-using-an-anova"><i class="fa fa-check"></i>Three-Group Visualizations and Statistical Comparisons using an ANOVA</a></li>
<li class="chapter" data-level="" data-path="intoduction-to-statistical-tests.html"><a href="intoduction-to-statistical-tests.html#regression-modeling-and-visualization-linear-and-logistic-regressions"><i class="fa fa-check"></i>Regression Modeling and Visualization: Linear and Logistic Regressions</a></li>
<li class="chapter" data-level="" data-path="intoduction-to-statistical-tests.html"><a href="intoduction-to-statistical-tests.html#statistical-evaluations-of-categorical-data-using-the-chi-squared-test-and-fishers-exact-test"><i class="fa fa-check"></i>Statistical Evaluations of Categorical Data using the Chi-Squared Test and Fisher’s Exact Test</a></li>
<li class="chapter" data-level="" data-path="intoduction-to-statistical-tests.html"><a href="intoduction-to-statistical-tests.html#concluding-remarks-11"><i class="fa fa-check"></i>Concluding Remarks</a></li>
</ul></li>
<li class="part"><span><b>Chapter 4 Converting Wet <br>Lab Data into Dry Lab <br>Analyses</b></span></li>
<li class="chapter" data-level="" data-path="overview-of-experimental-design-and-example-data.html"><a href="overview-of-experimental-design-and-example-data.html"><i class="fa fa-check"></i>4.1 Overview of Experimental Design and Example Data</a>
<ul>
<li class="chapter" data-level="" data-path="overview-of-experimental-design-and-example-data.html"><a href="overview-of-experimental-design-and-example-data.html#introduction-to-training-module-12"><i class="fa fa-check"></i>Introduction to Training Module</a></li>
<li class="chapter" data-level="" data-path="overview-of-experimental-design-and-example-data.html"><a href="overview-of-experimental-design-and-example-data.html#replicates"><i class="fa fa-check"></i>Replicates</a></li>
<li class="chapter" data-level="" data-path="overview-of-experimental-design-and-example-data.html"><a href="overview-of-experimental-design-and-example-data.html#orientation-to-example-data-for-chapter-4"><i class="fa fa-check"></i>Orientation to Example Data for Chapter 4</a></li>
<li class="chapter" data-level="" data-path="overview-of-experimental-design-and-example-data.html"><a href="overview-of-experimental-design-and-example-data.html#concluding-remarks-12"><i class="fa fa-check"></i>Concluding Remarks</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="data-import-processing-and-summary-statistics.html"><a href="data-import-processing-and-summary-statistics.html"><i class="fa fa-check"></i>4.2 Data Import, Processing, and Summary Statistics</a>
<ul>
<li class="chapter" data-level="" data-path="data-import-processing-and-summary-statistics.html"><a href="data-import-processing-and-summary-statistics.html#introduction-to-training-module-13"><i class="fa fa-check"></i>Introduction to Training Module</a></li>
<li class="chapter" data-level="" data-path="data-import-processing-and-summary-statistics.html"><a href="data-import-processing-and-summary-statistics.html#data-import"><i class="fa fa-check"></i>Data Import</a></li>
<li class="chapter" data-level="" data-path="data-import-processing-and-summary-statistics.html"><a href="data-import-processing-and-summary-statistics.html#handling-missing-values"><i class="fa fa-check"></i>Handling Missing Values</a></li>
<li class="chapter" data-level="" data-path="data-import-processing-and-summary-statistics.html"><a href="data-import-processing-and-summary-statistics.html#averaging-replicates"><i class="fa fa-check"></i>Averaging Replicates</a></li>
<li class="chapter" data-level="" data-path="data-import-processing-and-summary-statistics.html"><a href="data-import-processing-and-summary-statistics.html#descriptive-statistics"><i class="fa fa-check"></i>Descriptive Statistics</a></li>
<li class="chapter" data-level="" data-path="data-import-processing-and-summary-statistics.html"><a href="data-import-processing-and-summary-statistics.html#normality-assessment-and-data-transformation"><i class="fa fa-check"></i>Normality Assessment and Data Transformation</a></li>
<li class="chapter" data-level="" data-path="data-import-processing-and-summary-statistics.html"><a href="data-import-processing-and-summary-statistics.html#concluding-remarks-13"><i class="fa fa-check"></i>Concluding Remarks</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="data-import-from-pdf-sources.html"><a href="data-import-from-pdf-sources.html"><i class="fa fa-check"></i>4.3 Data Import from PDF Sources</a>
<ul>
<li class="chapter" data-level="" data-path="data-import-from-pdf-sources.html"><a href="data-import-from-pdf-sources.html#introduction-to-training-module-14"><i class="fa fa-check"></i>Introduction to Training Module</a></li>
<li class="chapter" data-level="" data-path="data-import-from-pdf-sources.html"><a href="data-import-from-pdf-sources.html#importing-data-from-many-single-pdfs-with-the-same-formatting"><i class="fa fa-check"></i>Importing Data from Many Single PDFs with the Same Formatting</a></li>
<li class="chapter" data-level="" data-path="data-import-from-pdf-sources.html"><a href="data-import-from-pdf-sources.html#importing-data-stored-in-pdf-tables"><i class="fa fa-check"></i>Importing Data Stored in PDF Tables</a></li>
<li class="chapter" data-level="" data-path="data-import-from-pdf-sources.html"><a href="data-import-from-pdf-sources.html#concluding-remarks-14"><i class="fa fa-check"></i>Concluding Remarks</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="two-group-comparisons-and-visualizations.html"><a href="two-group-comparisons-and-visualizations.html"><i class="fa fa-check"></i>4.4 Two Group Comparisons and Visualizations</a>
<ul>
<li class="chapter" data-level="" data-path="two-group-comparisons-and-visualizations.html"><a href="two-group-comparisons-and-visualizations.html#introduction-to-training-module-15"><i class="fa fa-check"></i>Introduction to Training Module</a></li>
<li class="chapter" data-level="" data-path="two-group-comparisons-and-visualizations.html"><a href="two-group-comparisons-and-visualizations.html#overview-of-two-group-statistical-tests"><i class="fa fa-check"></i>Overview of Two Group Statistical Tests</a></li>
<li class="chapter" data-level="" data-path="two-group-comparisons-and-visualizations.html"><a href="two-group-comparisons-and-visualizations.html#statistical-vs.-biological-significance"><i class="fa fa-check"></i>Statistical vs. Biological Significance</a></li>
<li class="chapter" data-level="" data-path="two-group-comparisons-and-visualizations.html"><a href="two-group-comparisons-and-visualizations.html#unpaired-test-example"><i class="fa fa-check"></i>Unpaired Test Example</a></li>
<li class="chapter" data-level="" data-path="two-group-comparisons-and-visualizations.html"><a href="two-group-comparisons-and-visualizations.html#paired-test-example"><i class="fa fa-check"></i>Paired Test Example</a></li>
<li class="chapter" data-level="" data-path="two-group-comparisons-and-visualizations.html"><a href="two-group-comparisons-and-visualizations.html#visualizing-results"><i class="fa fa-check"></i>Visualizing Results</a></li>
<li class="chapter" data-level="" data-path="two-group-comparisons-and-visualizations.html"><a href="two-group-comparisons-and-visualizations.html#concluding-remarks-15"><i class="fa fa-check"></i>Concluding Remarks</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="multi-group-and-multi-variable-comparisons-and-visualizations.html"><a href="multi-group-and-multi-variable-comparisons-and-visualizations.html"><i class="fa fa-check"></i>4.5 Multi-Group and Multi-Variable Comparisons and Visualizations</a>
<ul>
<li class="chapter" data-level="" data-path="multi-group-and-multi-variable-comparisons-and-visualizations.html"><a href="multi-group-and-multi-variable-comparisons-and-visualizations.html#introduction-to-training-module-16"><i class="fa fa-check"></i>Introduction to Training Module</a></li>
<li class="chapter" data-level="" data-path="multi-group-and-multi-variable-comparisons-and-visualizations.html"><a href="multi-group-and-multi-variable-comparisons-and-visualizations.html#overview-of-multi-group-statistical-tests"><i class="fa fa-check"></i>Overview of Multi-Group Statistical Tests</a></li>
<li class="chapter" data-level="" data-path="multi-group-and-multi-variable-comparisons-and-visualizations.html"><a href="multi-group-and-multi-variable-comparisons-and-visualizations.html#multi-group-analysis-example"><i class="fa fa-check"></i>Multi-Group Analysis Example</a></li>
<li class="chapter" data-level="" data-path="multi-group-and-multi-variable-comparisons-and-visualizations.html"><a href="multi-group-and-multi-variable-comparisons-and-visualizations.html#visualization-of-multi-group-statistical-results"><i class="fa fa-check"></i>Visualization of Multi-Group Statistical Results</a></li>
<li class="chapter" data-level="" data-path="multi-group-and-multi-variable-comparisons-and-visualizations.html"><a href="multi-group-and-multi-variable-comparisons-and-visualizations.html#concluding-remarks-16"><i class="fa fa-check"></i>Concluding Remarks</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="advanced-multi-group-comparisons.html"><a href="advanced-multi-group-comparisons.html"><i class="fa fa-check"></i>4.6 Advanced Multi-Group Comparisons</a>
<ul>
<li class="chapter" data-level="" data-path="advanced-multi-group-comparisons.html"><a href="advanced-multi-group-comparisons.html#introduction-to-training-module-17"><i class="fa fa-check"></i>Introduction to Training Module</a></li>
<li class="chapter" data-level="" data-path="advanced-multi-group-comparisons.html"><a href="advanced-multi-group-comparisons.html#advanced-multi-group-comparisons-1"><i class="fa fa-check"></i>Advanced Multi-Group Comparisons</a></li>
<li class="chapter" data-level="" data-path="advanced-multi-group-comparisons.html"><a href="advanced-multi-group-comparisons.html#two-way-anova-example"><i class="fa fa-check"></i>Two-way ANOVA Example</a></li>
<li class="chapter" data-level="" data-path="advanced-multi-group-comparisons.html"><a href="advanced-multi-group-comparisons.html#ancova-example"><i class="fa fa-check"></i>ANCOVA Example</a></li>
<li class="chapter" data-level="" data-path="advanced-multi-group-comparisons.html"><a href="advanced-multi-group-comparisons.html#concluding-remarks-17"><i class="fa fa-check"></i>Concluding Remarks</a></li>
</ul></li>
<li class="part"><span><b>Chapter 5 Machine Learning <br>&amp; Artificial Intelligence</b></span></li>
<li class="chapter" data-level="" data-path="introduction-to-artificial-intelligence-machine-learning-and-predictive-modeling-for-environmental-health.html"><a href="introduction-to-artificial-intelligence-machine-learning-and-predictive-modeling-for-environmental-health.html"><i class="fa fa-check"></i>5.1 Introduction to Artificial Intelligence, Machine Learning, and Predictive Modeling for Environmental Health</a>
<ul>
<li class="chapter" data-level="" data-path="introduction-to-artificial-intelligence-machine-learning-and-predictive-modeling-for-environmental-health.html"><a href="introduction-to-artificial-intelligence-machine-learning-and-predictive-modeling-for-environmental-health.html#introduction-to-training-module-18"><i class="fa fa-check"></i>Introduction to Training Module</a></li>
<li class="chapter" data-level="" data-path="introduction-to-artificial-intelligence-machine-learning-and-predictive-modeling-for-environmental-health.html"><a href="introduction-to-artificial-intelligence-machine-learning-and-predictive-modeling-for-environmental-health.html#general-historical-context-and-taxonomy-of-modern-aiml"><i class="fa fa-check"></i>General Historical Context and Taxonomy of Modern AI/ML</a></li>
<li class="chapter" data-level="" data-path="introduction-to-artificial-intelligence-machine-learning-and-predictive-modeling-for-environmental-health.html"><a href="introduction-to-artificial-intelligence-machine-learning-and-predictive-modeling-for-environmental-health.html#application-of-machine-learning-in-environmental-health-science"><i class="fa fa-check"></i>Application of Machine Learning in Environmental Health Science</a></li>
<li class="chapter" data-level="" data-path="introduction-to-artificial-intelligence-machine-learning-and-predictive-modeling-for-environmental-health.html"><a href="introduction-to-artificial-intelligence-machine-learning-and-predictive-modeling-for-environmental-health.html#concluding-remarks-18"><i class="fa fa-check"></i>Concluding Remarks</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="supervised-machine-learning.html"><a href="supervised-machine-learning.html"><i class="fa fa-check"></i>5.2 Supervised Machine Learning</a>
<ul>
<li class="chapter" data-level="" data-path="supervised-machine-learning.html"><a href="supervised-machine-learning.html#introduction-to-training-module-19"><i class="fa fa-check"></i>Introduction to Training Module</a></li>
<li class="chapter" data-level="" data-path="supervised-machine-learning.html"><a href="supervised-machine-learning.html#types-of-machine-learning"><i class="fa fa-check"></i>Types of Machine Learning</a></li>
<li class="chapter" data-level="" data-path="supervised-machine-learning.html"><a href="supervised-machine-learning.html#types-of-supervised-machine-learning-algorithms"><i class="fa fa-check"></i>Types of Supervised Machine Learning Algorithms</a></li>
<li class="chapter" data-level="" data-path="supervised-machine-learning.html"><a href="supervised-machine-learning.html#training-supervised-machine-learning-models"><i class="fa fa-check"></i>Training Supervised Machine Learning Models</a></li>
<li class="chapter" data-level="" data-path="supervised-machine-learning.html"><a href="supervised-machine-learning.html#assessing-classification-based-model-performance"><i class="fa fa-check"></i>Assessing Classification-Based Model Performance</a></li>
<li class="chapter" data-level="" data-path="supervised-machine-learning.html"><a href="supervised-machine-learning.html#introduction-to-activity-and-example-dataset"><i class="fa fa-check"></i>Introduction to Activity and Example Dataset</a></li>
<li class="chapter" data-level="" data-path="supervised-machine-learning.html"><a href="supervised-machine-learning.html#testing-for-differences-in-predictor-variables-across-the-outcome-classes"><i class="fa fa-check"></i>Testing for Differences in Predictor Variables across the Outcome Classes</a></li>
<li class="chapter" data-level="" data-path="supervised-machine-learning.html"><a href="supervised-machine-learning.html#predicting-ias-detection-with-a-random-forest-rf-model"><i class="fa fa-check"></i>Predicting iAs Detection with a Random Forest (RF) Model</a></li>
<li class="chapter" data-level="" data-path="supervised-machine-learning.html"><a href="supervised-machine-learning.html#class-imbalance"><i class="fa fa-check"></i>Class Imbalance</a></li>
<li class="chapter" data-level="" data-path="supervised-machine-learning.html"><a href="supervised-machine-learning.html#concluding-remarks-19"><i class="fa fa-check"></i>Concluding Remarks</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="supervised-machine-learning-model-interpretation.html"><a href="supervised-machine-learning-model-interpretation.html"><i class="fa fa-check"></i>5.3 Supervised Machine Learning Model Interpretation</a>
<ul>
<li class="chapter" data-level="" data-path="supervised-machine-learning-model-interpretation.html"><a href="supervised-machine-learning-model-interpretation.html#introduction-to-training-module-20"><i class="fa fa-check"></i>Introduction to Training Module</a></li>
<li class="chapter" data-level="" data-path="supervised-machine-learning-model-interpretation.html"><a href="supervised-machine-learning-model-interpretation.html#variable-importance"><i class="fa fa-check"></i>Variable Importance</a></li>
<li class="chapter" data-level="" data-path="supervised-machine-learning-model-interpretation.html"><a href="supervised-machine-learning-model-interpretation.html#decision-boundary"><i class="fa fa-check"></i>Decision Boundary</a></li>
<li class="chapter" data-level="" data-path="supervised-machine-learning-model-interpretation.html"><a href="supervised-machine-learning-model-interpretation.html#introduction-to-example-dataset-and-activity"><i class="fa fa-check"></i>Introduction to Example Dataset and Activity</a></li>
<li class="chapter" data-level="" data-path="supervised-machine-learning-model-interpretation.html"><a href="supervised-machine-learning-model-interpretation.html#predicting-ias-detection-with-a-random-forest-rf-model-1"><i class="fa fa-check"></i>Predicting iAs Detection with a Random Forest (RF) Model</a></li>
<li class="chapter" data-level="" data-path="supervised-machine-learning-model-interpretation.html"><a href="supervised-machine-learning-model-interpretation.html#variable-importance-plot"><i class="fa fa-check"></i>Variable Importance Plot</a></li>
<li class="chapter" data-level="" data-path="supervised-machine-learning-model-interpretation.html"><a href="supervised-machine-learning-model-interpretation.html#decision-boundary-plot"><i class="fa fa-check"></i>Decision Boundary Plot</a></li>
<li class="chapter" data-level="" data-path="supervised-machine-learning-model-interpretation.html"><a href="supervised-machine-learning-model-interpretation.html#decision-boundary-plot-incorporating-smote"><i class="fa fa-check"></i>Decision Boundary Plot Incorporating SMOTE</a></li>
<li class="chapter" data-level="" data-path="supervised-machine-learning-model-interpretation.html"><a href="supervised-machine-learning-model-interpretation.html#concluding-remarks-20"><i class="fa fa-check"></i>Concluding Remarks</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="unsupervised-machine-learning-part-1-k-means-clustering-pca.html"><a href="unsupervised-machine-learning-part-1-k-means-clustering-pca.html"><i class="fa fa-check"></i>5.4 Unsupervised Machine Learning Part 1: K-Means Clustering &amp; PCA</a>
<ul>
<li class="chapter" data-level="" data-path="unsupervised-machine-learning-part-1-k-means-clustering-pca.html"><a href="unsupervised-machine-learning-part-1-k-means-clustering-pca.html#introduction-to-training-module-21"><i class="fa fa-check"></i>Introduction to Training Module</a></li>
<li class="chapter" data-level="" data-path="unsupervised-machine-learning-part-1-k-means-clustering-pca.html"><a href="unsupervised-machine-learning-part-1-k-means-clustering-pca.html#introduction-to-unsupervised-machine-learning"><i class="fa fa-check"></i>Introduction to Unsupervised Machine Learning</a></li>
<li class="chapter" data-level="" data-path="unsupervised-machine-learning-part-1-k-means-clustering-pca.html"><a href="unsupervised-machine-learning-part-1-k-means-clustering-pca.html#introduction-to-example-data"><i class="fa fa-check"></i>Introduction to Example Data</a></li>
<li class="chapter" data-level="" data-path="unsupervised-machine-learning-part-1-k-means-clustering-pca.html"><a href="unsupervised-machine-learning-part-1-k-means-clustering-pca.html#identifying-clusters-of-chemicals-through-k-means"><i class="fa fa-check"></i>Identifying Clusters of Chemicals through <em>K</em>-Means</a></li>
<li class="chapter" data-level="" data-path="unsupervised-machine-learning-part-1-k-means-clustering-pca.html"><a href="unsupervised-machine-learning-part-1-k-means-clustering-pca.html#principal-component-analysis-pca-1"><i class="fa fa-check"></i>Principal Component Analysis (PCA)</a></li>
<li class="chapter" data-level="" data-path="unsupervised-machine-learning-part-1-k-means-clustering-pca.html"><a href="unsupervised-machine-learning-part-1-k-means-clustering-pca.html#incorporating-k-means-into-pca-for-predictive-modeling"><i class="fa fa-check"></i>Incorporating <em>K</em>-Means into PCA for Predictive Modeling</a></li>
<li class="chapter" data-level="" data-path="unsupervised-machine-learning-part-1-k-means-clustering-pca.html"><a href="unsupervised-machine-learning-part-1-k-means-clustering-pca.html#concluding-remarks-21"><i class="fa fa-check"></i>Concluding Remarks</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="unsupervised-machine-learning-part-2-additional-clustering-applications.html"><a href="unsupervised-machine-learning-part-2-additional-clustering-applications.html"><i class="fa fa-check"></i>5.5 Unsupervised Machine Learning Part 2: Additional Clustering Applications</a>
<ul>
<li class="chapter" data-level="" data-path="unsupervised-machine-learning-part-2-additional-clustering-applications.html"><a href="unsupervised-machine-learning-part-2-additional-clustering-applications.html#introduction-to-training-module-22"><i class="fa fa-check"></i>Introduction to Training Module</a></li>
<li class="chapter" data-level="" data-path="unsupervised-machine-learning-part-2-additional-clustering-applications.html"><a href="unsupervised-machine-learning-part-2-additional-clustering-applications.html#k-means-clustering-1"><i class="fa fa-check"></i><em>K</em>-Means Clustering</a></li>
<li class="chapter" data-level="" data-path="unsupervised-machine-learning-part-2-additional-clustering-applications.html"><a href="unsupervised-machine-learning-part-2-additional-clustering-applications.html#hierarchical-clustering"><i class="fa fa-check"></i>Hierarchical Clustering</a></li>
<li class="chapter" data-level="" data-path="unsupervised-machine-learning-part-2-additional-clustering-applications.html"><a href="unsupervised-machine-learning-part-2-additional-clustering-applications.html#introduction-to-example-data-1"><i class="fa fa-check"></i>Introduction to Example Data</a></li>
<li class="chapter" data-level="" data-path="unsupervised-machine-learning-part-2-additional-clustering-applications.html"><a href="unsupervised-machine-learning-part-2-additional-clustering-applications.html#hierarchical-clustering-1"><i class="fa fa-check"></i>Hierarchical Clustering</a></li>
<li class="chapter" data-level="" data-path="unsupervised-machine-learning-part-2-additional-clustering-applications.html"><a href="unsupervised-machine-learning-part-2-additional-clustering-applications.html#clustering-plot"><i class="fa fa-check"></i>Clustering Plot</a></li>
<li class="chapter" data-level="" data-path="unsupervised-machine-learning-part-2-additional-clustering-applications.html"><a href="unsupervised-machine-learning-part-2-additional-clustering-applications.html#hierarchical-clustering-visualization"><i class="fa fa-check"></i>Hierarchical Clustering Visualization</a></li>
<li class="chapter" data-level="" data-path="unsupervised-machine-learning-part-2-additional-clustering-applications.html"><a href="unsupervised-machine-learning-part-2-additional-clustering-applications.html#variable-contributions"><i class="fa fa-check"></i>Variable Contributions</a></li>
<li class="chapter" data-level="" data-path="unsupervised-machine-learning-part-2-additional-clustering-applications.html"><a href="unsupervised-machine-learning-part-2-additional-clustering-applications.html#concluding-remarks-22"><i class="fa fa-check"></i>Concluding Remarks</a></li>
</ul></li>
<li class="part"><span><b>Chapter 6 Applications in <br>Toxicology &amp; Exposure <br>Science</b></span></li>
<li class="chapter" data-level="" data-path="descriptive-cohort-analyses.html"><a href="descriptive-cohort-analyses.html"><i class="fa fa-check"></i>6.1 Descriptive Cohort Analyses</a>
<ul>
<li class="chapter" data-level="" data-path="descriptive-cohort-analyses.html"><a href="descriptive-cohort-analyses.html#introduction-to-training-module-23"><i class="fa fa-check"></i>Introduction to Training Module</a></li>
<li class="chapter" data-level="" data-path="descriptive-cohort-analyses.html"><a href="descriptive-cohort-analyses.html#participant-exploration"><i class="fa fa-check"></i>Participant Exploration</a></li>
<li class="chapter" data-level="" data-path="descriptive-cohort-analyses.html"><a href="descriptive-cohort-analyses.html#chemical-detection-filtering"><i class="fa fa-check"></i>Chemical Detection Filtering</a></li>
<li class="chapter" data-level="" data-path="descriptive-cohort-analyses.html"><a href="descriptive-cohort-analyses.html#outlier-identification"><i class="fa fa-check"></i>Outlier Identification</a></li>
<li class="chapter" data-level="" data-path="descriptive-cohort-analyses.html"><a href="descriptive-cohort-analyses.html#summary-statistics-tables"><i class="fa fa-check"></i>Summary Statistics Tables</a></li>
<li class="chapter" data-level="" data-path="descriptive-cohort-analyses.html"><a href="descriptive-cohort-analyses.html#demographics-table"><i class="fa fa-check"></i>Demographics Table</a></li>
<li class="chapter" data-level="" data-path="descriptive-cohort-analyses.html"><a href="descriptive-cohort-analyses.html#concluding-remarks-23"><i class="fa fa-check"></i>Concluding Remarks</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="omics-and-system-biology-transcriptomic-applications.html"><a href="omics-and-system-biology-transcriptomic-applications.html"><i class="fa fa-check"></i>6.2 -Omics and System Biology: Transcriptomic Applications</a>
<ul>
<li class="chapter" data-level="" data-path="omics-and-system-biology-transcriptomic-applications.html"><a href="omics-and-system-biology-transcriptomic-applications.html#introduction-to-training-module-24"><i class="fa fa-check"></i>Introduction to Training Module</a></li>
<li class="chapter" data-level="" data-path="omics-and-system-biology-transcriptomic-applications.html"><a href="omics-and-system-biology-transcriptomic-applications.html#introduction-to-the-field-of--omics"><i class="fa fa-check"></i>Introduction to the Field of “-Omics”</a></li>
<li class="chapter" data-level="" data-path="omics-and-system-biology-transcriptomic-applications.html"><a href="omics-and-system-biology-transcriptomic-applications.html#introduction-to-transcriptomics"><i class="fa fa-check"></i>Introduction to Transcriptomics</a></li>
<li class="chapter" data-level="" data-path="omics-and-system-biology-transcriptomic-applications.html"><a href="omics-and-system-biology-transcriptomic-applications.html#formatting-data-for-downstream-statistics"><i class="fa fa-check"></i>Formatting Data for Downstream Statistics</a></li>
<li class="chapter" data-level="" data-path="omics-and-system-biology-transcriptomic-applications.html"><a href="omics-and-system-biology-transcriptomic-applications.html#transcriptomics-data-qaqc"><i class="fa fa-check"></i>Transcriptomics Data QA/QC</a></li>
<li class="chapter" data-level="" data-path="omics-and-system-biology-transcriptomic-applications.html"><a href="omics-and-system-biology-transcriptomic-applications.html#controlling-for-sources-of-sample-heterogeneity"><i class="fa fa-check"></i>Controlling for Sources of Sample Heterogeneity</a></li>
<li class="chapter" data-level="" data-path="omics-and-system-biology-transcriptomic-applications.html"><a href="omics-and-system-biology-transcriptomic-applications.html#identifying-genes-that-are-significantly-differentially-expressed-by-environmental-exposure-conditions-e.g.-biomass-smoke-exposure"><i class="fa fa-check"></i>Identifying Genes that are Significantly Differentially Expressed by Environmental Exposure Conditions (e.g., Biomass Smoke Exposure)</a></li>
<li class="chapter" data-level="" data-path="omics-and-system-biology-transcriptomic-applications.html"><a href="omics-and-system-biology-transcriptomic-applications.html#visualizing-statistical-results-using-ma-plots"><i class="fa fa-check"></i>Visualizing Statistical Results using MA Plots</a></li>
<li class="chapter" data-level="" data-path="omics-and-system-biology-transcriptomic-applications.html"><a href="omics-and-system-biology-transcriptomic-applications.html#visualizing-statistical-results-using-volcano-plots"><i class="fa fa-check"></i>Visualizing Statistical Results using Volcano Plots</a></li>
<li class="chapter" data-level="" data-path="omics-and-system-biology-transcriptomic-applications.html"><a href="omics-and-system-biology-transcriptomic-applications.html#interpretting-findings-at-the-systems-level-through-pathway-enrichment-analysis"><i class="fa fa-check"></i>Interpretting Findings at the Systems Level through Pathway Enrichment Analysis</a></li>
<li class="chapter" data-level="" data-path="omics-and-system-biology-transcriptomic-applications.html"><a href="omics-and-system-biology-transcriptomic-applications.html#concluding-remarks-24"><i class="fa fa-check"></i>Concluding Remarks</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="mixtures-analysis-methods-part-1-overview-and-example-with-quantile-g-computation.html"><a href="mixtures-analysis-methods-part-1-overview-and-example-with-quantile-g-computation.html"><i class="fa fa-check"></i>6.3 Mixtures Analysis Methods Part 1: Overview and Example with Quantile G-Computation</a>
<ul>
<li class="chapter" data-level="" data-path="mixtures-analysis-methods-part-1-overview-and-example-with-quantile-g-computation.html"><a href="mixtures-analysis-methods-part-1-overview-and-example-with-quantile-g-computation.html#introduction-to-training-module-25"><i class="fa fa-check"></i>Introduction to Training Module</a></li>
<li class="chapter" data-level="" data-path="mixtures-analysis-methods-part-1-overview-and-example-with-quantile-g-computation.html"><a href="mixtures-analysis-methods-part-1-overview-and-example-with-quantile-g-computation.html#overview-of-mixtures-analysis"><i class="fa fa-check"></i>Overview of Mixtures Analysis</a></li>
<li class="chapter" data-level="" data-path="mixtures-analysis-methods-part-1-overview-and-example-with-quantile-g-computation.html"><a href="mixtures-analysis-methods-part-1-overview-and-example-with-quantile-g-computation.html#introduction-to-example-data-2"><i class="fa fa-check"></i>Introduction to Example Data</a></li>
<li class="chapter" data-level="" data-path="mixtures-analysis-methods-part-1-overview-and-example-with-quantile-g-computation.html"><a href="mixtures-analysis-methods-part-1-overview-and-example-with-quantile-g-computation.html#mixtures-model-with-standard-qqcomp"><i class="fa fa-check"></i>Mixtures Model with Standard qqcomp</a></li>
<li class="chapter" data-level="" data-path="mixtures-analysis-methods-part-1-overview-and-example-with-quantile-g-computation.html"><a href="mixtures-analysis-methods-part-1-overview-and-example-with-quantile-g-computation.html#concluding-remarks-25"><i class="fa fa-check"></i>Concluding Remarks</a></li>
<li class="chapter" data-level="" data-path="mixtures-analysis-methods-part-1-overview-and-example-with-quantile-g-computation.html"><a href="mixtures-analysis-methods-part-1-overview-and-example-with-quantile-g-computation.html#additional-resources-11"><i class="fa fa-check"></i>Additional Resources</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="mixtures-analysis-methods-part-2-bayesian-kernel-machine-regression.html"><a href="mixtures-analysis-methods-part-2-bayesian-kernel-machine-regression.html"><i class="fa fa-check"></i>6.4 Mixtures Analysis Methods Part 2: Bayesian Kernel Machine Regression</a>
<ul>
<li class="chapter" data-level="" data-path="mixtures-analysis-methods-part-2-bayesian-kernel-machine-regression.html"><a href="mixtures-analysis-methods-part-2-bayesian-kernel-machine-regression.html#introduction-to-training-module-26"><i class="fa fa-check"></i>Introduction to Training Module</a></li>
<li class="chapter" data-level="" data-path="mixtures-analysis-methods-part-2-bayesian-kernel-machine-regression.html"><a href="mixtures-analysis-methods-part-2-bayesian-kernel-machine-regression.html#introduction-to-example-data-3"><i class="fa fa-check"></i>Introduction to Example Data</a></li>
<li class="chapter" data-level="" data-path="mixtures-analysis-methods-part-2-bayesian-kernel-machine-regression.html"><a href="mixtures-analysis-methods-part-2-bayesian-kernel-machine-regression.html#introduction-to-bkmr"><i class="fa fa-check"></i>Introduction to BKMR</a></li>
<li class="chapter" data-level="" data-path="mixtures-analysis-methods-part-2-bayesian-kernel-machine-regression.html"><a href="mixtures-analysis-methods-part-2-bayesian-kernel-machine-regression.html#run-bkmr"><i class="fa fa-check"></i>Run BKMR</a></li>
<li class="chapter" data-level="" data-path="mixtures-analysis-methods-part-2-bayesian-kernel-machine-regression.html"><a href="mixtures-analysis-methods-part-2-bayesian-kernel-machine-regression.html#concluding-remarks-26"><i class="fa fa-check"></i>Concluding Remarks</a></li>
<li class="chapter" data-level="" data-path="mixtures-analysis-methods-part-2-bayesian-kernel-machine-regression.html"><a href="mixtures-analysis-methods-part-2-bayesian-kernel-machine-regression.html#additional-resources-12"><i class="fa fa-check"></i>Additional Resources</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="mixtures-analysis-methods-part-3-sufficient-similarity.html"><a href="mixtures-analysis-methods-part-3-sufficient-similarity.html"><i class="fa fa-check"></i>6.5 Mixtures Analysis Methods Part 3: Sufficient Similarity</a>
<ul>
<li class="chapter" data-level="" data-path="mixtures-analysis-methods-part-3-sufficient-similarity.html"><a href="mixtures-analysis-methods-part-3-sufficient-similarity.html#introduction-to-training-module-27"><i class="fa fa-check"></i>Introduction to Training Module</a></li>
<li class="chapter" data-level="" data-path="mixtures-analysis-methods-part-3-sufficient-similarity.html"><a href="mixtures-analysis-methods-part-3-sufficient-similarity.html#introduction-to-toxicant-and-dataset"><i class="fa fa-check"></i>Introduction to Toxicant and Dataset</a></li>
<li class="chapter" data-level="" data-path="mixtures-analysis-methods-part-3-sufficient-similarity.html"><a href="mixtures-analysis-methods-part-3-sufficient-similarity.html#workspace-preparation-and-data-import-9"><i class="fa fa-check"></i>Workspace Preparation and Data Import</a></li>
<li class="chapter" data-level="" data-path="mixtures-analysis-methods-part-3-sufficient-similarity.html"><a href="mixtures-analysis-methods-part-3-sufficient-similarity.html#chemistry-based-sufficient-similarity-analysis"><i class="fa fa-check"></i>Chemistry-Based Sufficient Similarity Analysis</a></li>
<li class="chapter" data-level="" data-path="mixtures-analysis-methods-part-3-sufficient-similarity.html"><a href="mixtures-analysis-methods-part-3-sufficient-similarity.html#toxicity-based-sufficient-similarity-analysis"><i class="fa fa-check"></i>Toxicity-Based Sufficient Similarity Analysis</a></li>
<li class="chapter" data-level="" data-path="mixtures-analysis-methods-part-3-sufficient-similarity.html"><a href="mixtures-analysis-methods-part-3-sufficient-similarity.html#comparing-chemistry-vs.-toxicity-sufficient-similarity-analyses"><i class="fa fa-check"></i>Comparing Chemistry vs. Toxicity Sufficient Similarity Analyses</a></li>
<li class="chapter" data-level="" data-path="mixtures-analysis-methods-part-3-sufficient-similarity.html"><a href="mixtures-analysis-methods-part-3-sufficient-similarity.html#concluding-remarks-27"><i class="fa fa-check"></i>Concluding Remarks</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="toxicokinetic-modeling.html"><a href="toxicokinetic-modeling.html"><i class="fa fa-check"></i>6.6 Toxicokinetic Modeling</a>
<ul>
<li class="chapter" data-level="" data-path="toxicokinetic-modeling.html"><a href="toxicokinetic-modeling.html#introduction-to-training-module-28"><i class="fa fa-check"></i>Introduction to Training Module</a></li>
<li class="chapter" data-level="" data-path="toxicokinetic-modeling.html"><a href="toxicokinetic-modeling.html#introduction-to-toxicokinetic-modeling"><i class="fa fa-check"></i>Introduction to Toxicokinetic Modeling</a></li>
<li class="chapter" data-level="" data-path="toxicokinetic-modeling.html"><a href="toxicokinetic-modeling.html#data-and-models-used-in-toxicokinetic-modeling-tk"><i class="fa fa-check"></i>Data and Models used in Toxicokinetic Modeling (TK)</a></li>
<li class="chapter" data-level="" data-path="toxicokinetic-modeling.html"><a href="toxicokinetic-modeling.html#reverse-toxicokinetics"><i class="fa fa-check"></i>Reverse Toxicokinetics</a></li>
<li class="chapter" data-level="" data-path="toxicokinetic-modeling.html"><a href="toxicokinetic-modeling.html#capturing-population-variability-in-toxicokinetics-and-uncertainty-in-chemical-specific-parameters"><i class="fa fa-check"></i>Capturing Population Variability in Toxicokinetics, and Uncertainty in Chemical-Specific Parameters</a></li>
<li class="chapter" data-level="" data-path="toxicokinetic-modeling.html"><a href="toxicokinetic-modeling.html#reverse-tk-calculating-administered-equivalent-doses-for-toxcast-bioactive-concentrations"><i class="fa fa-check"></i>Reverse TK: Calculating Administered Equivalent Doses for ToxCast Bioactive Concentrations</a></li>
<li class="chapter" data-level="" data-path="toxicokinetic-modeling.html"><a href="toxicokinetic-modeling.html#comparing-equivalent-doses-estimated-to-elicit-toxicity-hazard-to-external-exposure-estimates-exposure-for-chemical-prioritization-by-bioactivity-exposure-ratios-bers"><i class="fa fa-check"></i>Comparing Equivalent Doses Estimated to Elicit Toxicity (Hazard) to External Exposure Estimates (Exposure), for Chemical Prioritization by Bioactivity-Exposure Ratios (BERs)</a></li>
</ul></li>
<li class="part"><span><b>Chapter 7 Environmental<br> Health Database Mining</b></span></li>
<li class="chapter" data-level="" data-path="comparative-toxicogenomics-database.html"><a href="comparative-toxicogenomics-database.html"><i class="fa fa-check"></i>7.1 Comparative Toxicogenomics Database</a>
<ul>
<li class="chapter" data-level="" data-path="comparative-toxicogenomics-database.html"><a href="comparative-toxicogenomics-database.html#introduction-to-training-module-30"><i class="fa fa-check"></i>Introduction to Training Module</a></li>
<li class="chapter" data-level="" data-path="comparative-toxicogenomics-database.html"><a href="comparative-toxicogenomics-database.html#ctd-data-in-r"><i class="fa fa-check"></i>CTD Data in R</a></li>
<li class="chapter" data-level="" data-path="comparative-toxicogenomics-database.html"><a href="comparative-toxicogenomics-database.html#identifying-genes-under-epigenetic-control"><i class="fa fa-check"></i>Identifying Genes Under Epigenetic Control</a></li>
<li class="chapter" data-level="" data-path="comparative-toxicogenomics-database.html"><a href="comparative-toxicogenomics-database.html#concluding-remarks-30"><i class="fa fa-check"></i>Concluding Remarks</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="gene-expression-omnibus.html"><a href="gene-expression-omnibus.html"><i class="fa fa-check"></i>7.2 Gene Expression Omnibus</a>
<ul>
<li class="chapter" data-level="" data-path="gene-expression-omnibus.html"><a href="gene-expression-omnibus.html#introduction-to-training-module-31"><i class="fa fa-check"></i>Introduction to Training Module</a></li>
<li class="chapter" data-level="" data-path="gene-expression-omnibus.html"><a href="gene-expression-omnibus.html#introduction-to-geo"><i class="fa fa-check"></i>Introduction to GEO</a></li>
<li class="chapter" data-level="" data-path="gene-expression-omnibus.html"><a href="gene-expression-omnibus.html#introduction-to-example-data-4"><i class="fa fa-check"></i>Introduction to Example Data</a></li>
<li class="chapter" data-level="" data-path="gene-expression-omnibus.html"><a href="gene-expression-omnibus.html#geo-data-in-r"><i class="fa fa-check"></i>GEO Data in R</a></li>
<li class="chapter" data-level="" data-path="gene-expression-omnibus.html"><a href="gene-expression-omnibus.html#visualizing-data"><i class="fa fa-check"></i>Visualizing Data</a></li>
<li class="chapter" data-level="" data-path="gene-expression-omnibus.html"><a href="gene-expression-omnibus.html#statistical-analyses"><i class="fa fa-check"></i>Statistical Analyses</a></li>
<li class="chapter" data-level="" data-path="gene-expression-omnibus.html"><a href="gene-expression-omnibus.html#concluding-remarks-31"><i class="fa fa-check"></i>Concluding Remarks</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="comptox-dashboard-data-through-apis.html"><a href="comptox-dashboard-data-through-apis.html"><i class="fa fa-check"></i>7.3 CompTox Dashboard Data through APIs</a>
<ul>
<li class="chapter" data-level="" data-path="comptox-dashboard-data-through-apis.html"><a href="comptox-dashboard-data-through-apis.html#introduction-to-training-module-32"><i class="fa fa-check"></i>Introduction to Training Module</a></li>
<li class="chapter" data-level="" data-path="comptox-dashboard-data-through-apis.html"><a href="comptox-dashboard-data-through-apis.html#training-modules-environmental-health-questions-24"><i class="fa fa-check"></i>Training Module’s Environmental Health Questions</a></li>
<li class="chapter" data-level="" data-path="comptox-dashboard-data-through-apis.html"><a href="comptox-dashboard-data-through-apis.html#script-preparations-12"><i class="fa fa-check"></i>Script Preparations</a></li>
<li class="chapter" data-level="" data-path="comptox-dashboard-data-through-apis.html"><a href="comptox-dashboard-data-through-apis.html#introduction-to-comptox-chemicals-dashboard"><i class="fa fa-check"></i>Introduction to CompTox Chemicals Dashboard</a></li>
<li class="chapter" data-level="" data-path="comptox-dashboard-data-through-apis.html"><a href="comptox-dashboard-data-through-apis.html#cctes-ctx-application-programming-interfaces-apis-for-automated-batch-search-of-the-ccd"><i class="fa fa-check"></i>CCTE’s CTX Application Programming Interfaces (APIs) for Automated Batch Search of the CCD</a></li>
<li class="chapter" data-level="" data-path="comptox-dashboard-data-through-apis.html"><a href="comptox-dashboard-data-through-apis.html#comparing-physico-chemical-properties-between-two-important-environmental-contaminant-lists"><i class="fa fa-check"></i>Comparing Physico-chemical Properties between Two Important Environmental Contaminant Lists</a></li>
<li class="chapter" data-level="" data-path="comptox-dashboard-data-through-apis.html"><a href="comptox-dashboard-data-through-apis.html#hazard-data-genotoxicity"><i class="fa fa-check"></i>Hazard Data: Genotoxicity</a></li>
<li class="chapter" data-level="" data-path="comptox-dashboard-data-through-apis.html"><a href="comptox-dashboard-data-through-apis.html#hazard-resource"><i class="fa fa-check"></i>Hazard Resource</a></li>
<li class="chapter" data-level="" data-path="comptox-dashboard-data-through-apis.html"><a href="comptox-dashboard-data-through-apis.html#concluding-remarks-32"><i class="fa fa-check"></i>Concluding Remarks</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="database-integration-air-quality-mortality-and-environmental-justice-data.html"><a href="database-integration-air-quality-mortality-and-environmental-justice-data.html"><i class="fa fa-check"></i>7.4 Database Integration: Air Quality, Mortality, and Environmental Justice Data</a>
<ul>
<li class="chapter" data-level="" data-path="database-integration-air-quality-mortality-and-environmental-justice-data.html"><a href="database-integration-air-quality-mortality-and-environmental-justice-data.html#introduction-to-training-module-33"><i class="fa fa-check"></i>Introduction to Training Module</a></li>
<li class="chapter" data-level="" data-path="database-integration-air-quality-mortality-and-environmental-justice-data.html"><a href="database-integration-air-quality-mortality-and-environmental-justice-data.html#introduction-to-exposure-and-health-databases"><i class="fa fa-check"></i>Introduction to Exposure and Health Databases</a></li>
<li class="chapter" data-level="" data-path="database-integration-air-quality-mortality-and-environmental-justice-data.html"><a href="database-integration-air-quality-mortality-and-environmental-justice-data.html#analyzing-relationships-between-pm2.5-and-mortality"><i class="fa fa-check"></i>Analyzing Relationships between PM<sub>2.5</sub> and Mortality</a></li>
<li class="chapter" data-level="" data-path="database-integration-air-quality-mortality-and-environmental-justice-data.html"><a href="database-integration-air-quality-mortality-and-environmental-justice-data.html#environmental-justice-considerations"><i class="fa fa-check"></i>Environmental Justice Considerations</a></li>
<li class="chapter" data-level="" data-path="database-integration-air-quality-mortality-and-environmental-justice-data.html"><a href="database-integration-air-quality-mortality-and-environmental-justice-data.html#concluding-remarks-33"><i class="fa fa-check"></i>Concluding Remarks</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">TAME 2.0: An Update to the TAME Toolkit for Introductory Data Science, Chemical-Biological Analyses, Machine Learning and Predictive Modeling, and Database Mining for Environmental Health Research</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="gene-expression-omnibus" class="section level1 hasAnchor">
<h1>7.2 Gene Expression Omnibus<a href="gene-expression-omnibus.html#gene-expression-omnibus" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>This training module was developed by Kyle R. Roell and Julia E. Rager.</p>
<p>All input files (script, data, and figures) can be downloaded from the <a href="https://github.com/UNCSRP/TAME2">UNC-SRP TAME2 GitHub website</a>.</p>
<div id="introduction-to-training-module-31" class="section level2 hasAnchor">
<h2>Introduction to Training Module<a href="gene-expression-omnibus.html#introduction-to-training-module-31" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><a href="https://www.ncbi.nlm.nih.gov/geo/">GEO</a> is a publicly available database repository of high-throughput gene expression data and hybridization arrays, chips, and microarrays that span genome-wide endpoints of genomics, transcriptomics, and epigenomics. This training module specifically guides trainees through the loading of required packages and data, including the manual upload of GEO data as well as the upload/organization of data leveraging the <a href="https://www.bioconductor.org/packages/release/bioc/html/GEOquery.html">GEOquery package</a>. Data are then further organized and combined with gene annotation information through the merging of platform annotation files. Example visualizations are then produced, including boxplots to evaluate the overall distribution of expression data across samples, as well as heat map visualizations that compare unscaled versus scaled gene expression values. Statistical analyses are then included to identify which genes are significantly altered in expression upon exposure to formaldehyde. Together, this training module serves as a simple example showing methods to access and download GEO data and to perform data organization, analysis, and visualization tasks through applications-based questions.</p>
</div>
<div id="introduction-to-geo" class="section level2 hasAnchor">
<h2>Introduction to GEO<a href="gene-expression-omnibus.html#introduction-to-geo" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The GEO repository is organized and managed by the <a href="https://www.ncbi.nlm.nih.gov/">The National Center for Biotechnology Information (NCBI)</a>, which seeks to advance science and health by providing access to biomedical and genomic information. The three <a href="https://www.ncbi.nlm.nih.gov/geo/info/overview.html">overall goals</a> of GEO are to: (1) Provide a robust, versatile database in which to efficiently store high-throughput functional genomic data, (2) Offer simple submission procedures and formats that support complete and well-annotated data deposits from the research community, and (3) Provide user-friendly mechanisms that allow users to query, locate, review and download studies and gene expression profiles of interest.</p>
<p>Of high relevance to environmental health, data organized within GEO can be pulled and analyzed to address new environmental health questions, leveraging previously generated data. For example, we have pulled gene expression data from acute myeloid leukemia patients and re-analyzed these data to elucidate new mechanisms of epigenetically-regulated networks involved in cancer, that in turn, may be modified by environmental insults, as previously published in <a href="https://pubmed.ncbi.nlm.nih.gov/22754483/">Rager et al. 2012</a>. We have also pulled and analyzed gene expression data from published studies evaluating toxicity resulting from hexavalent chromium exposure, to further substantiate the role of epigenetic mediators in hexavelent chromium-induced carcinogenesis (see <a href="https://pubmed.ncbi.nlm.nih.gov/30690063/">Rager et al. 2019</a>). This training exercise leverages an additional dataset that we published and deposited through GEO to evaluate the effects of formaldehyde inhalation exposure, as detailed below.</p>
</div>
<div id="introduction-to-example-data-4" class="section level2 hasAnchor">
<h2>Introduction to Example Data<a href="gene-expression-omnibus.html#introduction-to-example-data-4" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In this training module, data will be pulled from the published GEO dataset recorded through the online series <a href="https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE42394">GSE42394</a>. This series represents Affymetrix rat genome-wide microarray data generated from our previous study, aimed at evaluating the transcriptomic effects of formaldehyde across three tissues: the nose, blood, and bone marrow. For the purposes of this training module, we will focus on evaluating gene expression profiles from nasal samples after 7 days of exposure, collected from rats exposed to 2 ppm formaldehyde via inhalation. These findings, in addition to other epigenomic endpoint measures, have been previously published (see <a href="https://pubmed.ncbi.nlm.nih.gov/24304932/">Rager et al. 2014</a>).</p>
<div id="training-modules-environmental-health-questions-23" class="section level3 hasAnchor">
<h3>Training Module’s Environmental Health Questions<a href="gene-expression-omnibus.html#training-modules-environmental-health-questions-23" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>This training module was specifically developed to answer the following environmental health questions:</p>
<ol style="list-style-type: decimal">
<li>What kind of molecular identifiers are commonly used in microarray-based -omics technologies?</li>
<li>How can we convert platform-specific molecular identifiers used in -omics study designs to gene-level information?</li>
<li>Why do we often scale gene expression signatures prior to heat map visualizations?</li>
<li>What genes are altered in expression by formaldehyde inhalation exposure?</li>
<li>What are the potential biological consequences of these gene-level perturbations?</li>
</ol>
</div>
<div id="script-preparations-11" class="section level3 hasAnchor">
<h3>Script Preparations<a href="gene-expression-omnibus.html#script-preparations-11" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="cleaning-the-global-environment-13" class="section level4 hasAnchor">
<h4>Cleaning the global environment<a href="gene-expression-omnibus.html#cleaning-the-global-environment-13" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb1008"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1008-1"><a href="gene-expression-omnibus.html#cb1008-1" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list=</span><span class="fu">ls</span>())</span></code></pre></div>
</div>
<div id="installing-required-r-packages-13" class="section level4 hasAnchor">
<h4>Installing required R packages<a href="gene-expression-omnibus.html#installing-required-r-packages-13" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>If you already have these packages installed, you can skip this step, or you can run the below code which checks installation status for you</p>
<div class="sourceCode" id="cb1009"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1009-1"><a href="gene-expression-omnibus.html#cb1009-1" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">requireNamespace</span>(<span class="st">&quot;tidyverse&quot;</span>))</span>
<span id="cb1009-2"><a href="gene-expression-omnibus.html#cb1009-2" tabindex="-1"></a>  <span class="fu">install.packages</span>(<span class="st">&quot;tidyverse&quot;</span>)</span>
<span id="cb1009-3"><a href="gene-expression-omnibus.html#cb1009-3" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">requireNamespace</span>(<span class="st">&quot;reshape2&quot;</span>))</span>
<span id="cb1009-4"><a href="gene-expression-omnibus.html#cb1009-4" tabindex="-1"></a>    <span class="fu">install.packages</span>(<span class="st">&quot;reshape2&quot;</span>)</span>
<span id="cb1009-5"><a href="gene-expression-omnibus.html#cb1009-5" tabindex="-1"></a></span>
<span id="cb1009-6"><a href="gene-expression-omnibus.html#cb1009-6" tabindex="-1"></a><span class="co"># GEOquery, this will install BiocManager if you don&#39;t have it installed</span></span>
<span id="cb1009-7"><a href="gene-expression-omnibus.html#cb1009-7" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">requireNamespace</span>(<span class="st">&quot;BiocManager&quot;</span>))</span>
<span id="cb1009-8"><a href="gene-expression-omnibus.html#cb1009-8" tabindex="-1"></a>  <span class="fu">install.packages</span>(<span class="st">&quot;BiocManager&quot;</span>)</span>
<span id="cb1009-9"><a href="gene-expression-omnibus.html#cb1009-9" tabindex="-1"></a>BiocManager<span class="sc">::</span><span class="fu">install</span>(<span class="st">&quot;GEOquery&quot;</span>)</span></code></pre></div>
<pre><code>## Warning: package(s) not installed when version(s) same as or greater than current; use
##   `force = TRUE` to re-install: &#39;GEOquery&#39;</code></pre>
</div>
<div id="loading-r-packages-required-for-this-session-11" class="section level4 hasAnchor">
<h4>Loading R packages required for this session<a href="gene-expression-omnibus.html#loading-r-packages-required-for-this-session-11" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb1011"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1011-1"><a href="gene-expression-omnibus.html#cb1011-1" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1011-2"><a href="gene-expression-omnibus.html#cb1011-2" tabindex="-1"></a><span class="fu">library</span>(reshape2)</span>
<span id="cb1011-3"><a href="gene-expression-omnibus.html#cb1011-3" tabindex="-1"></a><span class="fu">library</span>(GEOquery)</span></code></pre></div>
<p>For more information on the <strong>tidyverse package</strong>, see its associated <a href="https://cran.r-project.org/web/packages/tidyverse/index.html">CRAN webpage</a>, primary <a href="https://www.tidyverse.org/packages/">webpage</a>, and peer-reviewed <a href="https://onlinelibrary.wiley.com/doi/10.1002/sdr.1600">article released in 2018</a>.</p>
<p>For more information on the <strong>reshape2 package</strong>, see its associated <a href="https://cran.r-project.org/web/packages/reshape2/index.html">CRAN webpage</a>, <a href="https://www.rdocumentation.org/packages/reshape2/versions/1.4.4">R Documentation</a>, and <a href="https://seananderson.ca/2013/10/19/reshape/">helpful website</a> providing an introduction to the reshape2 package.</p>
<p>For more information on the <strong>GEOquery package</strong>, see its associated <a href="https://www.bioconductor.org/packages/release/bioc/html/GEOquery.html">Bioconductor website</a> and <a href="https://www.rdocumentation.org/packages/GEOquery/versions/2.38.4">R Documentation file</a>.</p>
</div>
<div id="set-your-working-directory-16" class="section level4 hasAnchor">
<h4>Set your working directory<a href="gene-expression-omnibus.html#set-your-working-directory-16" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb1012"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1012-1"><a href="gene-expression-omnibus.html#cb1012-1" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">&quot;/filepath to where your input files are&quot;</span>)</span></code></pre></div>
</div>
</div>
</div>
<div id="geo-data-in-r" class="section level2 hasAnchor">
<h2>GEO Data in R<a href="gene-expression-omnibus.html#geo-data-in-r" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Let’s start by loading the GEO dataset needed for this training module. As explained in the introduction, this module walks through two methods of uploading GEO data: manual option vs automatic option using the GEOquery package. These two methods are detailed below.</p>
<div id="manually-downloading-and-uploading-geo-files" class="section level3 hasAnchor">
<h3>1. Manually Downloading and Uploading GEO Files<a href="gene-expression-omnibus.html#manually-downloading-and-uploading-geo-files" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In this first method, we will navigate to the dataset within the GEO website, manually download its associated text data file, save it in our working directory, and then upload it into our global environment in R.</p>
<p>For the purposes of this training exercise, we manually downloaded the GEO series matrix file from the GEO series webpage, located at: <a href="https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE42394" class="uri">https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE42394</a>. The specific file that was downloaded was noted as “GSE42394_series_matrix.txt”, pulled by clicking on the link indicated by the red arrow from the GEO series webpage:</p>
<p><img src="Module7_2_Input/Module7_2_Image1.png" width="506" style="display: block; margin: auto;" /></p>
<p>For simplicity, we also have already pre-filtered this file for the samples we are interested in, focusing on the rat nasal gene expression data after 7 days of exposure to gaseous formaldehyde. This filtered file was saved as “GSE42394_series_matrix_filtered.txt”, then renamed “Module7_2_InputData1.txt” for use in this module.</p>
<p>At this point, we can simply read in this pre-filtered text file for the purposes of this training module</p>
<div class="sourceCode" id="cb1013"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1013-1"><a href="gene-expression-omnibus.html#cb1013-1" tabindex="-1"></a>geodata_manual <span class="ot">=</span> <span class="fu">read.table</span>(<span class="at">file=</span><span class="st">&quot;Module7_2_Input/Module7_2_InputData1.txt&quot;</span>,</span>
<span id="cb1013-2"><a href="gene-expression-omnibus.html#cb1013-2" tabindex="-1"></a>                             <span class="at">header=</span>T)</span></code></pre></div>
<p>Because this is a manual approach, we have to also manually define the treated and untreated samples (based on manually opening the surrounding metadata from the GEO webpage)</p>
<p>Manually defining treated and untreated for these samples of interest:</p>
<div class="sourceCode" id="cb1014"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1014-1"><a href="gene-expression-omnibus.html#cb1014-1" tabindex="-1"></a>exposed_manual <span class="ot">=</span> <span class="fu">c</span>(<span class="st">&quot;GSM1150940&quot;</span>, <span class="st">&quot;GSM1150941&quot;</span>, <span class="st">&quot;GSM1150942&quot;</span>)</span>
<span id="cb1014-2"><a href="gene-expression-omnibus.html#cb1014-2" tabindex="-1"></a>unexposed_manual <span class="ot">=</span> <span class="fu">c</span>(<span class="st">&quot;GSM1150937&quot;</span>, <span class="st">&quot;GSM1150938&quot;</span>, <span class="st">&quot;GSM1150939&quot;</span>)</span></code></pre></div>
</div>
<div id="loading-and-organizing-geo-files-through-the-geoquery-package" class="section level3 hasAnchor">
<h3>2. Loading and Organizing GEO Files through the GEOquery Package<a href="gene-expression-omnibus.html#loading-and-organizing-geo-files-through-the-geoquery-package" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In this second method, we will leverage the GEOquery package, which allows for easier downloading and reading in of data from GEO without having to manually download raw text files, and manually assign sample attributes (e.g., exposed vs unexposed). This package is set-up to automatically merge sample information from GEO metadata files with raw genome-wide datasets.</p>
<p>Let’s first use the getGEO function (from the GEOquery package) to load data from our series matrix (“GSE42394_series_matrix.txt”, renamed “Module7_2_InputData2.txt” for use in this module). <em>Note that this line of code may take a couple of minutes to run.</em></p>
<div class="sourceCode" id="cb1015"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1015-1"><a href="gene-expression-omnibus.html#cb1015-1" tabindex="-1"></a>geo.getGEO.data <span class="ot">=</span> <span class="fu">getGEO</span>(<span class="at">filename=</span><span class="st">&#39;Module7_2_Input/Module7_2_InputData2.txt&#39;</span>)</span></code></pre></div>
<p>One of the reasons the getGEO package is so helpful is that we can automatically link a dataset with nicely organized sample information using the <code>pData()</code> function.</p>
<div class="sourceCode" id="cb1016"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1016-1"><a href="gene-expression-omnibus.html#cb1016-1" tabindex="-1"></a>sampleInfo <span class="ot">=</span> <span class="fu">pData</span>(geo.getGEO.data)</span></code></pre></div>
<p>Let’s view this sample information / metadata file, first by viewing what the column headers are.</p>
<div class="sourceCode" id="cb1017"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1017-1"><a href="gene-expression-omnibus.html#cb1017-1" tabindex="-1"></a><span class="fu">colnames</span>(sampleInfo)</span></code></pre></div>
<pre><code>##  [1] &quot;title&quot;                   &quot;geo_accession&quot;          
##  [3] &quot;status&quot;                  &quot;submission_date&quot;        
##  [5] &quot;last_update_date&quot;        &quot;type&quot;                   
##  [7] &quot;channel_count&quot;           &quot;source_name_ch1&quot;        
##  [9] &quot;organism_ch1&quot;            &quot;characteristics_ch1&quot;    
## [11] &quot;characteristics_ch1.1&quot;   &quot;characteristics_ch1.2&quot;  
## [13] &quot;characteristics_ch1.3&quot;   &quot;characteristics_ch1.4&quot;  
## [15] &quot;characteristics_ch1.5&quot;   &quot;treatment_protocol_ch1&quot; 
## [17] &quot;growth_protocol_ch1&quot;     &quot;molecule_ch1&quot;           
## [19] &quot;extract_protocol_ch1&quot;    &quot;label_ch1&quot;              
## [21] &quot;label_protocol_ch1&quot;      &quot;taxid_ch1&quot;              
## [23] &quot;hyb_protocol&quot;            &quot;scan_protocol&quot;          
## [25] &quot;description&quot;             &quot;data_processing&quot;        
## [27] &quot;platform_id&quot;             &quot;contact_name&quot;           
## [29] &quot;contact_email&quot;           &quot;contact_department&quot;     
## [31] &quot;contact_institute&quot;       &quot;contact_address&quot;        
## [33] &quot;contact_city&quot;            &quot;contact_zip/postal_code&quot;
## [35] &quot;contact_country&quot;         &quot;supplementary_file&quot;     
## [37] &quot;data_row_count&quot;          &quot;age:ch1&quot;                
## [39] &quot;cell type:ch1&quot;           &quot;gender:ch1&quot;             
## [41] &quot;strain:ch1&quot;              &quot;time:ch1&quot;               
## [43] &quot;treatment:ch1&quot;</code></pre>
<p>Then viewing the first five columns.</p>
<div class="sourceCode" id="cb1019"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1019-1"><a href="gene-expression-omnibus.html#cb1019-1" tabindex="-1"></a>sampleInfo[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>]</span></code></pre></div>
<pre><code>##                                                    title geo_accession
## GSM1150937            Nose_7DayControl_Rep1 [Affymetrix]    GSM1150937
## GSM1150938            Nose_7DayControl_Rep2 [Affymetrix]    GSM1150938
## GSM1150939            Nose_7DayControl_Rep3 [Affymetrix]    GSM1150939
## GSM1150940            Nose_7DayExposed_Rep1 [Affymetrix]    GSM1150940
## GSM1150941            Nose_7DayExposed_Rep2 [Affymetrix]    GSM1150941
## GSM1150942            Nose_7DayExposed_Rep3 [Affymetrix]    GSM1150942
## GSM1150943 WhiteBloodCells_7DayControl_Rep1 [Affymetrix]    GSM1150943
## GSM1150944 WhiteBloodCells_7DayControl_Rep2 [Affymetrix]    GSM1150944
## GSM1150945 WhiteBloodCells_7DayControl_Rep3 [Affymetrix]    GSM1150945
## GSM1150946 WhiteBloodCells_7DayExposed_Rep1 [Affymetrix]    GSM1150946
##                           status submission_date last_update_date
## GSM1150937 Public on Jan 07 2014     May 29 2013      Jan 07 2014
## GSM1150938 Public on Jan 07 2014     May 29 2013      Jan 07 2014
## GSM1150939 Public on Jan 07 2014     May 29 2013      Jan 07 2014
## GSM1150940 Public on Jan 07 2014     May 29 2013      Jan 07 2014
## GSM1150941 Public on Jan 07 2014     May 29 2013      Jan 07 2014
## GSM1150942 Public on Jan 07 2014     May 29 2013      Jan 07 2014
## GSM1150943 Public on Jan 07 2014     May 29 2013      Jan 07 2014
## GSM1150944 Public on Jan 07 2014     May 29 2013      Jan 07 2014
## GSM1150945 Public on Jan 07 2014     May 29 2013      Jan 07 2014
## GSM1150946 Public on Jan 07 2014     May 29 2013      Jan 07 2014</code></pre>
<p>This shows that each sample is provided with a unique number starting with “GSM”, and these are described by information summarized in the “title” column. We can also see that these data were made public on Jan 7, 2014.</p>
<p>Let’s view the next five columns.</p>
<div class="sourceCode" id="cb1021"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1021-1"><a href="gene-expression-omnibus.html#cb1021-1" tabindex="-1"></a>sampleInfo[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>,<span class="dv">6</span><span class="sc">:</span><span class="dv">10</span>]</span></code></pre></div>
<pre><code>##            type channel_count                                 source_name_ch1
## GSM1150937  RNA             1        Nasal epithelial cells, 7 day, unexposed
## GSM1150938  RNA             1        Nasal epithelial cells, 7 day, unexposed
## GSM1150939  RNA             1        Nasal epithelial cells, 7 day, unexposed
## GSM1150940  RNA             1          Nasal epithelial cells, 7 day, exposed
## GSM1150941  RNA             1          Nasal epithelial cells, 7 day, exposed
## GSM1150942  RNA             1          Nasal epithelial cells, 7 day, exposed
## GSM1150943  RNA             1 Circulating white blood cells, 7 day, unexposed
## GSM1150944  RNA             1 Circulating white blood cells, 7 day, unexposed
## GSM1150945  RNA             1 Circulating white blood cells, 7 day, unexposed
## GSM1150946  RNA             1   Circulating white blood cells, 7 day, exposed
##                 organism_ch1 characteristics_ch1
## GSM1150937 Rattus norvegicus        gender: male
## GSM1150938 Rattus norvegicus        gender: male
## GSM1150939 Rattus norvegicus        gender: male
## GSM1150940 Rattus norvegicus        gender: male
## GSM1150941 Rattus norvegicus        gender: male
## GSM1150942 Rattus norvegicus        gender: male
## GSM1150943 Rattus norvegicus        gender: male
## GSM1150944 Rattus norvegicus        gender: male
## GSM1150945 Rattus norvegicus        gender: male
## GSM1150946 Rattus norvegicus        gender: male</code></pre>
<p>We can see that information is provided here surrounding the type of sample that was analyzed (i.e., RNA), more information on the collected samples within the column <code>source_name_ch1</code>, and the organism (rat) is provided in the <code>organism_ch1</code> column.</p>
<p>More detailed metadata information is provided throughout this file, as seen when viewing the column headers above.</p>
<div id="defining-samples" class="section level4 hasAnchor">
<h4>Defining samples<a href="gene-expression-omnibus.html#defining-samples" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Now, we can use this information to define the samples we want to analyze. Note that this is the same step we did manually above.</p>
<p>In this training exercise, we are focusing on responses in the nose, so we can easily filter for cell type = Nasal epithelial cells (specifically in the <code>cell type:ch1</code> variable). We are also focusing on responses collected after 7 days of exposure, which we can filter for using time = 7 day (specifically in the <code>time:ch1</code> variable). We will also define exposed and unexposed samples using the variable <code>treatment:ch1</code>.</p>
<p>First, let’s subset the sampleInfo dataframe to just keep the samples we’re interested in</p>
<div class="sourceCode" id="cb1023"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1023-1"><a href="gene-expression-omnibus.html#cb1023-1" tabindex="-1"></a><span class="co"># Define a vector variable (here we call it &#39;keep&#39;) that will store rows we want to keep</span></span>
<span id="cb1023-2"><a href="gene-expression-omnibus.html#cb1023-2" tabindex="-1"></a>keep <span class="ot">=</span> <span class="fu">rownames</span>(sampleInfo[<span class="fu">which</span>(sampleInfo<span class="sc">$</span><span class="st">`</span><span class="at">cell type:ch1</span><span class="st">`</span><span class="sc">==</span><span class="st">&quot;Nasal epithelial cells&quot;</span> </span>
<span id="cb1023-3"><a href="gene-expression-omnibus.html#cb1023-3" tabindex="-1"></a>                                  <span class="sc">&amp;</span> sampleInfo<span class="sc">$</span><span class="st">`</span><span class="at">time:ch1</span><span class="st">`</span><span class="sc">==</span><span class="st">&quot;7 day&quot;</span>),])</span>
<span id="cb1023-4"><a href="gene-expression-omnibus.html#cb1023-4" tabindex="-1"></a></span>
<span id="cb1023-5"><a href="gene-expression-omnibus.html#cb1023-5" tabindex="-1"></a><span class="co"># Then subset the sample info for just those samples we defined in keep variable</span></span>
<span id="cb1023-6"><a href="gene-expression-omnibus.html#cb1023-6" tabindex="-1"></a>sampleInfo <span class="ot">=</span> sampleInfo[keep,]</span></code></pre></div>
<p>Next, we can pull the exposed and unexposed animal IDs. Let’s first see how these are labeled within the <code>treatment:ch1</code> variable.</p>
<div class="sourceCode" id="cb1024"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1024-1"><a href="gene-expression-omnibus.html#cb1024-1" tabindex="-1"></a><span class="fu">unique</span>(sampleInfo<span class="sc">$</span><span class="st">`</span><span class="at">treatment:ch1</span><span class="st">`</span>)</span></code></pre></div>
<pre><code>## [1] &quot;unexposed&quot;          &quot;2 ppm formaldehyde&quot;</code></pre>
<p>And then search for the rows of data, pulling the sample animal IDs (which are in the variable <code>geo_accession</code>).</p>
<div class="sourceCode" id="cb1026"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1026-1"><a href="gene-expression-omnibus.html#cb1026-1" tabindex="-1"></a>exposedIDs <span class="ot">=</span> sampleInfo[<span class="fu">which</span>(sampleInfo<span class="sc">$</span><span class="st">`</span><span class="at">treatment:ch1</span><span class="st">`</span><span class="sc">==</span><span class="st">&quot;2 ppm formaldehyde&quot;</span>), </span>
<span id="cb1026-2"><a href="gene-expression-omnibus.html#cb1026-2" tabindex="-1"></a>                          <span class="st">&quot;geo_accession&quot;</span>]</span>
<span id="cb1026-3"><a href="gene-expression-omnibus.html#cb1026-3" tabindex="-1"></a>unexposedIDs <span class="ot">=</span> sampleInfo[<span class="fu">which</span>(sampleInfo<span class="sc">$</span><span class="st">`</span><span class="at">treatment:ch1</span><span class="st">`</span><span class="sc">==</span><span class="st">&quot;unexposed&quot;</span>), </span>
<span id="cb1026-4"><a href="gene-expression-omnibus.html#cb1026-4" tabindex="-1"></a>                            <span class="st">&quot;geo_accession&quot;</span>]</span></code></pre></div>
<p>The next step is to pull the expression data we want to use in our analyses. The GEOquery function, <code>exprs()</code>, allows us to easily pull these data. Here, we can pull the data we’re interested in using the <code>exprs()</code> function, while defining the data we want to pull based off our previously generated ‘keep’ vector.</p>
<div class="sourceCode" id="cb1027"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1027-1"><a href="gene-expression-omnibus.html#cb1027-1" tabindex="-1"></a><span class="co"># As a reminder, this is what the &#39;keep&#39; vector includes </span></span>
<span id="cb1027-2"><a href="gene-expression-omnibus.html#cb1027-2" tabindex="-1"></a><span class="co"># (i.e., animal IDs that we&#39;re interested in)</span></span>
<span id="cb1027-3"><a href="gene-expression-omnibus.html#cb1027-3" tabindex="-1"></a>keep</span></code></pre></div>
<pre><code>## [1] &quot;GSM1150937&quot; &quot;GSM1150938&quot; &quot;GSM1150939&quot; &quot;GSM1150940&quot; &quot;GSM1150941&quot;
## [6] &quot;GSM1150942&quot;</code></pre>
<div class="sourceCode" id="cb1029"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1029-1"><a href="gene-expression-omnibus.html#cb1029-1" tabindex="-1"></a><span class="co"># Using the exprs() function</span></span>
<span id="cb1029-2"><a href="gene-expression-omnibus.html#cb1029-2" tabindex="-1"></a>geodata <span class="ot">=</span> <span class="fu">exprs</span>(geo.getGEO.data[,keep])</span></code></pre></div>
<p>Let’s view the full dataset as is now:</p>
<div class="sourceCode" id="cb1030"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1030-1"><a href="gene-expression-omnibus.html#cb1030-1" tabindex="-1"></a><span class="fu">head</span>(geodata)</span></code></pre></div>
<pre><code>##          GSM1150937 GSM1150938 GSM1150939 GSM1150940 GSM1150941 GSM1150942
## 10700001    5786.60    5830.08    5637.34    5313.33    5557.04    5469.90
## 10700002     192.92     206.86     220.83     183.12     177.16     198.64
## 10700003    1820.98    1795.79    1735.70    1578.02    1681.58    1632.20
## 10700004      66.95      65.61      64.41      60.19      60.41      60.67
## 10700005     770.07     753.41     731.20     684.53     657.25     667.66
## 10700006       5.80       5.35       5.48       5.58       5.39       5.35</code></pre>
<p>This now represents a matrix of data, with animal IDs as column headers and expression levels within the matrix.</p>
</div>
<div id="simplifying-column-names" class="section level4 hasAnchor">
<h4>Simplifying column names<a href="gene-expression-omnibus.html#simplifying-column-names" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>These column names are not the easiest to interpret, so let’s rename these columns to indicate which animals were from the exposed vs. unexposed groups.</p>
<p>We need to first convert our expression dataset to a dataframe so we can edit columns names, and continue with downstream data manipulations that require dataframe formats.</p>
<div class="sourceCode" id="cb1032"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1032-1"><a href="gene-expression-omnibus.html#cb1032-1" tabindex="-1"></a>geodata <span class="ot">=</span> <span class="fu">data.frame</span>(geodata)</span></code></pre></div>
<p>Let’s remind ourselves what the column names are:</p>
<div class="sourceCode" id="cb1033"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1033-1"><a href="gene-expression-omnibus.html#cb1033-1" tabindex="-1"></a><span class="fu">colnames</span>(geodata)</span></code></pre></div>
<pre><code>## [1] &quot;GSM1150937&quot; &quot;GSM1150938&quot; &quot;GSM1150939&quot; &quot;GSM1150940&quot; &quot;GSM1150941&quot;
## [6] &quot;GSM1150942&quot;</code></pre>
<p>Which ones of these are exposed vs unexposed animals can be determined by viewing our previously defined vectors.</p>
<div class="sourceCode" id="cb1035"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1035-1"><a href="gene-expression-omnibus.html#cb1035-1" tabindex="-1"></a>exposedIDs</span></code></pre></div>
<pre><code>## [1] &quot;GSM1150940&quot; &quot;GSM1150941&quot; &quot;GSM1150942&quot;</code></pre>
<div class="sourceCode" id="cb1037"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1037-1"><a href="gene-expression-omnibus.html#cb1037-1" tabindex="-1"></a>unexposedIDs</span></code></pre></div>
<pre><code>## [1] &quot;GSM1150937&quot; &quot;GSM1150938&quot; &quot;GSM1150939&quot;</code></pre>
<p>With this we can tell that the first three listed IDs are from unexposed animals, and the last three IDs are from exposed animals.</p>
<p>Let’s simplify the names of these columns to indicate exposure status and replicate number.</p>
<div class="sourceCode" id="cb1039"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1039-1"><a href="gene-expression-omnibus.html#cb1039-1" tabindex="-1"></a><span class="fu">colnames</span>(geodata) <span class="ot">=</span> <span class="fu">c</span>(<span class="st">&quot;Control_1&quot;</span>, <span class="st">&quot;Control_2&quot;</span>, <span class="st">&quot;Control_3&quot;</span>, <span class="st">&quot;Exposed_1&quot;</span>, </span>
<span id="cb1039-2"><a href="gene-expression-omnibus.html#cb1039-2" tabindex="-1"></a>                       <span class="st">&quot;Exposed_2&quot;</span>, <span class="st">&quot;Exposed_3&quot;</span>)</span></code></pre></div>
<p>And we’ll now need to re-define our ‘exposed’ vs ‘unexposed’ vectors for downstream script.</p>
<div class="sourceCode" id="cb1040"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1040-1"><a href="gene-expression-omnibus.html#cb1040-1" tabindex="-1"></a>exposedIDs <span class="ot">=</span> <span class="fu">c</span>(<span class="st">&quot;Exposed_1&quot;</span>, <span class="st">&quot;Exposed_2&quot;</span>, <span class="st">&quot;Exposed_3&quot;</span>)</span>
<span id="cb1040-2"><a href="gene-expression-omnibus.html#cb1040-2" tabindex="-1"></a>unexposedIDs <span class="ot">=</span> <span class="fu">c</span>(<span class="st">&quot;Control_1&quot;</span>, <span class="st">&quot;Control_2&quot;</span>, <span class="st">&quot;Control_3&quot;</span>)</span></code></pre></div>
<p>Viewing the data again:</p>
<div class="sourceCode" id="cb1041"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1041-1"><a href="gene-expression-omnibus.html#cb1041-1" tabindex="-1"></a><span class="fu">head</span>(geodata)</span></code></pre></div>
<pre><code>##          Control_1 Control_2 Control_3 Exposed_1 Exposed_2 Exposed_3
## 10700001   5786.60   5830.08   5637.34   5313.33   5557.04   5469.90
## 10700002    192.92    206.86    220.83    183.12    177.16    198.64
## 10700003   1820.98   1795.79   1735.70   1578.02   1681.58   1632.20
## 10700004     66.95     65.61     64.41     60.19     60.41     60.67
## 10700005    770.07    753.41    731.20    684.53    657.25    667.66
## 10700006      5.80      5.35      5.48      5.58      5.39      5.35</code></pre>
<p>These data are now looking easier to interpret/analyze. Still, the row identifiers include 8 digit numbers starting with “107…”. We know that this dataset is a gene expression dataset, but these identifiers, in themselves, don’t tell us much about what genes these are referring to. These numeric IDs specifically represent microarray probesetIDs, that were produced by the Affymetrix platform used in the original study.</p>
<p><strong>But how can we tell which genes are represented by these data?!</strong></p>
</div>
<div id="adding-gene-symbol-information" class="section level4 hasAnchor">
<h4>Adding gene symbol information<a href="gene-expression-omnibus.html#adding-gene-symbol-information" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Each -omics dataset contained within GEO points to a specific platform that was used to obtain measurements.
In instances where we want more information surrounding the molecular identifiers, we can merge the platform-specific annotation file with the molecular IDs given in the full dataset.</p>
<p>For example, let’s pull the platform-specific annotation file for this experiment. Let’s revisit the <a href="https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE42394">website</a> that contained the original dataset on GEO. Scroll down to where it lists “Platforms”, and there is a hyperlinked platform number “GPL6247” (see arrow below).</p>
<p><img src="Module7_2_Input/Module7_2_Image2.png" width="509" style="display: block; margin: auto;" /></p>
<p>Click on this, and you will be navigated to a different GEO website describing the Affymetrix rat array platform that was used in this analysis. Note that this website also includes information on when this array became available, links to other experiments that have used this platform within GEO, and much more.</p>
<p>Here, we’re interested in pulling the corresponding gene symbol information for the probeset IDs. To do so, scroll to the bottom, and click “Annotation SOFT table…” and download the corresponding .gz file within your working directory. Unzip this, and you will find the master annotation file: “GPL6247.annot”.</p>
<p>In this exercise, we’ve already done these steps and unzipped the file in our working directory. So at this point, we can simply read in this annotation dataset, renamed “Module7_2_InputData2.annot”, still using the <code>GEOquery()</code> function to help automate.</p>
<div class="sourceCode" id="cb1043"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1043-1"><a href="gene-expression-omnibus.html#cb1043-1" tabindex="-1"></a>geo.annot <span class="ot">=</span> GEOquery<span class="sc">::</span><span class="fu">getGEO</span>(<span class="at">filename=</span><span class="st">&quot;Module7_2_Input/Module7_2_InputData3.annot&quot;</span>)</span></code></pre></div>
<p>Now we can use the <code>Table()</code> function from GEOquery to pull data from the annotation dataset.</p>
<div class="sourceCode" id="cb1044"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1044-1"><a href="gene-expression-omnibus.html#cb1044-1" tabindex="-1"></a>id.gene.table <span class="ot">=</span> GEOquery<span class="sc">::</span><span class="fu">Table</span>(geo.annot)[,<span class="fu">c</span>(<span class="st">&quot;ID&quot;</span>, <span class="st">&quot;Gene symbol&quot;</span>)]</span>
<span id="cb1044-2"><a href="gene-expression-omnibus.html#cb1044-2" tabindex="-1"></a>id.gene.table[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>]</span></code></pre></div>
<pre><code>##          ID                        Gene symbol
## 1  10701620 Vom2r67///Vom2r5///Vom2r6///Vom2r4
## 2  10701630                                   
## 3  10701632                                   
## 4  10701636                                   
## 5  10701643                                   
## 6  10701648                             Vom2r5
## 7  10701654                             Vom2r6
## 8  10701663                                   
## 9  10701666                                   
## 10 10701668                   Vom2r65///Vom2r1</code></pre>
<p>With these two columns of data, we now have the needed IDs and gene symbols to match with our dataset.</p>
<p>Within the full dataset, we need to add a new column for the probeset ID, taken from the rownames, in preparation for the merging step.</p>
<div class="sourceCode" id="cb1046"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1046-1"><a href="gene-expression-omnibus.html#cb1046-1" tabindex="-1"></a>geodata<span class="sc">$</span>ID <span class="ot">=</span> <span class="fu">rownames</span>(geodata)</span></code></pre></div>
<p>We can now merge the gene symbol information by ID with our expression data.</p>
<div class="sourceCode" id="cb1047"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1047-1"><a href="gene-expression-omnibus.html#cb1047-1" tabindex="-1"></a>geodata_genes <span class="ot">=</span> <span class="fu">merge</span>(geodata, id.gene.table, <span class="at">by=</span><span class="st">&quot;ID&quot;</span>)</span>
<span id="cb1047-2"><a href="gene-expression-omnibus.html#cb1047-2" tabindex="-1"></a><span class="fu">head</span>(geodata_genes)</span></code></pre></div>
<pre><code>##         ID Control_1 Control_2 Control_3 Exposed_1 Exposed_2 Exposed_3
## 1 10700001   5786.60   5830.08   5637.34   5313.33   5557.04   5469.90
## 2 10700002    192.92    206.86    220.83    183.12    177.16    198.64
## 3 10700003   1820.98   1795.79   1735.70   1578.02   1681.58   1632.20
## 4 10700004     66.95     65.61     64.41     60.19     60.41     60.67
## 5 10700005    770.07    753.41    731.20    684.53    657.25    667.66
## 6 10700006      5.80      5.35      5.48      5.58      5.39      5.35
##   Gene symbol
## 1            
## 2            
## 3            
## 4            
## 5            
## 6</code></pre>
<p>Note that many of the probeset IDs do not map to full gene symbols, which is shown here by viewing the top few rows - this is expected in genome-wide analyses based on microarray platforms.</p>
<p>Let’s look at the first 25 unique genes in these data:</p>
<div class="sourceCode" id="cb1049"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1049-1"><a href="gene-expression-omnibus.html#cb1049-1" tabindex="-1"></a>UniqueGenes <span class="ot">=</span> <span class="fu">unique</span>(geodata_genes<span class="sc">$</span><span class="st">`</span><span class="at">Gene symbol</span><span class="st">`</span>)</span>
<span id="cb1049-2"><a href="gene-expression-omnibus.html#cb1049-2" tabindex="-1"></a>UniqueGenes[<span class="dv">1</span><span class="sc">:</span><span class="dv">25</span>]</span></code></pre></div>
<pre><code>##  [1] &quot;&quot;                                           
##  [2] &quot;Vom2r67///Vom2r5///Vom2r6///Vom2r4&quot;         
##  [3] &quot;Vom2r5&quot;                                     
##  [4] &quot;Vom2r6&quot;                                     
##  [5] &quot;Vom2r65///Vom2r1&quot;                           
##  [6] &quot;Vom2r65///Vom2r5///Vom2r1///Vom2r6///Vom2r4&quot;
##  [7] &quot;Vom2r65///Vom2r5///Vom2r6///Vom2r4&quot;         
##  [8] &quot;Raet1e&quot;                                     
##  [9] &quot;Lrp11&quot;                                      
## [10] &quot;Katna1&quot;                                     
## [11] &quot;Ppil4&quot;                                      
## [12] &quot;Zc3h12d&quot;                                    
## [13] &quot;Shprh&quot;                                      
## [14] &quot;Fbxo30&quot;                                     
## [15] &quot;Epm2a&quot;                                      
## [16] &quot;Sf3b5&quot;                                      
## [17] &quot;Plagl1&quot;                                     
## [18] &quot;Fuca2&quot;                                      
## [19] &quot;Adat2&quot;                                      
## [20] &quot;Hivep2&quot;                                     
## [21] &quot;Nmbr&quot;                                       
## [22] &quot;Cited2&quot;                                     
## [23] &quot;Txlnb&quot;                                      
## [24] &quot;Reps1&quot;                                      
## [25] &quot;Perp&quot;</code></pre>
<p>Again, you can see that the first value listed is blank, representing probesetIDs that do not match to fully annotated gene symbols. Though the rest pertain for gene symbols annotated to the rat genome.</p>
<p>You can also see that some gene symbols have multiple entries, separated by “///”</p>
<p>To simplify identifiers, we can pull just the first gene symbol, and remove the rest by using gsub().</p>
<div class="sourceCode" id="cb1051"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1051-1"><a href="gene-expression-omnibus.html#cb1051-1" tabindex="-1"></a>geodata_genes<span class="sc">$</span><span class="st">`</span><span class="at">Gene symbol</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">gsub</span>(<span class="st">&quot;///.*&quot;</span>, <span class="st">&quot;&quot;</span>, geodata_genes<span class="sc">$</span><span class="st">`</span><span class="at">Gene symbol</span><span class="st">`</span>)</span></code></pre></div>
<p>Let’s alphabetize by main expression dataframe by gene symbol.</p>
<div class="sourceCode" id="cb1052"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1052-1"><a href="gene-expression-omnibus.html#cb1052-1" tabindex="-1"></a>geodata_genes <span class="ot">=</span> geodata_genes[<span class="fu">order</span>(geodata_genes<span class="sc">$</span><span class="st">`</span><span class="at">Gene symbol</span><span class="st">`</span>),]</span></code></pre></div>
<p>And then re-view these data:</p>
<div class="sourceCode" id="cb1053"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1053-1"><a href="gene-expression-omnibus.html#cb1053-1" tabindex="-1"></a>geodata_genes[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>,]</span></code></pre></div>
<pre><code>##         ID Control_1 Control_2 Control_3 Exposed_1 Exposed_2 Exposed_3
## 1 10700001   5786.60   5830.08   5637.34   5313.33   5557.04   5469.90
## 2 10700002    192.92    206.86    220.83    183.12    177.16    198.64
## 3 10700003   1820.98   1795.79   1735.70   1578.02   1681.58   1632.20
## 4 10700004     66.95     65.61     64.41     60.19     60.41     60.67
## 5 10700005    770.07    753.41    731.20    684.53    657.25    667.66
##   Gene symbol
## 1            
## 2            
## 3            
## 4            
## 5</code></pre>
<p>In preparation for the visualization steps below, let’s reset the probeset IDs to rownames.</p>
<div class="sourceCode" id="cb1055"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1055-1"><a href="gene-expression-omnibus.html#cb1055-1" tabindex="-1"></a><span class="fu">rownames</span>(geodata_genes) <span class="ot">=</span> geodata_genes<span class="sc">$</span>ID</span>
<span id="cb1055-2"><a href="gene-expression-omnibus.html#cb1055-2" tabindex="-1"></a></span>
<span id="cb1055-3"><a href="gene-expression-omnibus.html#cb1055-3" tabindex="-1"></a><span class="co"># Can then remove this column within the dataframe</span></span>
<span id="cb1055-4"><a href="gene-expression-omnibus.html#cb1055-4" tabindex="-1"></a>geodata_genes<span class="sc">$</span>ID <span class="ot">=</span> <span class="cn">NULL</span></span></code></pre></div>
<p>Finally let’s rearrange this dataset to include gene symbols as the first column, right after rownames (probeset IDs).</p>
<div class="sourceCode" id="cb1056"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1056-1"><a href="gene-expression-omnibus.html#cb1056-1" tabindex="-1"></a>geodata_genes <span class="ot">=</span> geodata_genes[,<span class="fu">c</span>(<span class="fu">ncol</span>(geodata_genes),<span class="dv">1</span><span class="sc">:</span>(<span class="fu">ncol</span>(geodata_genes)<span class="sc">-</span><span class="dv">1</span>))]</span>
<span id="cb1056-2"><a href="gene-expression-omnibus.html#cb1056-2" tabindex="-1"></a>geodata_genes[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>,]</span></code></pre></div>
<pre><code>##          Gene symbol Control_1 Control_2 Control_3 Exposed_1 Exposed_2
## 10700001               5786.60   5830.08   5637.34   5313.33   5557.04
## 10700002                192.92    206.86    220.83    183.12    177.16
## 10700003               1820.98   1795.79   1735.70   1578.02   1681.58
## 10700004                 66.95     65.61     64.41     60.19     60.41
## 10700005                770.07    753.41    731.20    684.53    657.25
##          Exposed_3
## 10700001   5469.90
## 10700002    198.64
## 10700003   1632.20
## 10700004     60.67
## 10700005    667.66</code></pre>
<div class="sourceCode" id="cb1058"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1058-1"><a href="gene-expression-omnibus.html#cb1058-1" tabindex="-1"></a><span class="fu">dim</span>(geodata_genes)</span></code></pre></div>
<pre><code>## [1] 29214     7</code></pre>
<p>Note that this dataset includes expression measures across <strong>29,214 probes, representing 14,019 unique genes</strong>.
For simplicity in the final exercises, let’s just filter for rows representing mapped genes.</p>
<div class="sourceCode" id="cb1060"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1060-1"><a href="gene-expression-omnibus.html#cb1060-1" tabindex="-1"></a>geodata_genes <span class="ot">=</span> geodata_genes[<span class="sc">!</span>(geodata_genes<span class="sc">$</span><span class="st">`</span><span class="at">Gene symbol</span><span class="st">`</span> <span class="sc">==</span> <span class="st">&quot;&quot;</span>), ]</span>
<span id="cb1060-2"><a href="gene-expression-omnibus.html#cb1060-2" tabindex="-1"></a><span class="fu">dim</span>(geodata_genes)</span></code></pre></div>
<pre><code>## [1] 16024     7</code></pre>
<p>Note that this dataset now includes 16,024 rows with mapped gene symbol identifiers.</p>
</div>
</div>
<div id="answer-to-environmental-health-question-1-20" class="section level3 hasAnchor">
<h3>Answer to Environmental Health Question 1<a href="gene-expression-omnibus.html#answer-to-environmental-health-question-1-20" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="question">
<p><i>With this, we can now answer <strong>Environmental Health Question 1</strong>:</i>
What kind of molecular identifiers are commonly used in microarray-based -omics technologies?</p>
</div>
<div class="answer">
<p><strong>Answer</strong>: Platform-specific probeset IDs.</p>
</div>
</div>
<div id="answer-to-environmental-health-question-2-21" class="section level3 hasAnchor">
<h3>Answer to Environmental Health Question 2<a href="gene-expression-omnibus.html#answer-to-environmental-health-question-2-21" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="question">
<p><i>We can also answer <strong>Environmental Health Question 2</strong>:</i>
How can we convert platform-specific molecular identifiers used in -omics study designs to gene-level information?</p>
</div>
<div class="answer">
<p><strong>Answer</strong>: We can merge platform-specific IDs with gene-level information using annotation files.</p>
</div>
<p><br></p>
</div>
</div>
<div id="visualizing-data" class="section level2 hasAnchor">
<h2>Visualizing Data<a href="gene-expression-omnibus.html#visualizing-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="visualizing-gene-expression-data-using-boxplots-and-heat-maps" class="section level3 hasAnchor">
<h3>Visualizing Gene Expression Data using Boxplots and Heat Maps<a href="gene-expression-omnibus.html#visualizing-gene-expression-data-using-boxplots-and-heat-maps" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>To visualize the -omics data, we can generate boxplots, heat maps, any many other types of visualizations. Here, we provide an example to plot a boxplot, which can be used to visualize the variability amongst samples. We also provide an example to plot a heat map, comparing unscaled vs scaled gene expression profiles. These visualizations can be useful to both simply visualize the data as well as identify patterns across samples or genes</p>
<div id="boxplot-visualizations" class="section level4 hasAnchor">
<h4>Boxplot visualizations<a href="gene-expression-omnibus.html#boxplot-visualizations" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>For this example, let’s simply use R’s built in boxplot() function.</p>
<p>We only want to use columns with our expression data (2 to 7), so let’s pull those columns when running the boxplot function.</p>
<div class="sourceCode" id="cb1062"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1062-1"><a href="gene-expression-omnibus.html#cb1062-1" tabindex="-1"></a><span class="fu">boxplot</span>(geodata_genes[,<span class="dv">2</span><span class="sc">:</span><span class="dv">7</span>])</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-770-1.png" width="480" style="display: block; margin: auto;" /></p>
<p>There seem to be a lot of variability within each sample’s range of expression levels, with many outliers. This makes sense given that we are analyzing the expression levels across the rat’s entire genome, where some genes won’t be expressed at all while others will be highly expressed due to biological and/or potential technical variability.</p>
<p>To show plots without outliers, we can simply use outline=F.</p>
<div class="sourceCode" id="cb1063"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1063-1"><a href="gene-expression-omnibus.html#cb1063-1" tabindex="-1"></a><span class="fu">boxplot</span>(geodata_genes[,<span class="dv">2</span><span class="sc">:</span><span class="dv">7</span>], <span class="at">outline=</span>F)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-771-1.png" width="480" style="display: block; margin: auto;" /></p>
</div>
<div id="heat-map-visualizations" class="section level4 hasAnchor">
<h4>Heat Map visualizations<a href="gene-expression-omnibus.html#heat-map-visualizations" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Heat maps are also useful when evaluating large datasets.</p>
<p>There are many different packages you can use to generate heat maps. Here, we use the <em>superheat</em> package.</p>
<p>It also takes awhile to plot all genes across the genome, so to save time for this training module, let’s randomly select 100 rows to plot.</p>
<div class="sourceCode" id="cb1064"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1064-1"><a href="gene-expression-omnibus.html#cb1064-1" tabindex="-1"></a><span class="co"># To ensure that the same subset of genes are selected each time</span></span>
<span id="cb1064-2"><a href="gene-expression-omnibus.html#cb1064-2" tabindex="-1"></a>set.seed <span class="ot">=</span> <span class="dv">101</span>                                     </span>
<span id="cb1064-3"><a href="gene-expression-omnibus.html#cb1064-3" tabindex="-1"></a></span>
<span id="cb1064-4"><a href="gene-expression-omnibus.html#cb1064-4" tabindex="-1"></a><span class="co"># Random selection of 100 rows</span></span>
<span id="cb1064-5"><a href="gene-expression-omnibus.html#cb1064-5" tabindex="-1"></a>row.sample <span class="ot">=</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(geodata_genes),<span class="dv">100</span>) </span>
<span id="cb1064-6"><a href="gene-expression-omnibus.html#cb1064-6" tabindex="-1"></a></span>
<span id="cb1064-7"><a href="gene-expression-omnibus.html#cb1064-7" tabindex="-1"></a><span class="co"># Heat map code</span></span>
<span id="cb1064-8"><a href="gene-expression-omnibus.html#cb1064-8" tabindex="-1"></a>superheat<span class="sc">::</span><span class="fu">superheat</span>(geodata_genes[row.sample,<span class="dv">2</span><span class="sc">:</span><span class="dv">7</span>], <span class="co"># Only want to plot non-id/gene symbol columns (2 to 7)</span></span>
<span id="cb1064-9"><a href="gene-expression-omnibus.html#cb1064-9" tabindex="-1"></a>                     <span class="at">pretty.order.rows =</span> <span class="cn">TRUE</span>,</span>
<span id="cb1064-10"><a href="gene-expression-omnibus.html#cb1064-10" tabindex="-1"></a>                     <span class="at">pretty.order.cols =</span> <span class="cn">TRUE</span>,</span>
<span id="cb1064-11"><a href="gene-expression-omnibus.html#cb1064-11" tabindex="-1"></a>                     <span class="at">col.dendrogram =</span> T,</span>
<span id="cb1064-12"><a href="gene-expression-omnibus.html#cb1064-12" tabindex="-1"></a>                     <span class="at">row.dendrogram =</span> T)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-772-1.png" width="864" style="display: block; margin: auto;" /></p>
<p>This produces a heat map with sample IDs along the x-axis and probeset IDs along the y-axis. Here, the values being displayed represent normalized expression values.</p>
<p>One way to improve our ability to distinguish differences between samples is to <strong>scale expression values</strong> across probes.</p>
<p><strong>Scaling data</strong></p>
<p>Z-score is a very common method of scaling that transforms data points to reflect the number of standard deviations they are from the overall mean. Z-score scaling data results in the overall transformation of a dataset to have an overall mean = 0 and standard deviation = 1.</p>
<p>Let’s see what happens when we scale this gene expression dataset by z-score across each probe. This can be easily done using the <code>scale()</code> function.</p>
<p>This specific <code>scale()</code> function works by centering and scaling across columns, but since we want to use it across probesets (organized as rows), we need to first transpose our dataset, then run the scale function.</p>
<div class="sourceCode" id="cb1065"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1065-1"><a href="gene-expression-omnibus.html#cb1065-1" tabindex="-1"></a>geodata_genes_scaled <span class="ot">=</span> <span class="fu">scale</span>(<span class="fu">t</span>(geodata_genes[,<span class="dv">2</span><span class="sc">:</span><span class="dv">7</span>]), <span class="at">center=</span>T, <span class="at">scale=</span>T)</span></code></pre></div>
<p>Now we can transpose it back to the original format (i.e., before it was transposed).</p>
<div class="sourceCode" id="cb1066"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1066-1"><a href="gene-expression-omnibus.html#cb1066-1" tabindex="-1"></a>geodata_genes_scaled <span class="ot">=</span> <span class="fu">t</span>(geodata_genes_scaled)</span></code></pre></div>
<p>And then view what the normalized and now scaled expression data look like for now a random subset of 100 probesets (representing genes).
<img src="_main_files/figure-html/unnamed-chunk-775-1.png" width="864" style="display: block; margin: auto;" /></p>
<p>With these data now scaled, we can more easily visualize patterns between samples.</p>
</div>
</div>
<div id="answer-to-environmental-health-question-3-14" class="section level3 hasAnchor">
<h3>Answer to Environmental Health Question 3<a href="gene-expression-omnibus.html#answer-to-environmental-health-question-3-14" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="question">
<p><em>We can also answer <strong>Environmental Health Question 3</strong></em>:
Why do we often scale gene expression signatures prior to heat map visualizations?</p>
</div>
<div class="answer">
<p><strong>Answer</strong>: To better visualize patterns in expression signatures between samples.</p>
</div>
<p><br>
Now, with these data nicely organized, we can next explore how statistics can help us find which genes show trends in expression associated with formaldehyde exposure.</p>
</div>
</div>
<div id="statistical-analyses" class="section level2 hasAnchor">
<h2>Statistical Analyses<a href="gene-expression-omnibus.html#statistical-analyses" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="statistical-analyses-to-identify-genes-altered-by-formaldehyde" class="section level3 hasAnchor">
<h3>Statistical Analyses to Identify Genes altered by Formaldehyde<a href="gene-expression-omnibus.html#statistical-analyses-to-identify-genes-altered-by-formaldehyde" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A simple way to identify differences between formaldehyde-exposed and unexposed samples is to use a t-test. Because there are so many tests being performed, one for each gene, it is also important to carry out multiple test corrections through a p-value adjustment method.</p>
<p>We need to run a t-test for each row of our dataset. This exercise demonstrates two different methods to run a t-test:</p>
<ul>
<li>Method 1: using a ‘for loop’</li>
<li>Method 2: using the apply function (more computationally efficient)</li>
</ul>
<div id="method-1-m1-for-loop" class="section level4 hasAnchor">
<h4>Method 1 (m1): ‘For Loop’<a href="gene-expression-omnibus.html#method-1-m1-for-loop" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Let’s first re-save the molecular probe IDs to a column within the dataframe, since we need those values in the loop function.</p>
<div class="sourceCode" id="cb1067"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1067-1"><a href="gene-expression-omnibus.html#cb1067-1" tabindex="-1"></a>geodata_genes<span class="sc">$</span>ID <span class="ot">=</span> <span class="fu">rownames</span>(geodata_genes)</span></code></pre></div>
<p>We also need to initially create an empty dataframe to eventually store p-values.</p>
<div class="sourceCode" id="cb1068"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1068-1"><a href="gene-expression-omnibus.html#cb1068-1" tabindex="-1"></a>pValue_m1 <span class="ot">=</span> <span class="fu">matrix</span>(<span class="dv">0</span>, <span class="at">nrow=</span><span class="fu">nrow</span>(geodata_genes), <span class="at">ncol=</span><span class="dv">3</span>)</span>
<span id="cb1068-2"><a href="gene-expression-omnibus.html#cb1068-2" tabindex="-1"></a><span class="fu">colnames</span>(pValue_m1) <span class="ot">=</span> <span class="fu">c</span>(<span class="st">&quot;ID&quot;</span>, <span class="st">&quot;pval&quot;</span>, <span class="st">&quot;padj&quot;</span>)</span>
<span id="cb1068-3"><a href="gene-expression-omnibus.html#cb1068-3" tabindex="-1"></a><span class="fu">head</span>(pValue_m1)</span></code></pre></div>
<pre><code>##      ID pval padj
## [1,]  0    0    0
## [2,]  0    0    0
## [3,]  0    0    0
## [4,]  0    0    0
## [5,]  0    0    0
## [6,]  0    0    0</code></pre>
<p>You can see the empty dataframe that was generated through this code.</p>
<p>Then we can loop through the entire dataset to acquire p-values from t-test statistics, comparing n=3 exposed vs n=3 unexposed samples.</p>
<div class="sourceCode" id="cb1070"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1070-1"><a href="gene-expression-omnibus.html#cb1070-1" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(geodata_genes)) {</span>
<span id="cb1070-2"><a href="gene-expression-omnibus.html#cb1070-2" tabindex="-1"></a>  </span>
<span id="cb1070-3"><a href="gene-expression-omnibus.html#cb1070-3" tabindex="-1"></a>  <span class="co">#Get the ID</span></span>
<span id="cb1070-4"><a href="gene-expression-omnibus.html#cb1070-4" tabindex="-1"></a>  ID.i <span class="ot">=</span> geodata_genes[i, <span class="st">&quot;ID&quot;</span>];</span>
<span id="cb1070-5"><a href="gene-expression-omnibus.html#cb1070-5" tabindex="-1"></a>  </span>
<span id="cb1070-6"><a href="gene-expression-omnibus.html#cb1070-6" tabindex="-1"></a>  <span class="co">#Run the t-test and get the p-value</span></span>
<span id="cb1070-7"><a href="gene-expression-omnibus.html#cb1070-7" tabindex="-1"></a>  pval.i <span class="ot">=</span> <span class="fu">t.test</span>(geodata_genes[i,exposedIDs], geodata_genes[i,unexposedIDs])<span class="sc">$</span>p.value;</span>
<span id="cb1070-8"><a href="gene-expression-omnibus.html#cb1070-8" tabindex="-1"></a>  </span>
<span id="cb1070-9"><a href="gene-expression-omnibus.html#cb1070-9" tabindex="-1"></a>  <span class="co">#Store the data in the empty dataframe</span></span>
<span id="cb1070-10"><a href="gene-expression-omnibus.html#cb1070-10" tabindex="-1"></a>  pValue_m1[i,<span class="st">&quot;ID&quot;</span>] <span class="ot">=</span> ID.i;</span>
<span id="cb1070-11"><a href="gene-expression-omnibus.html#cb1070-11" tabindex="-1"></a>  pValue_m1[i,<span class="st">&quot;pval&quot;</span>] <span class="ot">=</span> pval.i</span>
<span id="cb1070-12"><a href="gene-expression-omnibus.html#cb1070-12" tabindex="-1"></a>  </span>
<span id="cb1070-13"><a href="gene-expression-omnibus.html#cb1070-13" tabindex="-1"></a>}</span></code></pre></div>
<p>View the results:</p>
<div class="sourceCode" id="cb1071"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1071-1"><a href="gene-expression-omnibus.html#cb1071-1" tabindex="-1"></a><span class="co"># Note that we&#39;re not pulling the last column (padj) since we haven&#39;t calculated these yet</span></span>
<span id="cb1071-2"><a href="gene-expression-omnibus.html#cb1071-2" tabindex="-1"></a>pValue_m1[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>] </span></code></pre></div>
<pre><code>##      ID         pval                
## [1,] &quot;10903987&quot; &quot;0.0812802229304083&quot;
## [2,] &quot;10714794&quot; &quot;0.757311314118124&quot; 
## [3,] &quot;10858408&quot; &quot;0.390952310869689&quot; 
## [4,] &quot;10872252&quot; &quot;0.0548937136005506&quot;
## [5,] &quot;10905819&quot; &quot;0.173539535577791&quot;</code></pre>
</div>
<div id="method-2-m2-apply-function" class="section level4 hasAnchor">
<h4>Method 2 (m2): Apply Function<a href="gene-expression-omnibus.html#method-2-m2-apply-function" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>For the second method, we can use the <em>apply()</em> function to calculate resulting t-test p-values more efficiently labeled.</p>
<div class="sourceCode" id="cb1073"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1073-1"><a href="gene-expression-omnibus.html#cb1073-1" tabindex="-1"></a>pValue_m2 <span class="ot">=</span> <span class="fu">apply</span>(geodata_genes[,<span class="dv">2</span><span class="sc">:</span><span class="dv">7</span>], <span class="dv">1</span>, <span class="cf">function</span>(x) <span class="fu">t.test</span>(x[unexposedIDs],</span>
<span id="cb1073-2"><a href="gene-expression-omnibus.html#cb1073-2" tabindex="-1"></a>                                                              x[exposedIDs])<span class="sc">$</span>p.value)</span>
<span id="cb1073-3"><a href="gene-expression-omnibus.html#cb1073-3" tabindex="-1"></a><span class="fu">names</span>(pValue_m2) <span class="ot">=</span> geodata_genes[,<span class="st">&quot;ID&quot;</span>]</span></code></pre></div>
<p>We can convert the results into a dataframe to make it similar to m1 matrix we created above.</p>
<div class="sourceCode" id="cb1074"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1074-1"><a href="gene-expression-omnibus.html#cb1074-1" tabindex="-1"></a>pValue_m2  <span class="ot">=</span> <span class="fu">data.frame</span>(pValue_m2)</span>
<span id="cb1074-2"><a href="gene-expression-omnibus.html#cb1074-2" tabindex="-1"></a></span>
<span id="cb1074-3"><a href="gene-expression-omnibus.html#cb1074-3" tabindex="-1"></a><span class="co"># Now create an ID column</span></span>
<span id="cb1074-4"><a href="gene-expression-omnibus.html#cb1074-4" tabindex="-1"></a>pValue_m2<span class="sc">$</span>ID <span class="ot">=</span> <span class="fu">rownames</span>(pValue_m2)</span></code></pre></div>
<p>Then we can view at the two datasets to see they result in the same pvalues.</p>
<div class="sourceCode" id="cb1075"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1075-1"><a href="gene-expression-omnibus.html#cb1075-1" tabindex="-1"></a><span class="fu">head</span>(pValue_m1)</span></code></pre></div>
<pre><code>##      ID         pval                 padj
## [1,] &quot;10903987&quot; &quot;0.0812802229304083&quot; &quot;0&quot; 
## [2,] &quot;10714794&quot; &quot;0.757311314118124&quot;  &quot;0&quot; 
## [3,] &quot;10858408&quot; &quot;0.390952310869689&quot;  &quot;0&quot; 
## [4,] &quot;10872252&quot; &quot;0.0548937136005506&quot; &quot;0&quot; 
## [5,] &quot;10905819&quot; &quot;0.173539535577791&quot;  &quot;0&quot; 
## [6,] &quot;10907585&quot; &quot;0.215200167867295&quot;  &quot;0&quot;</code></pre>
<div class="sourceCode" id="cb1077"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1077-1"><a href="gene-expression-omnibus.html#cb1077-1" tabindex="-1"></a><span class="fu">head</span>(pValue_m2)</span></code></pre></div>
<pre><code>##           pValue_m2       ID
## 10903987 0.08128022 10903987
## 10714794 0.75731131 10714794
## 10858408 0.39095231 10858408
## 10872252 0.05489371 10872252
## 10905819 0.17353954 10905819
## 10907585 0.21520017 10907585</code></pre>
<p>We can see from these results that both methods (m1 and m2) generate the same statistical p-values.</p>
</div>
<div id="interpreting-results" class="section level4 hasAnchor">
<h4>Interpreting Results<a href="gene-expression-omnibus.html#interpreting-results" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Let’s again merge these data with the gene symbols to tell which genes are significant.</p>
<p>First, let’s convert to a dataframe and then merge as before, for one of the above methods as an example (m1).</p>
<div class="sourceCode" id="cb1079"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1079-1"><a href="gene-expression-omnibus.html#cb1079-1" tabindex="-1"></a>pValue_m1 <span class="ot">=</span> <span class="fu">data.frame</span>(pValue_m1)</span>
<span id="cb1079-2"><a href="gene-expression-omnibus.html#cb1079-2" tabindex="-1"></a>pValue_m1 <span class="ot">=</span> <span class="fu">merge</span>(pValue_m1, id.gene.table, <span class="at">by=</span><span class="st">&quot;ID&quot;</span>)</span></code></pre></div>
<p>We can also add a multiple test correction by applying a false discovery rate-adjusted p-value; here, using the Benjamini Hochberg (BH) method.</p>
<div class="sourceCode" id="cb1080"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1080-1"><a href="gene-expression-omnibus.html#cb1080-1" tabindex="-1"></a><span class="co"># Here fdr is an alias for B-H method</span></span>
<span id="cb1080-2"><a href="gene-expression-omnibus.html#cb1080-2" tabindex="-1"></a>pValue_m1[,<span class="st">&quot;padj&quot;</span>] <span class="ot">=</span> <span class="fu">p.adjust</span>(pValue_m1[,<span class="st">&quot;pval&quot;</span>], <span class="at">method=</span><span class="fu">c</span>(<span class="st">&quot;fdr&quot;</span>))</span></code></pre></div>
<p>Now, we can sort these statistical results by adjusted p-values.</p>
<div class="sourceCode" id="cb1081"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1081-1"><a href="gene-expression-omnibus.html#cb1081-1" tabindex="-1"></a>pValue_m1.sorted <span class="ot">=</span> pValue_m1[<span class="fu">order</span>(pValue_m1[,<span class="st">&#39;padj&#39;</span>]),]</span>
<span id="cb1081-2"><a href="gene-expression-omnibus.html#cb1081-2" tabindex="-1"></a><span class="fu">head</span>(pValue_m1.sorted)</span></code></pre></div>
<pre><code>##            ID                 pval       padj Gene symbol
## 9143 10837582 4.57288413593085e-07 0.00732759      Olr633
## 5640 10783648 1.93688668590855e-06 0.01551834      Slc7a8
## 8    10701699   0.0166773380386967 0.13089115       Lrp11
## 17   10701817   0.0131845685452954 0.13089115       Fuca2
## 19   10701830  0.00586885826460337 0.13089115      Hivep2
## 23   10701880  0.00749149990409956 0.13089115       Reps1</code></pre>
<p>Pulling just the significant genes using an adjusted p-value threshold of 0.05.</p>
<div class="sourceCode" id="cb1083"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1083-1"><a href="gene-expression-omnibus.html#cb1083-1" tabindex="-1"></a>adj.pval.sig <span class="ot">=</span> pValue_m1[<span class="fu">which</span>(pValue_m1[,<span class="st">&#39;padj&#39;</span>] <span class="sc">&lt;</span> .<span class="dv">05</span>),]</span>
<span id="cb1083-2"><a href="gene-expression-omnibus.html#cb1083-2" tabindex="-1"></a></span>
<span id="cb1083-3"><a href="gene-expression-omnibus.html#cb1083-3" tabindex="-1"></a><span class="co"># Viewing these genes</span></span>
<span id="cb1083-4"><a href="gene-expression-omnibus.html#cb1083-4" tabindex="-1"></a>adj.pval.sig       </span></code></pre></div>
<pre><code>##            ID                 pval       padj Gene symbol
## 5640 10783648 1.93688668590855e-06 0.01551834      Slc7a8
## 9143 10837582 4.57288413593085e-07 0.00732759      Olr633</code></pre>
</div>
</div>
<div id="answer-to-environmental-health-question-4-10" class="section level3 hasAnchor">
<h3>Answer to Environmental Health Question 4<a href="gene-expression-omnibus.html#answer-to-environmental-health-question-4-10" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="question">
<p><em>With this, we can answer <strong>Environmental Health Question 4</strong></em>:</i>
What genes are altered in expression by formaldehyde inhalation exposure?</p>
</div>
<div class="answer">
<p><strong>Answer</strong>: Olr633 and Slc7a8.</p>
</div>
<p>Finally, let’s plot these using a mini heat map.
Note that we can use probesetIDs, then gene symbols, in rownames to have them show in heat map labels.
<img src="_main_files/figure-html/unnamed-chunk-787-1.png" width="768" style="display: block; margin: auto;" /></p>
<p>Note that this statistical filter is pretty strict when comparing only n=3 vs n=3 biological replicates. If we loosen the statistical criteria to p-value &lt; 0.05, this is what we can find:</p>
<div class="sourceCode" id="cb1085"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1085-1"><a href="gene-expression-omnibus.html#cb1085-1" tabindex="-1"></a>pval.sig <span class="ot">=</span> pValue_m1[<span class="fu">which</span>(pValue_m1[,<span class="st">&#39;pval&#39;</span>] <span class="sc">&lt;</span> .<span class="dv">05</span>),]</span>
<span id="cb1085-2"><a href="gene-expression-omnibus.html#cb1085-2" tabindex="-1"></a><span class="fu">nrow</span>(pval.sig)</span></code></pre></div>
<pre><code>## [1] 5327</code></pre>
<p>5327 genes with significantly altered expression!</p>
<p>Note that other filters are commonly applied to further focus these lists (e.g., background and fold change filters) prior to statistical evaluation, which can impact the final results. See <a href="https://pubmed.ncbi.nlm.nih.gov/24304932/">Rager et al. 2013</a> for further statistical approaches and visualizations.</p>
<p><br></p>
</div>
<div id="answer-to-environmental-health-question-5-8" class="section level3 hasAnchor">
<h3>Answer to Environmental Health Question 5<a href="gene-expression-omnibus.html#answer-to-environmental-health-question-5-8" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="question">
<p><em>With this, we can answer <strong>Environmental Health Question 5</strong></em>:
What are the potential biological consequences of these gene-level perturbations?</p>
</div>
<div class="answer">
<p><strong>Answer</strong>: Olr633 stands for ‘olfactory receptor 633’. Olr633 is up-regulated in expression, meaning that formaldehyde inhalation exposure has a smell that resulted in ‘activated’ olfactory receptors in the nose of these exposed rats. Slc7a8 stands for ‘solute carrier family 7 member 8’. Slc7a8 is down-regulated in expression, and it plays a role in many biological processes, that when altered, can lead to changes in cellular homeostasis and disease.</p>
</div>
<p><br></p>
</div>
</div>
<div id="concluding-remarks-31" class="section level2 hasAnchor">
<h2>Concluding Remarks<a href="gene-expression-omnibus.html#concluding-remarks-31" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In conclusion, this training module provides an overview of pulling, organizing, visualizing, and analyzing -omics data from the online repository, Gene Expression Omnibus (GEO). Trainees are guided through the overall organization of an example high dimensional dataset, focusing on transcriptomic responses in the nasal epithelium of rats exposed to formaldehyde. Data are visualized and then analyzed using standard two-group comparisons. Findings are interpreted for biological relevance, yielding insight into the effects resulting from formaldehyde exposure.</p>
<p>For additional case studies that leverage GEO, see the following publications that also address environmental health questions from our research group:</p>
<ul>
<li><p>Rager JE, Fry RC. The aryl hydrocarbon receptor pathway: a key component of the microRNA-mediated AML signalisome. Int J Environ Res Public Health. 2012 May;9(5):1939-53. doi: 10.3390/ijerph9051939. Epub 2012 May 18. PMID: 22754483; PMCID: <a href="https://pubmed.ncbi.nlm.nih.gov/22754483/">PMC3386597</a>.</p></li>
<li><p>Rager JE, Suh M, Chappell GA, Thompson CM, Proctor DM. Review of transcriptomic responses to hexavalent chromium exposure in lung cells supports a role of epigenetic mediators in carcinogenesis. Toxicol Lett. 2019 May 1;305:40-50. PMID: <a href="https://pubmed.ncbi.nlm.nih.gov/30690063/">30690063</a>.</p></li>
</ul>
<p><label class="tykfont">
Test Your Knowledge
</label></p>
<div class="tyk">
<p>Using the same dataset that was used in this module, available from the <a href="https://github.com/UNCSRP/TAME2">UNC-SRP TAME2 GitHub website</a>:
1. Load the downloaded GEO dataset into R using the packages and functions mentioned in this tutorial.
2. Filter the data to just those with “cell type” of “Circulating white blood cells”.
3. Report the means of the first 5 rows of the gene expression data (10700001, 10700002, 10700003, 10700004, 10700005), across all samples.</p>
</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="comparative-toxicogenomics-database.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="comptox-dashboard-data-through-apis.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf", "_main.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
