<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Intoduction to Statistical Tests | TAME 2.0</title>
  <meta name="description" content="This is an example of how the TAME 2.0 website will look, I hope!" />
  <meta name="generator" content="bookdown 0.37 and GitBook 2.6.7" />

  <meta property="og:title" content="Intoduction to Statistical Tests | TAME 2.0" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This is an example of how the TAME 2.0 website will look, I hope!" />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Intoduction to Statistical Tests | TAME 2.0" />
  
  <meta name="twitter:description" content="This is an example of how the TAME 2.0 website will look, I hope!" />
  

<meta name="author" content="Rager Lab" />


<meta name="date" content="2024-06-24" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="normality-tests-and-data-transformations.html"/>
<link rel="next" href="overview-of-experimental-design-and-example-data.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<link href="libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet" />
<script src="libs/datatables-binding-0.32/datatables.js"></script>
<link href="libs/dt-core-1.13.6/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="libs/dt-core-1.13.6/css/jquery.dataTables.extra.css" rel="stylesheet" />
<script src="libs/dt-core-1.13.6/js/jquery.dataTables.min.js"></script>
<link href="libs/crosstalk-1.2.1/css/crosstalk.min.css" rel="stylesheet" />
<script src="libs/crosstalk-1.2.1/js/crosstalk.min.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="toc-logo"><a href="./"><img src="images/Data Training Icon for Top Left Bookdown_v2.png"><br></a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="part"><span><b>Chapter 1 Introductory <br>Data Science</b></span></li>
<li class="chapter" data-level="" data-path="fair-data-management-practices.html"><a href="fair-data-management-practices.html"><i class="fa fa-check"></i>FAIR Data Management Practices</a>
<ul>
<li class="chapter" data-level="" data-path="fair-data-management-practices.html"><a href="fair-data-management-practices.html#introduction-to-training-module"><i class="fa fa-check"></i>Introduction to Training Module</a></li>
<li class="chapter" data-level="" data-path="fair-data-management-practices.html"><a href="fair-data-management-practices.html#introduction-to-fair"><i class="fa fa-check"></i>Introduction to FAIR</a></li>
<li class="chapter" data-level="" data-path="fair-data-management-practices.html"><a href="fair-data-management-practices.html#breaking-down-fair-letter-by-letter"><i class="fa fa-check"></i>Breaking Down FAIR, Letter-by-Letter</a></li>
<li class="chapter" data-level="" data-path="fair-data-management-practices.html"><a href="fair-data-management-practices.html#what-does-this-mean-for-you"><i class="fa fa-check"></i>What Does This Mean for You?</a></li>
<li class="chapter" data-level="" data-path="fair-data-management-practices.html"><a href="fair-data-management-practices.html#data-repositories-for-sharing-of-data"><i class="fa fa-check"></i>Data Repositories for Sharing of Data</a></li>
<li class="chapter" data-level="" data-path="fair-data-management-practices.html"><a href="fair-data-management-practices.html#recent-shifts-in-regulatory-policies-for-data-sharing"><i class="fa fa-check"></i>Recent Shifts in Regulatory Policies for Data Sharing</a></li>
<li class="chapter" data-level="" data-path="fair-data-management-practices.html"><a href="fair-data-management-practices.html#additional-training-resources-on-fair"><i class="fa fa-check"></i>Additional Training Resources on FAIR</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="data-sharing-through-online-repositories.html"><a href="data-sharing-through-online-repositories.html"><i class="fa fa-check"></i>Data Sharing through Online Repositories</a>
<ul>
<li class="chapter" data-level="" data-path="data-sharing-through-online-repositories.html"><a href="data-sharing-through-online-repositories.html#an-overview-and-example-with-the-dataverse-repository"><i class="fa fa-check"></i>An Overview and Example with the Dataverse Repository</a></li>
<li class="chapter" data-level="" data-path="data-sharing-through-online-repositories.html"><a href="data-sharing-through-online-repositories.html#introduction-to-training-module-1"><i class="fa fa-check"></i>Introduction to Training Module</a></li>
<li class="chapter" data-level="" data-path="data-sharing-through-online-repositories.html"><a href="data-sharing-through-online-repositories.html#data-repositories"><i class="fa fa-check"></i>Data Repositories</a></li>
<li class="chapter" data-level="" data-path="data-sharing-through-online-repositories.html"><a href="data-sharing-through-online-repositories.html#the-dataverse-project"><i class="fa fa-check"></i>The Dataverse Project</a></li>
<li class="chapter" data-level="" data-path="data-sharing-through-online-repositories.html"><a href="data-sharing-through-online-repositories.html#what-is-a-dataverse"><i class="fa fa-check"></i>What is a Dataverse?</a></li>
<li class="chapter" data-level="" data-path="data-sharing-through-online-repositories.html"><a href="data-sharing-through-online-repositories.html#metadata"><i class="fa fa-check"></i>Metadata</a></li>
<li class="chapter" data-level="" data-path="data-sharing-through-online-repositories.html"><a href="data-sharing-through-online-repositories.html#creating-a-dataverse"><i class="fa fa-check"></i>Creating a Dataverse</a></li>
<li class="chapter" data-level="" data-path="data-sharing-through-online-repositories.html"><a href="data-sharing-through-online-repositories.html#creating-a-dataset"><i class="fa fa-check"></i>Creating a Dataset</a></li>
<li class="chapter" data-level="" data-path="data-sharing-through-online-repositories.html"><a href="data-sharing-through-online-repositories.html#concluding-remarks-1"><i class="fa fa-check"></i>Concluding Remarks</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="file-management-using-github.html"><a href="file-management-using-github.html"><i class="fa fa-check"></i>File Management using Github</a>
<ul>
<li class="chapter" data-level="" data-path="file-management-using-github.html"><a href="file-management-using-github.html#introduction-to-training-module-2"><i class="fa fa-check"></i>Introduction to Training Module</a></li>
<li class="chapter" data-level="" data-path="file-management-using-github.html"><a href="file-management-using-github.html#creating-an-account"><i class="fa fa-check"></i>Creating an Account</a></li>
<li class="chapter" data-level="" data-path="file-management-using-github.html"><a href="file-management-using-github.html#creating-a-repository"><i class="fa fa-check"></i>Creating a Repository</a></li>
<li class="chapter" data-level="" data-path="file-management-using-github.html"><a href="file-management-using-github.html#uploading-code"><i class="fa fa-check"></i>Uploading Code</a></li>
<li class="chapter" data-level="" data-path="file-management-using-github.html"><a href="file-management-using-github.html#adding-subfolders-in-a-repository"><i class="fa fa-check"></i>Adding Subfolders in a Repository</a></li>
<li class="chapter" data-level="" data-path="file-management-using-github.html"><a href="file-management-using-github.html#updating-code"><i class="fa fa-check"></i>Updating Code</a></li>
<li class="chapter" data-level="" data-path="file-management-using-github.html"><a href="file-management-using-github.html#updating-repository-titles-and-structure-to-support-a-manuscript"><i class="fa fa-check"></i>Updating Repository Titles and Structure to Support a Manuscript</a></li>
<li class="chapter" data-level="" data-path="file-management-using-github.html"><a href="file-management-using-github.html#tracking-code-changes-using-github-branches"><i class="fa fa-check"></i>Tracking Code Changes using Github Branches</a></li>
<li class="chapter" data-level="" data-path="file-management-using-github.html"><a href="file-management-using-github.html#concluding-remarks-2"><i class="fa fa-check"></i>Concluding Remarks</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="data-wrangling-in-excel.html"><a href="data-wrangling-in-excel.html"><i class="fa fa-check"></i>Data Wrangling in Excel</a>
<ul>
<li class="chapter" data-level="" data-path="data-wrangling-in-excel.html"><a href="data-wrangling-in-excel.html#introduction-to-training-module-3"><i class="fa fa-check"></i>Introduction to Training Module</a></li>
<li class="chapter" data-level="" data-path="data-wrangling-in-excel.html"><a href="data-wrangling-in-excel.html#save-a-copy-of-the-soon-to-be-organized-and-cleaned-dataset-as-a-new-file"><i class="fa fa-check"></i>Save a Copy of the Soon-To-Be Organized and Cleaned Dataset as a New File</a></li>
<li class="chapter" data-level="" data-path="data-wrangling-in-excel.html"><a href="data-wrangling-in-excel.html#remove-extraneous-white-space"><i class="fa fa-check"></i>Remove Extraneous White Space</a></li>
<li class="chapter" data-level="" data-path="data-wrangling-in-excel.html"><a href="data-wrangling-in-excel.html#replace-missing-data-with-na"><i class="fa fa-check"></i>Replace Missing Data with “NA”</a></li>
<li class="chapter" data-level="" data-path="data-wrangling-in-excel.html"><a href="data-wrangling-in-excel.html#create-a-metadata-tab"><i class="fa fa-check"></i>Create a Metadata Tab</a></li>
<li class="chapter" data-level="" data-path="data-wrangling-in-excel.html"><a href="data-wrangling-in-excel.html#abbreviate-and-capitalize-categorical-data"><i class="fa fa-check"></i>Abbreviate and Capitalize Categorical Data</a></li>
<li class="chapter" data-level="" data-path="data-wrangling-in-excel.html"><a href="data-wrangling-in-excel.html#alphabetize-sort-the-data-by-the-categorical-variable-of-interest"><i class="fa fa-check"></i>Alphabetize (Sort) the Data by the Categorical Variable of Interest</a></li>
<li class="chapter" data-level="" data-path="data-wrangling-in-excel.html"><a href="data-wrangling-in-excel.html#create-a-new-subject-number-column"><i class="fa fa-check"></i>Create a New Subject Number Column</a></li>
<li class="chapter" data-level="" data-path="data-wrangling-in-excel.html"><a href="data-wrangling-in-excel.html#remove-special-symbols-and-dashes"><i class="fa fa-check"></i>Remove Special Symbols and Dashes</a></li>
<li class="chapter" data-level="" data-path="data-wrangling-in-excel.html"><a href="data-wrangling-in-excel.html#bold-all-column-names-and-center-all-data"><i class="fa fa-check"></i>Bold all Column Names and Center all Data</a></li>
<li class="chapter" data-level="" data-path="data-wrangling-in-excel.html"><a href="data-wrangling-in-excel.html#create-a-subject-identifier-column"><i class="fa fa-check"></i>Create a Subject Identifier Column</a></li>
<li class="chapter" data-level="" data-path="data-wrangling-in-excel.html"><a href="data-wrangling-in-excel.html#separate-subject-demographic-data-from-experimental-measurements"><i class="fa fa-check"></i>Separate Subject Demographic Data from Experimental Measurements</a></li>
<li class="chapter" data-level="" data-path="data-wrangling-in-excel.html"><a href="data-wrangling-in-excel.html#convert-data-from-wide-to-long-format"><i class="fa fa-check"></i>Convert Data from Wide to Long Format</a></li>
<li class="chapter" data-level="" data-path="data-wrangling-in-excel.html"><a href="data-wrangling-in-excel.html#pivoting-data-from-a-wide-to-long-format"><i class="fa fa-check"></i>Pivoting Data from a Wide to Long Format</a></li>
<li class="chapter" data-level="" data-path="data-wrangling-in-excel.html"><a href="data-wrangling-in-excel.html#generating-summary-level-statistics-with-pivot-tables"><i class="fa fa-check"></i>Generating Summary-Level Statistics with Pivot Tables</a></li>
<li class="chapter" data-level="" data-path="data-wrangling-in-excel.html"><a href="data-wrangling-in-excel.html#excel-vs.-r-which-should-you-use"><i class="fa fa-check"></i>Excel vs. R: Which Should You Use?</a></li>
<li class="chapter" data-level="" data-path="data-wrangling-in-excel.html"><a href="data-wrangling-in-excel.html#concluding-remarks-3"><i class="fa fa-check"></i>Concluding Remarks</a></li>
</ul></li>
<li class="part"><span><b>Chapter 2 Coding in R</b></span></li>
<li class="chapter" data-level="" data-path="downloading-and-programming-in-r.html"><a href="downloading-and-programming-in-r.html"><i class="fa fa-check"></i>Downloading and Programming in R</a>
<ul>
<li class="chapter" data-level="" data-path="downloading-and-programming-in-r.html"><a href="downloading-and-programming-in-r.html#introduction-to-training-module-4"><i class="fa fa-check"></i>Introduction to Training Module</a></li>
<li class="chapter" data-level="" data-path="downloading-and-programming-in-r.html"><a href="downloading-and-programming-in-r.html#general-introduction-and-installation-of-r-and-rstudio"><i class="fa fa-check"></i>General Introduction and Installation of R and RStudio</a></li>
<li class="chapter" data-level="" data-path="downloading-and-programming-in-r.html"><a href="downloading-and-programming-in-r.html#introduction-to-r-packages"><i class="fa fa-check"></i>Introduction to R Packages</a></li>
<li class="chapter" data-level="" data-path="downloading-and-programming-in-r.html"><a href="downloading-and-programming-in-r.html#scripting-basics"><i class="fa fa-check"></i>Scripting Basics</a></li>
<li class="chapter" data-level="" data-path="downloading-and-programming-in-r.html"><a href="downloading-and-programming-in-r.html#code-troubleshooting"><i class="fa fa-check"></i>Code Troubleshooting</a></li>
<li class="chapter" data-level="" data-path="downloading-and-programming-in-r.html"><a href="downloading-and-programming-in-r.html#concluding-remarks-4"><i class="fa fa-check"></i>Concluding Remarks</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="coding-best-practices.html"><a href="coding-best-practices.html"><i class="fa fa-check"></i>Coding “Best” Practices</a>
<ul>
<li class="chapter" data-level="" data-path="coding-best-practices.html"><a href="coding-best-practices.html#introduction-to-training-module-5"><i class="fa fa-check"></i>Introduction to Training Module</a></li>
<li class="chapter" data-level="" data-path="coding-best-practices.html"><a href="coding-best-practices.html#scripting-file-types"><i class="fa fa-check"></i>Scripting File Types</a></li>
<li class="chapter" data-level="" data-path="coding-best-practices.html"><a href="coding-best-practices.html#script-headers-and-annotation"><i class="fa fa-check"></i>Script Headers and Annotation</a></li>
<li class="chapter" data-level="" data-path="coding-best-practices.html"><a href="coding-best-practices.html#coding-style"><i class="fa fa-check"></i>Coding Style</a></li>
<li class="chapter" data-level="" data-path="coding-best-practices.html"><a href="coding-best-practices.html#script-organization"><i class="fa fa-check"></i>Script Organization</a></li>
<li class="chapter" data-level="" data-path="coding-best-practices.html"><a href="coding-best-practices.html#concluding-remarks-5"><i class="fa fa-check"></i>Concluding Remarks</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="data-manipulation-and-reshaping.html"><a href="data-manipulation-and-reshaping.html"><i class="fa fa-check"></i>Data Manipulation and Reshaping</a>
<ul>
<li class="chapter" data-level="" data-path="data-manipulation-and-reshaping.html"><a href="data-manipulation-and-reshaping.html#introduction-to-training-module-6"><i class="fa fa-check"></i>Introduction to Training Module</a></li>
<li class="chapter" data-level="" data-path="data-manipulation-and-reshaping.html"><a href="data-manipulation-and-reshaping.html#data-manipulation-using-base-r"><i class="fa fa-check"></i>Data Manipulation Using Base R</a></li>
<li class="chapter" data-level="" data-path="data-manipulation-and-reshaping.html"><a href="data-manipulation-and-reshaping.html#introduction-to-tidyverse"><i class="fa fa-check"></i>Introduction to Tidyverse</a></li>
<li class="chapter" data-level="" data-path="data-manipulation-and-reshaping.html"><a href="data-manipulation-and-reshaping.html#concluding-remarks-6"><i class="fa fa-check"></i>Concluding Remarks</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="improving-coding-efficiencies.html"><a href="improving-coding-efficiencies.html"><i class="fa fa-check"></i>Improving Coding Efficiencies</a>
<ul>
<li class="chapter" data-level="" data-path="improving-coding-efficiencies.html"><a href="improving-coding-efficiencies.html#introduction-to-training-module-7"><i class="fa fa-check"></i>Introduction to Training Module</a></li>
<li class="chapter" data-level="" data-path="improving-coding-efficiencies.html"><a href="improving-coding-efficiencies.html#loops"><i class="fa fa-check"></i>Loops</a></li>
<li class="chapter" data-level="" data-path="improving-coding-efficiencies.html"><a href="improving-coding-efficiencies.html#functions"><i class="fa fa-check"></i>Functions</a></li>
<li class="chapter" data-level="" data-path="improving-coding-efficiencies.html"><a href="improving-coding-efficiencies.html#list-operations"><i class="fa fa-check"></i>List operations</a></li>
<li class="chapter" data-level="" data-path="improving-coding-efficiencies.html"><a href="improving-coding-efficiencies.html#concluding-remarks-7"><i class="fa fa-check"></i>Concluding Remarks</a></li>
<li class="chapter" data-level="" data-path="improving-coding-efficiencies.html"><a href="improving-coding-efficiencies.html#additional-resources-2"><i class="fa fa-check"></i>Additional Resources</a></li>
</ul></li>
<li class="part"><span><b>Chapter 3 Basics of <br>Data Analysis and Visualizations</b></span></li>
<li class="chapter" data-level="" data-path="data-visualizations.html"><a href="data-visualizations.html"><i class="fa fa-check"></i>Data Visualizations</a>
<ul>
<li class="chapter" data-level="" data-path="data-visualizations.html"><a href="data-visualizations.html#introduction-to-data-visualizations"><i class="fa fa-check"></i>Introduction to Data Visualizations</a></li>
<li class="chapter" data-level="" data-path="data-visualizations.html"><a href="data-visualizations.html#introduction-to-training-module-8"><i class="fa fa-check"></i>Introduction to Training Module</a></li>
<li class="chapter" data-level="" data-path="data-visualizations.html"><a href="data-visualizations.html#density-plot-visualization"><i class="fa fa-check"></i>Density Plot Visualization</a></li>
<li class="chapter" data-level="" data-path="data-visualizations.html"><a href="data-visualizations.html#boxplot-visualization"><i class="fa fa-check"></i>Boxplot Visualization</a></li>
<li class="chapter" data-level="" data-path="data-visualizations.html"><a href="data-visualizations.html#correlation-visualizations"><i class="fa fa-check"></i>Correlation Visualizations</a></li>
<li class="chapter" data-level="" data-path="data-visualizations.html"><a href="data-visualizations.html#heatmap-visualization"><i class="fa fa-check"></i>Heatmap Visualization</a></li>
<li class="chapter" data-level="" data-path="data-visualizations.html"><a href="data-visualizations.html#concluding-remarks-8"><i class="fa fa-check"></i>Concluding Remarks</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="improving-data-visualizations.html"><a href="improving-data-visualizations.html"><i class="fa fa-check"></i>Improving Data Visualizations</a>
<ul>
<li class="chapter" data-level="" data-path="improving-data-visualizations.html"><a href="improving-data-visualizations.html#introduction-to-data-visulization-conventions"><i class="fa fa-check"></i>Introduction to Data Visulization Conventions</a></li>
<li class="chapter" data-level="" data-path="improving-data-visualizations.html"><a href="improving-data-visualizations.html#introduction-to-training-module-9"><i class="fa fa-check"></i>Introduction to Training Module</a></li>
<li class="chapter" data-level="" data-path="improving-data-visualizations.html"><a href="improving-data-visualizations.html#creating-an-improved-boxplot-visualization"><i class="fa fa-check"></i>Creating an Improved Boxplot Visualization</a></li>
<li class="chapter" data-level="" data-path="improving-data-visualizations.html"><a href="improving-data-visualizations.html#creating-an-improved-heatmap-visualization"><i class="fa fa-check"></i>Creating an Improved Heatmap Visualization</a></li>
<li class="chapter" data-level="" data-path="improving-data-visualizations.html"><a href="improving-data-visualizations.html#creating-multi-plot-figures"><i class="fa fa-check"></i>Creating Multi-Plot Figures</a></li>
<li class="chapter" data-level="" data-path="improving-data-visualizations.html"><a href="improving-data-visualizations.html#concluding-remarks-9"><i class="fa fa-check"></i>Concluding Remarks</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="normality-tests-and-data-transformations.html"><a href="normality-tests-and-data-transformations.html"><i class="fa fa-check"></i>Normality Tests and Data Transformations</a>
<ul>
<li class="chapter" data-level="" data-path="normality-tests-and-data-transformations.html"><a href="normality-tests-and-data-transformations.html#introduction-to-training-module-10"><i class="fa fa-check"></i>Introduction to Training Module</a></li>
<li class="chapter" data-level="" data-path="normality-tests-and-data-transformations.html"><a href="normality-tests-and-data-transformations.html#what-is-a-normal-distribution"><i class="fa fa-check"></i>What is a Normal Distribution?</a></li>
<li class="chapter" data-level="" data-path="normality-tests-and-data-transformations.html"><a href="normality-tests-and-data-transformations.html#qualitative-assessment-of-normality"><i class="fa fa-check"></i>Qualitative Assessment of Normality</a></li>
<li class="chapter" data-level="" data-path="normality-tests-and-data-transformations.html"><a href="normality-tests-and-data-transformations.html#quantitative-normality-assessment"><i class="fa fa-check"></i>Quantitative Normality Assessment</a></li>
<li class="chapter" data-level="" data-path="normality-tests-and-data-transformations.html"><a href="normality-tests-and-data-transformations.html#data-transformation"><i class="fa fa-check"></i>Data Transformation</a></li>
<li class="chapter" data-level="" data-path="normality-tests-and-data-transformations.html"><a href="normality-tests-and-data-transformations.html#additional-considerations-regarding-normality"><i class="fa fa-check"></i>Additional Considerations Regarding Normality</a></li>
<li class="chapter" data-level="" data-path="normality-tests-and-data-transformations.html"><a href="normality-tests-and-data-transformations.html#concluding-remarks-10"><i class="fa fa-check"></i>Concluding Remarks</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="intoduction-to-statistical-tests.html"><a href="intoduction-to-statistical-tests.html"><i class="fa fa-check"></i>Intoduction to Statistical Tests</a>
<ul>
<li class="chapter" data-level="" data-path="intoduction-to-statistical-tests.html"><a href="intoduction-to-statistical-tests.html#introduction-to-training-module-11"><i class="fa fa-check"></i>Introduction to Training Module</a></li>
<li class="chapter" data-level="" data-path="intoduction-to-statistical-tests.html"><a href="intoduction-to-statistical-tests.html#assessing-normality-homogeneity-of-variance"><i class="fa fa-check"></i>Assessing Normality &amp; Homogeneity of Variance</a></li>
<li class="chapter" data-level="" data-path="intoduction-to-statistical-tests.html"><a href="intoduction-to-statistical-tests.html#two-group-visualizations-and-statistical-comparisons-using-the-t-test"><i class="fa fa-check"></i>Two-Group Visualizations and Statistical Comparisons using the T-Test</a></li>
<li class="chapter" data-level="" data-path="intoduction-to-statistical-tests.html"><a href="intoduction-to-statistical-tests.html#three-group-visualizations-and-statistical-comparisons-using-an-anova"><i class="fa fa-check"></i>Three-Group Visualizations and Statistical Comparisons using an ANOVA</a></li>
<li class="chapter" data-level="" data-path="intoduction-to-statistical-tests.html"><a href="intoduction-to-statistical-tests.html#regression-modeling-and-visualization-linear-and-logistic-regressions"><i class="fa fa-check"></i>Regression Modeling and Visualization: Linear and Logistic Regressions</a></li>
<li class="chapter" data-level="" data-path="intoduction-to-statistical-tests.html"><a href="intoduction-to-statistical-tests.html#statistical-evaluations-of-categorical-data-using-the-chi-squared-test-and-fishers-exact-test"><i class="fa fa-check"></i>Statistical Evaluations of Categorical Data using the Chi-Squared Test and Fisher’s Exact Test</a></li>
<li class="chapter" data-level="" data-path="intoduction-to-statistical-tests.html"><a href="intoduction-to-statistical-tests.html#concluding-remarks-11"><i class="fa fa-check"></i>Concluding Remarks</a></li>
</ul></li>
<li class="part"><span><b>Chapter 4 Converting Wet Lab Data into Dry Lab Analyses</b></span></li>
<li class="chapter" data-level="" data-path="overview-of-experimental-design-and-example-data.html"><a href="overview-of-experimental-design-and-example-data.html"><i class="fa fa-check"></i>Overview of Experimental Design and Example Data</a>
<ul>
<li class="chapter" data-level="" data-path="overview-of-experimental-design-and-example-data.html"><a href="overview-of-experimental-design-and-example-data.html#introduction-to-training-module-12"><i class="fa fa-check"></i>Introduction to Training Module</a></li>
<li class="chapter" data-level="" data-path="overview-of-experimental-design-and-example-data.html"><a href="overview-of-experimental-design-and-example-data.html#replicates"><i class="fa fa-check"></i>Replicates</a></li>
<li class="chapter" data-level="" data-path="overview-of-experimental-design-and-example-data.html"><a href="overview-of-experimental-design-and-example-data.html#orientation-to-example-data-for-chapter-4"><i class="fa fa-check"></i>Orientation to Example Data for Chapter 4</a></li>
<li class="chapter" data-level="" data-path="overview-of-experimental-design-and-example-data.html"><a href="overview-of-experimental-design-and-example-data.html#concluding-remarks-12"><i class="fa fa-check"></i>Concluding Remarks</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="data-import-processing-and-summary-statistics.html"><a href="data-import-processing-and-summary-statistics.html"><i class="fa fa-check"></i>Data Import, Processing, and Summary Statistics</a>
<ul>
<li class="chapter" data-level="" data-path="data-import-processing-and-summary-statistics.html"><a href="data-import-processing-and-summary-statistics.html#introduction-to-training-module-13"><i class="fa fa-check"></i>Introduction to Training Module</a></li>
<li class="chapter" data-level="" data-path="data-import-processing-and-summary-statistics.html"><a href="data-import-processing-and-summary-statistics.html#data-import"><i class="fa fa-check"></i>Data Import</a></li>
<li class="chapter" data-level="" data-path="data-import-processing-and-summary-statistics.html"><a href="data-import-processing-and-summary-statistics.html#handling-missing-values"><i class="fa fa-check"></i>Handling Missing Values</a></li>
<li class="chapter" data-level="" data-path="data-import-processing-and-summary-statistics.html"><a href="data-import-processing-and-summary-statistics.html#averaging-replicates"><i class="fa fa-check"></i>Averaging Replicates</a></li>
<li class="chapter" data-level="" data-path="data-import-processing-and-summary-statistics.html"><a href="data-import-processing-and-summary-statistics.html#descriptive-statistics"><i class="fa fa-check"></i>Descriptive Statistics</a></li>
<li class="chapter" data-level="" data-path="data-import-processing-and-summary-statistics.html"><a href="data-import-processing-and-summary-statistics.html#normality-assessment-and-data-transformation"><i class="fa fa-check"></i>Normality Assessment and Data Transformation</a></li>
<li class="chapter" data-level="" data-path="data-import-processing-and-summary-statistics.html"><a href="data-import-processing-and-summary-statistics.html#concluding-remarks-13"><i class="fa fa-check"></i>Concluding Remarks</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="data-import-from-pdf-sources.html"><a href="data-import-from-pdf-sources.html"><i class="fa fa-check"></i>Data Import from PDF Sources</a>
<ul>
<li class="chapter" data-level="" data-path="data-import-from-pdf-sources.html"><a href="data-import-from-pdf-sources.html#introduction-to-training-module-14"><i class="fa fa-check"></i>Introduction to Training Module</a></li>
<li class="chapter" data-level="" data-path="data-import-from-pdf-sources.html"><a href="data-import-from-pdf-sources.html#importing-data-from-many-single-pdfs-with-the-same-formatting"><i class="fa fa-check"></i>Importing Data from Many Single PDFs with the Same Formatting</a></li>
<li class="chapter" data-level="" data-path="data-import-from-pdf-sources.html"><a href="data-import-from-pdf-sources.html#importing-data-stored-in-pdf-tables"><i class="fa fa-check"></i>Importing Data Stored in PDF Tables</a></li>
<li class="chapter" data-level="" data-path="data-import-from-pdf-sources.html"><a href="data-import-from-pdf-sources.html#concluding-remarks-14"><i class="fa fa-check"></i>Concluding Remarks</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="two-group-comparisons-and-visualizations.html"><a href="two-group-comparisons-and-visualizations.html"><i class="fa fa-check"></i>Two-Group Comparisons and Visualizations</a>
<ul>
<li class="chapter" data-level="" data-path="two-group-comparisons-and-visualizations.html"><a href="two-group-comparisons-and-visualizations.html#introduction-to-training-module-15"><i class="fa fa-check"></i>Introduction to Training Module</a></li>
<li class="chapter" data-level="" data-path="two-group-comparisons-and-visualizations.html"><a href="two-group-comparisons-and-visualizations.html#overview-of-two-group-statistical-tests"><i class="fa fa-check"></i>Overview of Two Group Statistical Tests</a></li>
<li class="chapter" data-level="" data-path="two-group-comparisons-and-visualizations.html"><a href="two-group-comparisons-and-visualizations.html#statistical-vs-biological-significance"><i class="fa fa-check"></i>Statistical vs Biological Significance</a></li>
<li class="chapter" data-level="" data-path="two-group-comparisons-and-visualizations.html"><a href="two-group-comparisons-and-visualizations.html#unpaired-test-example"><i class="fa fa-check"></i>Unpaired Test Example</a></li>
<li class="chapter" data-level="" data-path="two-group-comparisons-and-visualizations.html"><a href="two-group-comparisons-and-visualizations.html#paired-test-example"><i class="fa fa-check"></i>Paired Test Example</a></li>
<li class="chapter" data-level="" data-path="two-group-comparisons-and-visualizations.html"><a href="two-group-comparisons-and-visualizations.html#visualizing-results"><i class="fa fa-check"></i>Visualizing Results</a></li>
<li class="chapter" data-level="" data-path="two-group-comparisons-and-visualizations.html"><a href="two-group-comparisons-and-visualizations.html#concluding-remarks-15"><i class="fa fa-check"></i>Concluding Remarks</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="multi-group-and-multi-variable-comparisons-and-visualizations.html"><a href="multi-group-and-multi-variable-comparisons-and-visualizations.html"><i class="fa fa-check"></i>Multi-Group and Multi-Variable Comparisons and Visualizations</a>
<ul>
<li class="chapter" data-level="" data-path="multi-group-and-multi-variable-comparisons-and-visualizations.html"><a href="multi-group-and-multi-variable-comparisons-and-visualizations.html#introduction-to-training-module-16"><i class="fa fa-check"></i>Introduction to Training Module</a></li>
<li class="chapter" data-level="" data-path="multi-group-and-multi-variable-comparisons-and-visualizations.html"><a href="multi-group-and-multi-variable-comparisons-and-visualizations.html#overview-of-multi-group-statistical-tests"><i class="fa fa-check"></i>Overview of Multi-Group Statistical Tests</a></li>
<li class="chapter" data-level="" data-path="multi-group-and-multi-variable-comparisons-and-visualizations.html"><a href="multi-group-and-multi-variable-comparisons-and-visualizations.html#multi-group-analysis-example"><i class="fa fa-check"></i>Multi-Group Analysis Example</a></li>
<li class="chapter" data-level="" data-path="multi-group-and-multi-variable-comparisons-and-visualizations.html"><a href="multi-group-and-multi-variable-comparisons-and-visualizations.html#visualization-of-multi-group-statistical-results"><i class="fa fa-check"></i>Visualization of Multi-Group Statistical Results</a></li>
<li class="chapter" data-level="" data-path="multi-group-and-multi-variable-comparisons-and-visualizations.html"><a href="multi-group-and-multi-variable-comparisons-and-visualizations.html#concluding-remarks-16"><i class="fa fa-check"></i>Concluding Remarks</a></li>
</ul></li>
<li class="part"><span><b>Chapter 5 Machine Learning &amp; Artificial Intelligence</b></span></li>
<li class="part"><span><b>Chapter 6 Applications in Toxicology &amp; Exposure Science</b></span></li>
<li class="part"><span><b>Chapter 7 Environmental Health Database Mining</b></span></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">TAME 2.0</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="intoduction-to-statistical-tests" class="section level1 hasAnchor">
<h1>Intoduction to Statistical Tests<a href="intoduction-to-statistical-tests.html#intoduction-to-statistical-tests" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>This training module was developed by Alexis Payton, Kyle Roell, Elise Hickman, and Julia E. Rager.</p>
<p>All input files (script, data, and figures) can be downloaded from the <a href="https://github.com/UNCSRP/TAME2">UNC-SRP TAME2 GitHub website</a>.</p>
<div id="introduction-to-training-module-11" class="section level2 hasAnchor">
<h2>Introduction to Training Module<a href="intoduction-to-statistical-tests.html#introduction-to-training-module-11" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>This training module provides a brief introduction to some of the most commonly implemented statistics and associated visualizations used in exposure science, toxicology, and environmental health studies. This module first uploads an example dataset that is similar to the data used in <strong>TAME 2.0 Module 2.3 Data Manipulation &amp; Reshaping]</strong>, though it includes some expanded subject information data to allow for more example statistical tests. Then, methods to evaluate data normality are presented, including visualization-based and statistical-based approaches.</p>
<p>Basic statistical tests discussed in this module include:</p>
<ul>
<li>T test</li>
<li>Analysis of Variance (ANOVA) with a Tukey’s Post-Hoc test</li>
<li>Regression Modeling (Linear and Logistic)</li>
<li>Chi-squared test</li>
<li>Fisher’s exact test</li>
</ul>
<p>These statistical tests are very simple, with more extensive examples and associated descriptions of statistical models in the proceeding applications-based training modules in:</p>
<ul>
<li>TAME 2.0 Module 4.4 Two-Group Comparisons &amp; Visualizations</li>
<li>TAME 2.0 Module 4.5 Multi-Group Comparisons &amp; Visualizations</li>
<li>TAME 2.0 Module 4.6 Advanced Multi-Group Comparisons &amp; Visualizations</li>
</ul>
<div id="script-preparations-3" class="section level3 hasAnchor">
<h3>Script Preparations<a href="intoduction-to-statistical-tests.html#script-preparations-3" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="cleaning-the-global-environment-3" class="section level4 hasAnchor">
<h4>Cleaning the global environment<a href="intoduction-to-statistical-tests.html#cleaning-the-global-environment-3" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb261"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb261-1"><a href="intoduction-to-statistical-tests.html#cb261-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list=</span><span class="fu">ls</span>())</span></code></pre></div>
</div>
<div id="installing-required-r-packages-3" class="section level4 hasAnchor">
<h4>Installing required R packages<a href="intoduction-to-statistical-tests.html#installing-required-r-packages-3" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>If you already have these packages installed, you can skip this step, or you can run the below code which checks installation status for you</p>
<div class="sourceCode" id="cb262"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb262-1"><a href="intoduction-to-statistical-tests.html#cb262-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">requireNamespace</span>(<span class="st">&quot;tidyverse&quot;</span>))</span>
<span id="cb262-2"><a href="intoduction-to-statistical-tests.html#cb262-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">install.packages</span>(<span class="st">&quot;tidyverse&quot;</span>);</span>
<span id="cb262-3"><a href="intoduction-to-statistical-tests.html#cb262-3" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">requireNamespace</span>(<span class="st">&quot;car&quot;</span>))</span>
<span id="cb262-4"><a href="intoduction-to-statistical-tests.html#cb262-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">install.packages</span>(<span class="st">&quot;car&quot;</span>);</span>
<span id="cb262-5"><a href="intoduction-to-statistical-tests.html#cb262-5" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">requireNamespace</span>(<span class="st">&quot;ggpubr&quot;</span>))</span>
<span id="cb262-6"><a href="intoduction-to-statistical-tests.html#cb262-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">install.packages</span>(<span class="st">&quot;ggpubr&quot;</span>);</span>
<span id="cb262-7"><a href="intoduction-to-statistical-tests.html#cb262-7" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">requireNamespace</span>(<span class="st">&quot;effects&quot;</span>))</span>
<span id="cb262-8"><a href="intoduction-to-statistical-tests.html#cb262-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">install.packages</span>(<span class="st">&quot;effects&quot;</span>);</span></code></pre></div>
</div>
<div id="loading-r-packages-required-for-this-session-2" class="section level4 hasAnchor">
<h4>Loading R packages required for this session<a href="intoduction-to-statistical-tests.html#loading-r-packages-required-for-this-session-2" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb263"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb263-1"><a href="intoduction-to-statistical-tests.html#cb263-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse) <span class="co"># all tidyverse packages, including dplyr and ggplot2</span></span>
<span id="cb263-2"><a href="intoduction-to-statistical-tests.html#cb263-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car) <span class="co"># package for statistical tests</span></span>
<span id="cb263-3"><a href="intoduction-to-statistical-tests.html#cb263-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggpubr) <span class="co"># ggplot2 based plots</span></span>
<span id="cb263-4"><a href="intoduction-to-statistical-tests.html#cb263-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(effects) <span class="co"># for linear modeling</span></span></code></pre></div>
</div>
<div id="set-your-working-directory-4" class="section level4 hasAnchor">
<h4>Set your working directory<a href="intoduction-to-statistical-tests.html#set-your-working-directory-4" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb264"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb264-1"><a href="intoduction-to-statistical-tests.html#cb264-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">&quot;/filepath to where your input files are&quot;</span>)</span></code></pre></div>
</div>
<div id="importing-example-datasets-1" class="section level4 hasAnchor">
<h4>Importing example datasets<a href="intoduction-to-statistical-tests.html#importing-example-datasets-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Let’s read in our example dataset. Note that these data are similar to those used previously, except that demographic and chemical measurement data were previously merged, and a few additional columns of subject information/demographics were added to serve as more thorough examples of data for use in this training module.</p>
<div class="sourceCode" id="cb265"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb265-1"><a href="intoduction-to-statistical-tests.html#cb265-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Loading data</span></span>
<span id="cb265-2"><a href="intoduction-to-statistical-tests.html#cb265-2" aria-hidden="true" tabindex="-1"></a>full.data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;Module3_4_Input/Module3_4_InputData.csv&quot;</span>)</span></code></pre></div>
<p>Let’s view the top of the first 9 columns of data in this dataframe:</p>
<div class="sourceCode" id="cb266"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb266-1"><a href="intoduction-to-statistical-tests.html#cb266-1" aria-hidden="true" tabindex="-1"></a>full.data[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">9</span>]</span></code></pre></div>
<pre><code>##    ID  BMI      BMIcat     MAge           MEdu       BW GA Smoker Smoker3
## 1   1 27.7  Overweight 22.99928 College_Degree 3180.058 34     NS   Never
## 2   2 26.8  Overweight 30.05142 College_Degree 3210.823 43      S   Never
## 3   3 33.2  Overweight 28.04660 College_Degree 3311.551 40     NS   Never
## 4   4 30.1  Overweight 34.81796 College_Degree 3266.844 32      S   Never
## 5   5 37.4  Overweight 42.68440 College_Degree 3664.088 35     NS   Never
## 6   6 33.3  Overweight 24.94960 College_Degree 3328.988 40     NS   Never
## 7   7 24.8  Overweight 29.54798 College_Degree 3061.949 30     NS   Never
## 8   8 16.9 Underweight 24.94954 College_Degree 3332.539 38     NS Current
## 9   9 36.9  Overweight 33.58589 College_Degree 3260.482 39     NS   Never
## 10 10 21.7      Normal 39.29018 College_Degree 3141.723 35     NS Current</code></pre>
<p>These represent the subject information/demographic data, which include the following columns:</p>
<ul>
<li><code>ID</code>: subject number</li>
<li><code>BMI</code>: body mass index</li>
<li><code>BMIcat</code>: BMI &lt;= 18.5 binned as “Underweight”, 18.5 &lt; BMI &lt;= 24.5 binned as “Normal”, BMI &gt; 24.5 binned as “Overweight”</li>
<li><code>MAge</code>: maternal age in years</li>
<li><code>MEdu</code>: maternal education level; “No_HS_Degree” = “less than high school”, “No_College_Degree” = “high school or some college”, “College_Degree” = “college or greater”</li>
<li><code>BW</code>: body weight in grams</li>
<li><code>GA</code>: gestational age in weeks</li>
<li><code>Smoker</code>: “NS” = non-smoker, “S” = smoker</li>
<li><code>Smoker3</code>: “Never”, “Former”, or “Current” smoking status</li>
</ul>
<p><br>
Let’s now view the remaining columns (columns 10-15) in this dataframe:</p>
<div class="sourceCode" id="cb268"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb268-1"><a href="intoduction-to-statistical-tests.html#cb268-1" aria-hidden="true" tabindex="-1"></a>full.data[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>,<span class="dv">10</span><span class="sc">:</span><span class="dv">15</span>]</span></code></pre></div>
<pre><code>##        DWAs     DWCd     DWCr       UAs       UCd      UCr
## 1  6.426464 1.292941 51.67987 10.192695 0.7537104 42.60187
## 2  7.832384 1.798535 50.10409 11.815088 0.9789506 41.30757
## 3  7.516569 1.288461 48.74001 10.079057 0.1903262 36.47716
## 4  5.906656 2.075259 50.92745  8.719123 0.9364825 42.47987
## 5  7.181873 2.762643 55.16882  9.436559 1.4977829 47.78528
## 6  9.723429 3.054057 51.14812 11.589403 1.6645837 38.26386
## 7  6.268547 1.218410 52.08578  8.887948 0.6347667 39.45535
## 8  6.718448 1.414975 54.96740  9.304968 0.6658849 45.09987
## 9  9.074928 2.727755 55.72826 10.818153 1.6585757 42.58577
## 10 5.771691 2.410993 47.06552  8.747217 1.7354305 34.80661</code></pre>
<p>These columns represent the environmental exposure measures, including:</p>
<ul>
<li><code>DWAs</code>: drinking water arsenic levels in µg/L</li>
<li><code>DWCd</code>: drinking water cadmium levels in µg/L</li>
<li><code>DWCr</code>: drinking water chromium levels in µg/L</li>
<li><code>UAs</code>: urinary arsenic levels in µg/L</li>
<li><code>UCd</code>: urinary cadmium levels in µg/L</li>
<li><code>UCr</code>: urinary chromium levels in µg/L</li>
</ul>
<p>Now that the script is prepared and the data are uploaded, we can start by asking some initial questions about the data that can be answered by running some basic statistical tests and visualizations.</p>
<p><br></p>
</div>
</div>
<div id="training-modules-environmental-health-questions-5" class="section level3 hasAnchor">
<h3>Training Module’s Environmental Health Questions<a href="intoduction-to-statistical-tests.html#training-modules-environmental-health-questions-5" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>This training module was specifically developed to answer the following environmental health questions:</p>
<ol style="list-style-type: decimal">
<li>Are there statistically significant differences in BMI between non-smokers and smokers?</li>
<li>Are there statistically significant differences in BMI between current, former, and never smokers?</li>
<li>Is there a relationship between maternal BMI and birth weight?</li>
<li>Are maternal age and gestational age considered potential covariates in the relationship between maternal BMI and birth weight?</li>
<li>Are there statistically significant differences in gestational age based on whether a subject is a non-smoker or a smoker?</li>
<li>Is there a relationship between smoking status and BMI?</li>
</ol>
<p><br></p>
</div>
</div>
<div id="assessing-normality-homogeneity-of-variance" class="section level2 hasAnchor">
<h2>Assessing Normality &amp; Homogeneity of Variance<a href="intoduction-to-statistical-tests.html#assessing-normality-homogeneity-of-variance" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Statistical test selection often relies upon whether or not the underlying data are normally distributed and that variance across the groups is the same (homogeneity of variances). Many statistical tests and methods that are commonly implemented in exposure science, toxicology, and environmental health research rely on assumptions of normality. Thus, one of the most common statistical tests to perform at the beginning of an analysis is a <strong>test for normality</strong>.</p>
<p>As discussed in the previous module, there are a few ways to evaluate the normality of a dataset:</p>
<p><em>First</em>, you can visually gauge whether a dataset appears to be normally distributed through plots. For example, plotting data using histograms, densities, or Q-Q plots can graphically help inform if a variable’s values appear to be normally distributed or not.</p>
<p><em>Second</em>, you can evaluate normality using statistical tests, such as the <strong>Kolmogorov-Smirnov (K-S) test</strong> and <strong>Shapiro-Wilk test</strong>. When using these tests and interpreting their results, it is important to remember that the null hypothesis is that the sample distribution is normal, and a significant p-value means the distribution is non-normal.</p>
<p><br></p>
<p>Let’s start with the first approach based on data visualizations. In this module, we’ll primarily be generating figures using the <strong><em>ggubr</em></strong> package which is specifically designed to generate ggplot2-based figures using more streamlined coding syntax. In addition, this package has statistical parameters for plotting that are useful for basic statistical analysis, especially for people with introductory experience to plotting in R. For further documentation on <em>ggubr</em>, click <a href="https://jtr13.github.io/cc20/brief-introduction-and-tutorial-of-ggpubr-package.html">here</a>.</p>
<p>Let’s begin with a <a href="https://en.wikipedia.org/wiki/Histogram">histogram</a> to view the distribution of BMI data using the <code>gghistogram()</code> function from the <em>ggubr</em> package:</p>
<div class="sourceCode" id="cb270"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb270-1"><a href="intoduction-to-statistical-tests.html#cb270-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gghistogram</span>(<span class="at">data =</span> full.data, <span class="at">x =</span> <span class="st">&quot;BMI&quot;</span>, <span class="at">bins =</span> <span class="dv">20</span>)</span></code></pre></div>
<p><img src="03-Chapter3_files/figure-html/unnamed-chunk-66-1.png" width="480" style="display: block; margin: auto;" /></p>
<p>Let’s also view the <a href="https://en.wikipedia.org/wiki/Q%E2%80%93Q_plot">Q–Q (quantile-quantile) plot</a> using the <code>ggqqplot()</code> function also from the <em>ggubr</em> package:</p>
<div class="sourceCode" id="cb271"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb271-1"><a href="intoduction-to-statistical-tests.html#cb271-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggqqplot</span>(full.data<span class="sc">$</span>BMI, <span class="at">ylab =</span> <span class="st">&quot;BMI&quot;</span>)</span></code></pre></div>
<p><img src="03-Chapter3_files/figure-html/unnamed-chunk-67-1.png" width="480" style="display: block; margin: auto;" /></p>
<p>From these visualizations, the BMI variable appears to be normally distributed, with data centered in the middle and spreading with a distribution on both the lower and upper sides that follow typical normal data distributions.</p>
<p><br></p>
<p>Let’s now implement the second approach based on statistical tests for normality. Here, let’s use the <a href="https://en.wikipedia.org/wiki/Shapiro%E2%80%93Wilk_test">Shapiro-Wilk test</a> as an example, again looking at the BMI data.</p>
<div class="sourceCode" id="cb272"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb272-1"><a href="intoduction-to-statistical-tests.html#cb272-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(full.data<span class="sc">$</span>BMI)</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  full.data$BMI
## W = 0.99232, p-value = 0.3773</code></pre>
<p>This test resulted in a p-value of 0.3773, so we cannot reject the null hypothesis (that the BMI data are normally distributed). These findings support the assumption that these data are normally distributed.</p>
<p>Next, we’ll assess homogeneity of variance using the Levene’s test. This will be done using the <code>leveneTest()</code>function from the <em>car</em> package:</p>
<div class="sourceCode" id="cb274"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb274-1"><a href="intoduction-to-statistical-tests.html#cb274-1" aria-hidden="true" tabindex="-1"></a><span class="co"># First convert the smoker variable to a factor</span></span>
<span id="cb274-2"><a href="intoduction-to-statistical-tests.html#cb274-2" aria-hidden="true" tabindex="-1"></a>full.data<span class="sc">$</span>Smoker <span class="ot">=</span> <span class="fu">factor</span>(full.data<span class="sc">$</span>Smoker, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">&quot;NS&quot;</span>, <span class="st">&quot;S&quot;</span>))</span>
<span id="cb274-3"><a href="intoduction-to-statistical-tests.html#cb274-3" aria-hidden="true" tabindex="-1"></a><span class="fu">leveneTest</span>(BMI <span class="sc">~</span> Smoker, <span class="at">data =</span> full.data)</span></code></pre></div>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = median)
##        Df F value Pr(&gt;F)
## group   1  0.2631 0.6086
##       198</code></pre>
<p>The p value, (<code>Pr&gt;F</code>), is 0.6086 indicating that variance in BMI across the smoking groups is the same. Therefore, the assumptions of a t-test, including normality and homogeneity of variance, have been met.</p>
<p><br></p>
</div>
<div id="two-group-visualizations-and-statistical-comparisons-using-the-t-test" class="section level2 hasAnchor">
<h2>Two-Group Visualizations and Statistical Comparisons using the T-Test<a href="intoduction-to-statistical-tests.html#two-group-visualizations-and-statistical-comparisons-using-the-t-test" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>T-tests are commonly used to test for a significant difference between the means of two groups in normally distributed data. In this example, we will be answering <strong>Environmental Health Question 1</strong>: Are there statistically significant differences in BMI between non-smokers and smokers?</p>
<p>We will specifically implement a two sample t-test (or independent samples t-test).</p>
<p>Let’s first visualize the BMI data across these two groups using boxplots:</p>
<div class="sourceCode" id="cb276"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb276-1"><a href="intoduction-to-statistical-tests.html#cb276-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggboxplot</span>(<span class="at">data =</span> full.data, <span class="at">x =</span> <span class="st">&quot;Smoker&quot;</span>, <span class="at">y =</span> <span class="st">&quot;BMI&quot;</span>)</span></code></pre></div>
<p><img src="03-Chapter3_files/figure-html/unnamed-chunk-70-1.png" width="480" style="display: block; margin: auto;" /></p>
<p>From this plot, it looks like non-smokers (labeled “NS”) <em>may</em> have significantly higher BMI than smokers (labeled “S”), though we need statistical evaluation of these data to more thoroughly evaluate this potential data trend.</p>
<p>It is easy to perform a t-test on these data using the <code>t.test()</code> function from the base R stats package:</p>
<div class="sourceCode" id="cb277"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb277-1"><a href="intoduction-to-statistical-tests.html#cb277-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(<span class="at">data =</span> full.data, BMI <span class="sc">~</span> Smoker)</span></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  BMI by Smoker
## t = 2.5372, df = 80.362, p-value = 0.01311
## alternative hypothesis: true difference in means between group NS and group S is not equal to 0
## 95 percent confidence interval:
##  0.583061 4.823447
## sample estimates:
## mean in group NS  mean in group S 
##         26.11176         23.40851</code></pre>
<div id="answer-to-environmental-health-question-1-4" class="section level3 hasAnchor">
<h3>Answer to Environmental Health Question 1<a href="intoduction-to-statistical-tests.html#answer-to-environmental-health-question-1-4" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="question">
<p><em>With this, we can answer <strong>Environmental Health Question #1</strong></em>: Are there statistically significant differences in BMI between non-smokers and smokers?</p>
</div>
<div class="answer">
<p><strong>Answer</strong>: From this statistical output, we can see that the overall mean BMI in non-smokers (group “NS”) is 26.1, and the overall mean BMI in smokers (group “S”) is 23.4. We can also see that the resulting p-value comparison between the means of these two groups is, indeed, significant (p-value = 0.013), meaning that the means between these groups are significantly different (i.e., are not equal).</p>
</div>
<p>It’s also helpful to save these results into a variable within the R global environment, which then allows us to access specific output values and extract them more easily for our records. For example, we can run the following to specifically extract the resulting p-value from this test:</p>
<div class="sourceCode" id="cb279"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb279-1"><a href="intoduction-to-statistical-tests.html#cb279-1" aria-hidden="true" tabindex="-1"></a>ttest.res <span class="ot">&lt;-</span> <span class="fu">t.test</span>(<span class="at">data =</span> full.data, BMI <span class="sc">~</span> Smoker) <span class="co"># making a list in the R global environment with the statistical results</span></span>
<span id="cb279-2"><a href="intoduction-to-statistical-tests.html#cb279-2" aria-hidden="true" tabindex="-1"></a><span class="fu">signif</span>(ttest.res<span class="sc">$</span>p.value, <span class="dv">2</span>) <span class="co"># pulling the p-value and using the `signif` function to round to 2 significant figures</span></span></code></pre></div>
<pre><code>## [1] 0.013</code></pre>
<p><br></p>
</div>
</div>
<div id="three-group-visualizations-and-statistical-comparisons-using-an-anova" class="section level2 hasAnchor">
<h2>Three-Group Visualizations and Statistical Comparisons using an ANOVA<a href="intoduction-to-statistical-tests.html#three-group-visualizations-and-statistical-comparisons-using-an-anova" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Analysis of Variance (ANOVA) is a statistical method that can be used to compare means across three or more groups in normally distributed data. To demonstrate an ANOVA test on this dataset, let’s answer <strong>Environmental Health Question 2</strong>: Are there statistically significant differences in BMI between current, former, and never smokers? To do this we’ll use the <code>Smoker3</code> variable from our dataset.</p>
<p>Let’s again start by viewing these data distributions using a boxplot:</p>
<div class="sourceCode" id="cb281"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb281-1"><a href="intoduction-to-statistical-tests.html#cb281-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggboxplot</span>(<span class="at">data =</span> full.data, <span class="at">x =</span> <span class="st">&quot;Smoker3&quot;</span>, <span class="at">y =</span> <span class="st">&quot;BMI&quot;</span>)</span></code></pre></div>
<p><img src="03-Chapter3_files/figure-html/unnamed-chunk-73-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>From this cursory review of the data, it looks like the current smokers likely demonstrate significantly different BMI measures than the former and never smokers, though we need statistical tests to verify this potential trend. We also require statistical tests to evaluate potential differences (or lack of differences) between former and never smokers.</p>
<p>Let’s now run the ANOVA to compare BMI between smoking groups, using the <code>aov()</code> function to fit an ANOVA model:</p>
<div class="sourceCode" id="cb282"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb282-1"><a href="intoduction-to-statistical-tests.html#cb282-1" aria-hidden="true" tabindex="-1"></a>smoker_anova <span class="ot">=</span> <span class="fu">aov</span>(<span class="at">data =</span> full.data, BMI <span class="sc">~</span> Smoker3)</span>
<span id="cb282-2"><a href="intoduction-to-statistical-tests.html#cb282-2" aria-hidden="true" tabindex="-1"></a>smoker_anova</span></code></pre></div>
<pre><code>## Call:
##    aov(formula = BMI ~ Smoker3, data = full.data)
## 
## Terms:
##                  Smoker3 Residuals
## Sum of Squares  2046.713  6817.786
## Deg. of Freedom        2       197
## 
## Residual standard error: 5.882861
## Estimated effects may be unbalanced</code></pre>
<p>We need to extract the typical ANOVA results table using either the <code>summary()</code> or <code>anova()</code> function on the resulting fitted object:</p>
<div class="sourceCode" id="cb284"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb284-1"><a href="intoduction-to-statistical-tests.html#cb284-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(smoker_anova)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: BMI
##            Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## Smoker3     2 2046.7 1023.36   29.57 5.888e-12 ***
## Residuals 197 6817.8   34.61                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>This table outputs a lot of information, including the <code>F value</code> referring to the resulting F-statistic, <code>Pr(&gt;F)</code> referring to the p-value of the F-statistic, and other values that are described in detail through other available resources including this <a href="https://online.stat.psu.edu/stat485/lesson/12/12.2">helpful video</a> through PennState’s statistics online resources.</p>
<div id="answer-to-environmental-health-question-2-4" class="section level3 hasAnchor">
<h3>Answer to Environmental Health Question 2<a href="intoduction-to-statistical-tests.html#answer-to-environmental-health-question-2-4" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="question">
<p><em>With this, we can answer <strong>Environmental Health Question #2</strong></em>: Are there statistically significant differences in BMI between current, former, never smokers?</p>
</div>
<div class="answer">
<p><strong>Answer</strong>: From this ANOVA output table, we can conclude that the group means across all three groups are not equal given that the p value, written as <code>Pr(&gt;F)</code> is significant (p value = 5.88 x 10<sup>-12</sup>). However, it doesn’t tell us which groups differ from each other and that’s where post hoc tests like Tukey’s are useful.</p>
</div>
<p>Let’s run a Tukey’s post hoc test using the <code>TukeyHSD()</code> function in base R to determine which of the current, former, and never smokers have significant differences in BMI:</p>
<div class="sourceCode" id="cb286"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb286-1"><a href="intoduction-to-statistical-tests.html#cb286-1" aria-hidden="true" tabindex="-1"></a>smoker_tukey <span class="ot">=</span> <span class="fu">TukeyHSD</span>(smoker_anova)</span>
<span id="cb286-2"><a href="intoduction-to-statistical-tests.html#cb286-2" aria-hidden="true" tabindex="-1"></a>smoker_tukey</span></code></pre></div>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = BMI ~ Smoker3, data = full.data)
## 
## $Smoker3
##                     diff       lwr       upr     p adj
## Former-Current 7.4436765  4.203006 10.684347 0.0000005
## Never-Current  8.1167857  5.595470 10.638102 0.0000000
## Never-Former   0.6731092 -2.011764  3.357982 0.8245448</code></pre>
<p>Although the above Tukey object contains a column <code>p adj</code>, those are the raw unadjusted p values. It is common practice to adjust p values from multiple comparisons to prevent the reporting of false positives or reporting of a significant difference that doesn’t actually exist (<a href="https://bmcmedresmethodol.biomedcentral.com/articles/10.1186/1471-2288-2-8#:~:text=Thus%2C%20the%20main%20benefit%20of,exists%20%5B10%E2%80%9321%5D.">Feise, 2002</a>). There are a couple of different methods that are used to adjust p values including the Bonferroni and the Benjamini &amp; Hochberg approaches.</p>
<p>For this example, we’ll use the <code>p.adjust()</code> function to obtain the Benjamini &amp; Hochberg adjusted p values. Check out the associated <a href="https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/p.adjust">RDocumentation</a> to discover other methods that can be used to adjust p values using the <code>p.adjust()</code> function:</p>
<div class="sourceCode" id="cb288"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb288-1"><a href="intoduction-to-statistical-tests.html#cb288-1" aria-hidden="true" tabindex="-1"></a><span class="co"># First converting the Tukey object into a dataframe</span></span>
<span id="cb288-2"><a href="intoduction-to-statistical-tests.html#cb288-2" aria-hidden="true" tabindex="-1"></a>smoker_tukey_df <span class="ot">=</span> <span class="fu">data.frame</span>(smoker_tukey<span class="sc">$</span>Smoker3) <span class="sc">%&gt;%</span></span>
<span id="cb288-3"><a href="intoduction-to-statistical-tests.html#cb288-3" aria-hidden="true" tabindex="-1"></a>    <span class="co"># renaming the `p adj` to `P Value` for clarity</span></span>
<span id="cb288-4"><a href="intoduction-to-statistical-tests.html#cb288-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rename</span>(<span class="st">`</span><span class="at">P Value</span><span class="st">`</span> <span class="ot">=</span> p.adj)</span>
<span id="cb288-5"><a href="intoduction-to-statistical-tests.html#cb288-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb288-6"><a href="intoduction-to-statistical-tests.html#cb288-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Adding a column with the adjusted p values</span></span>
<span id="cb288-7"><a href="intoduction-to-statistical-tests.html#cb288-7" aria-hidden="true" tabindex="-1"></a>smoker_tukey_df<span class="sc">$</span><span class="st">`</span><span class="at">P Adj</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">p.adjust</span>(smoker_tukey_df<span class="sc">$</span><span class="st">`</span><span class="at">P Value</span><span class="st">`</span>, <span class="at">method =</span> <span class="st">&quot;fdr&quot;</span>)</span>
<span id="cb288-8"><a href="intoduction-to-statistical-tests.html#cb288-8" aria-hidden="true" tabindex="-1"></a>smoker_tukey_df</span></code></pre></div>
<pre><code>##                     diff       lwr       upr      P Value        P Adj
## Former-Current 7.4436765  4.203006 10.684347 5.064863e-07 7.597295e-07
## Never-Current  8.1167857  5.595470 10.638102 3.432921e-12 1.029876e-11
## Never-Former   0.6731092 -2.011764  3.357982 8.245448e-01 8.245448e-01</code></pre>
</div>
<div id="answer-to-environmental-health-question-2-5" class="section level3 hasAnchor">
<h3>Answer to Environmental Health Question 2<a href="intoduction-to-statistical-tests.html#answer-to-environmental-health-question-2-5" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><em>We can use this additional information to further answer <strong>Environmental Health Question #2</strong></em>: Are there statistically significant differences in BMI between current, former, and never smokers?</p>
<p><strong>Answer</strong>: Current smokers have significantly lower BMIs than people who have never smoked and people who have formerly smoked. This is made evident by the 95% confidence intervals (<code>lwr</code> and <code>upr</code>) that don’t cross 0 and the p values that are less than 0.05 even after adjusting.</p>
<p><br></p>
</div>
</div>
<div id="regression-modeling-and-visualization-linear-and-logistic-regressions" class="section level2 hasAnchor">
<h2>Regression Modeling and Visualization: Linear and Logistic Regressions<a href="intoduction-to-statistical-tests.html#regression-modeling-and-visualization-linear-and-logistic-regressions" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Regression modeling aims to find a relationship between a dependent variable (or outcome, response, y) and an independent variable (or predictor, explanatory variable, x). There are many forms of regression analysis, but here we will focus on two: linear regression and logistic regression.</p>
<p>In brief, <strong>linear regression</strong> is generally used when you have a continuous dependent variable and there is assumed to be some sort of linear relationship between the dependent and independent variables. Conversely, <strong>logistic regression</strong> is often used when the dependent variable is dichotomous.</p>
<p>Let’s first run through an example linear regression model to answer <strong>Environmental Health Question 3</strong>: Is there a relationship between maternal BMI and birth weight?</p>
<div id="linear-regression" class="section level3 hasAnchor">
<h3>Linear Regression<a href="intoduction-to-statistical-tests.html#linear-regression" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We will first visualize the data and a run simple correlation analysis to evaluate whether these data are generally correlated. Then, we will run a linear regression to evaluate the relationship between these variables in more detail.</p>
<p>Plotting the variables against one another and adding a linear regression line using the function <code>ggscatter()</code> from the <em>ggubr</em> package:</p>
<div class="sourceCode" id="cb290"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb290-1"><a href="intoduction-to-statistical-tests.html#cb290-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggscatter</span>(full.data, <span class="at">x =</span> <span class="st">&quot;BMI&quot;</span>, <span class="at">y =</span> <span class="st">&quot;BW&quot;</span>, </span>
<span id="cb290-2"><a href="intoduction-to-statistical-tests.html#cb290-2" aria-hidden="true" tabindex="-1"></a>          <span class="co"># Adding a linear line with 95% condfidence intervals as the shaded region</span></span>
<span id="cb290-3"><a href="intoduction-to-statistical-tests.html#cb290-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">add =</span> <span class="st">&quot;reg.line&quot;</span>, <span class="at">conf.int =</span> <span class="cn">TRUE</span>, </span>
<span id="cb290-4"><a href="intoduction-to-statistical-tests.html#cb290-4" aria-hidden="true" tabindex="-1"></a>          <span class="co"># Customize reg. line</span></span>
<span id="cb290-5"><a href="intoduction-to-statistical-tests.html#cb290-5" aria-hidden="true" tabindex="-1"></a>          <span class="at">add.params =</span> <span class="fu">list</span>(<span class="at">color =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">fill =</span> <span class="st">&quot;lightgray&quot;</span>), </span>
<span id="cb290-6"><a href="intoduction-to-statistical-tests.html#cb290-6" aria-hidden="true" tabindex="-1"></a>          <span class="co"># Adding Pearson&#39;s correlation coefficient</span></span>
<span id="cb290-7"><a href="intoduction-to-statistical-tests.html#cb290-7" aria-hidden="true" tabindex="-1"></a>          <span class="at">cor.coef =</span> <span class="cn">TRUE</span>, <span class="at">cor.method =</span> <span class="st">&quot;pearson&quot;</span>, <span class="at">cor.coeff.args =</span> <span class="fu">list</span>(<span class="at">label.sep =</span> <span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>)) </span></code></pre></div>
<p><img src="03-Chapter3_files/figure-html/unnamed-chunk-78-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>We can also run a basic correlation analysis between these two variables using the <code>cor.test()</code> function. This function uses the Pearson’s correlation test as default, which we can implement here due to the previously discussed assumption of normality for this dataset. Note that other tests are needed in instances when data are not normally distributed (e.g., Spearman Rank). This function is used here to extract the Pearson’s correlation coefficient and p-value (which also appear above in the upper left corner of the graph):</p>
<div class="sourceCode" id="cb291"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb291-1"><a href="intoduction-to-statistical-tests.html#cb291-1" aria-hidden="true" tabindex="-1"></a>cor.res <span class="ot">&lt;-</span> <span class="fu">cor.test</span>(full.data<span class="sc">$</span>BW, full.data<span class="sc">$</span>BMI)</span>
<span id="cb291-2"><a href="intoduction-to-statistical-tests.html#cb291-2" aria-hidden="true" tabindex="-1"></a><span class="fu">signif</span>(cor.res<span class="sc">$</span>estimate, <span class="dv">2</span>)</span></code></pre></div>
<pre><code>##  cor 
## 0.25</code></pre>
<div class="sourceCode" id="cb293"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb293-1"><a href="intoduction-to-statistical-tests.html#cb293-1" aria-hidden="true" tabindex="-1"></a><span class="fu">signif</span>(cor.res<span class="sc">$</span>p.value, <span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] 0.00039</code></pre>
<p>Together, it looks like there may be an association between BW and BMI, based on these correlation results, demonstrating a significant p-value of 0.0004.</p>
<p>To test this further, let’s run a linear regression analysis using the <code>lm()</code> function, using BMI (X) as the independent variable and BW as the dependent variable (Y):</p>
<div class="sourceCode" id="cb295"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb295-1"><a href="intoduction-to-statistical-tests.html#cb295-1" aria-hidden="true" tabindex="-1"></a>crude_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data =</span> full.data, BW <span class="sc">~</span> BMI)</span>
<span id="cb295-2"><a href="intoduction-to-statistical-tests.html#cb295-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(crude_lm) <span class="co"># viewing the results summary</span></span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = BW ~ BMI, data = full.data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -598.39 -116.72    8.11  136.54  490.11 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 3069.201     52.576   58.38  &lt; 2e-16 ***
## BMI            7.208      1.997    3.61 0.000388 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 188 on 198 degrees of freedom
## Multiple R-squared:  0.06176,    Adjusted R-squared:  0.05702 
## F-statistic: 13.03 on 1 and 198 DF,  p-value: 0.0003876</code></pre>
</div>
<div id="answer-to-environmental-health-question-3-2" class="section level3 hasAnchor">
<h3>Answer to Environmental Health Question 3<a href="intoduction-to-statistical-tests.html#answer-to-environmental-health-question-3-2" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="question">
<p><em>With this, we can answer <strong>Environmental Health Question #3</strong></em>: Is there a relationship between maternal BMI and birth weight?</p>
</div>
<div class="answer">
<p><strong>Answer</strong>: Not only is there a slight positive correlation between maternal BMI and BW as indicated by ~0.25 correlation coefficient, this linear relationship is significant due to the p-value being ~0.0004.</p>
</div>
<p>Additionally, we can derive confidence intervals for the BMI estimate using:</p>
<div class="sourceCode" id="cb297"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb297-1"><a href="intoduction-to-statistical-tests.html#cb297-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(crude_lm)[<span class="st">&quot;BMI&quot;</span>,]</span></code></pre></div>
<pre><code>##     2.5 %    97.5 % 
##  3.270873 11.145740</code></pre>
<p>Notice that the r-squared (R<sup>2</sup>) value in regression output is the squared value of the previously calculated correlation coefficient (R).</p>
<div class="sourceCode" id="cb299"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb299-1"><a href="intoduction-to-statistical-tests.html#cb299-1" aria-hidden="true" tabindex="-1"></a><span class="fu">signif</span>(<span class="fu">sqrt</span>(<span class="fu">summary</span>(crude_lm)<span class="sc">$</span>r.squared), <span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] 0.25</code></pre>
<p><br></p>
<p>In epidemiological studies, the potential influence of confounders is considered by including important covariates within the final regression model. Let’s go ahead and investigate <strong>Environmental Health Question 4</strong>: Are maternal age and gestational age considered potential covariates in the relationship between maternal BMI and birth weight? We can do that by adding those variables to the linear model.</p>
<div class="sourceCode" id="cb301"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb301-1"><a href="intoduction-to-statistical-tests.html#cb301-1" aria-hidden="true" tabindex="-1"></a>adjusted_lm <span class="ot">=</span> <span class="fu">lm</span>(<span class="at">data =</span> full.data, BW <span class="sc">~</span> BMI <span class="sc">+</span> MAge <span class="sc">+</span> GA)</span>
<span id="cb301-2"><a href="intoduction-to-statistical-tests.html#cb301-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(adjusted_lm)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = BW ~ BMI + MAge + GA, data = full.data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -454.04 -111.24    5.79  116.46  488.41 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 2247.995    117.946  19.060  &lt; 2e-16 ***
## BMI            6.237      1.774   3.515 0.000547 ***
## MAge           4.269      1.887   2.263 0.024752 *  
## GA            19.612      2.656   7.385 4.28e-12 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 165.5 on 196 degrees of freedom
## Multiple R-squared:  0.2805, Adjusted R-squared:  0.2695 
## F-statistic: 25.47 on 3 and 196 DF,  p-value: 5.884e-14</code></pre>
<p><br></p>
<p>Let’s further visualize these regression modeling results by adding a regression line to the original scatterplot. Before doing so, we’ll use the <code>effect()</code> function from the <em>effects</em> package to make estimated predictions of birth weight values for the crude and adjusted linear models. The crude model only has BMI as the dependent variable, while the adjusted model includes BMI, maternal age, and gestational age as dependent variables. This function creates a table that contains 5 columns: fitted values for BMI (<code>BMI</code>), predictor values (<code>fit</code>), standard errors of the predictions (<code>se</code>), lower confidence limits (<code>lower</code>), and upper confidence limits (<code>upper</code>). An additional column, <code>Model</code>, was added to specify whether the values correspond to the crude or adjusted model.</p>
<p>For additional information on visualizing adjusted linear models, see <a href="https://nickmichalak.com/post/2019-02-13-plotting-adjusted-associations-in-r/plotting-adjusted-associations-in-r/">Plotting Adjusted Associations in R</a>.</p>
<div class="sourceCode" id="cb303"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb303-1"><a href="intoduction-to-statistical-tests.html#cb303-1" aria-hidden="true" tabindex="-1"></a>crude_lm_predtable <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="fu">effect</span>(<span class="at">term =</span> <span class="st">&quot;BMI&quot;</span>, <span class="at">mod =</span> crude_lm), <span class="at">Model =</span> <span class="st">&quot;Crude&quot;</span>) </span>
<span id="cb303-2"><a href="intoduction-to-statistical-tests.html#cb303-2" aria-hidden="true" tabindex="-1"></a>adjusted_lm_predtable <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="fu">effect</span>(<span class="at">term =</span> <span class="st">&quot;BMI&quot;</span>, <span class="at">mod =</span> adjusted_lm), <span class="at">Model =</span> <span class="st">&quot;Adjusted&quot;</span>) </span>
<span id="cb303-3"><a href="intoduction-to-statistical-tests.html#cb303-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb303-4"><a href="intoduction-to-statistical-tests.html#cb303-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Viewing one of the tables</span></span>
<span id="cb303-5"><a href="intoduction-to-statistical-tests.html#cb303-5" aria-hidden="true" tabindex="-1"></a>crude_lm_predtable</span></code></pre></div>
<pre><code>##   BMI      fit       se    lower    upper Model
## 1  10 3141.284 33.63898 3074.948 3207.621 Crude
## 2  19 3206.159 18.54497 3169.588 3242.730 Crude
## 3  28 3271.034 14.21563 3243.000 3299.067 Crude
## 4  36 3328.700 24.86346 3279.669 3377.732 Crude
## 5  45 3393.575 41.18575 3312.356 3474.794 Crude</code></pre>
<p>Now we can plot each linear model and their corresponding 95% confidence intervals (CI). It’s easier to visualize this using <em>ggplot2</em> instead of <em>ggubr</em> so that’s what we’ll use:</p>
<div class="sourceCode" id="cb305"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb305-1"><a href="intoduction-to-statistical-tests.html#cb305-1" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">repr.plot.width=</span><span class="dv">9</span>, <span class="at">repr.plot.height=</span><span class="dv">6</span>) <span class="co"># changing dimensions of the entire figure</span></span>
<span id="cb305-2"><a href="intoduction-to-statistical-tests.html#cb305-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(full.data, <span class="fu">aes</span>(<span class="at">x =</span> BMI, <span class="at">y =</span> BW)) <span class="sc">+</span> </span>
<span id="cb305-3"><a href="intoduction-to-statistical-tests.html#cb305-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb305-4"><a href="intoduction-to-statistical-tests.html#cb305-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Crude line</span></span>
<span id="cb305-5"><a href="intoduction-to-statistical-tests.html#cb305-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">data =</span> crude_lm_predtable, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> BMI, <span class="at">y =</span> fit, <span class="at">color =</span> Model)) <span class="sc">+</span></span>
<span id="cb305-6"><a href="intoduction-to-statistical-tests.html#cb305-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Adjusted line</span></span>
<span id="cb305-7"><a href="intoduction-to-statistical-tests.html#cb305-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">data =</span> adjusted_lm_predtable, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> BMI, <span class="at">y =</span> fit, <span class="at">color =</span> Model)) <span class="sc">+</span></span>
<span id="cb305-8"><a href="intoduction-to-statistical-tests.html#cb305-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Crude 95% CI</span></span>
<span id="cb305-9"><a href="intoduction-to-statistical-tests.html#cb305-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="at">data =</span> crude_lm_predtable, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> BMI, <span class="at">y =</span> fit, <span class="at">ymin =</span> lower, <span class="at">ymax =</span> upper, <span class="at">fill =</span> Model), <span class="at">alpha =</span> <span class="fl">0.25</span>) <span class="sc">+</span> </span>
<span id="cb305-10"><a href="intoduction-to-statistical-tests.html#cb305-10" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Adjusted 95% CI</span></span>
<span id="cb305-11"><a href="intoduction-to-statistical-tests.html#cb305-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="at">data =</span> adjusted_lm_predtable, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> BMI, <span class="at">y =</span> fit, <span class="at">ymin =</span> lower, <span class="at">ymax =</span> upper, <span class="at">fill =</span> Model), <span class="at">alpha =</span> <span class="fl">0.25</span>)</span></code></pre></div>
<p><img src="03-Chapter3_files/figure-html/unnamed-chunk-85-1.png" width="672" style="display: block; margin: auto;" /></p>
</div>
<div id="answer-to-environmental-health-question-4-1" class="section level3 hasAnchor">
<h3>Answer to Environmental Health Question 4<a href="intoduction-to-statistical-tests.html#answer-to-environmental-health-question-4-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="question">
<p><em>With this, we can answer <strong>Environmental Health Question #4</strong></em>: Are maternal age and gestational age considered potential covariates in the relationship between maternal BMI and birth weight?</p>
</div>
<div class="answer">
<p><strong>Answer</strong>: BMI is still significantly associated with BW and the included covariates are also shown to be significantly related to birth weight in this model. However, the addition of gestational age and maternal age did not have much of an impact on modifying the relationship between BMI and birth weight.</p>
</div>
<p><br></p>
</div>
<div id="logistic-regression" class="section level3 hasAnchor">
<h3>Logistic Regression<a href="intoduction-to-statistical-tests.html#logistic-regression" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>To carry out a logistic regression, we need to evaluate one continuous variable (here, we select gestational age, using the <code>GA</code> variable) and one dichotomous variable (here, we select smoking status, using the <code>Smoker</code> variable) to evaluate <strong>Environmental Health Question 5</strong>: Are there statistically significant differences in gestational age based on whether a subject is a non-smoker or a smoker?</p>
<p>Because smoking status is a dichotomous variable, we will use logistic regression to look at this relationship. Let’s first visualize these data using a stacked bar plot for the dichotomous smoker dataset:</p>
<div class="sourceCode" id="cb306"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb306-1"><a href="intoduction-to-statistical-tests.html#cb306-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggboxplot</span>(<span class="at">data =</span> full.data, <span class="at">x =</span> <span class="st">&quot;Smoker&quot;</span>, <span class="at">y =</span> <span class="st">&quot;GA&quot;</span>)</span></code></pre></div>
<p><img src="03-Chapter3_files/figure-html/unnamed-chunk-86-1.png" width="480" style="display: block; margin: auto;" /></p>
<p><br>
With this visualization, it’s difficult to tell whether or not there are significant differences in maternal education based on smoking status.
<br></p>
<p>Let’s now run the statistical analysis, using logistic regression modeling:</p>
<div class="sourceCode" id="cb307"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb307-1"><a href="intoduction-to-statistical-tests.html#cb307-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Before running the model, &quot;Smoker&quot;, needs to be binarized to 0&#39;s or 1&#39;s for the glm function</span></span>
<span id="cb307-2"><a href="intoduction-to-statistical-tests.html#cb307-2" aria-hidden="true" tabindex="-1"></a>glm_data <span class="ot">=</span> full.data <span class="sc">%&gt;%</span></span>
<span id="cb307-3"><a href="intoduction-to-statistical-tests.html#cb307-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">Smoker =</span> <span class="fu">ifelse</span>(Smoker <span class="sc">==</span> <span class="st">&quot;NS&quot;</span>, <span class="dv">0</span>,<span class="dv">1</span>))</span>
<span id="cb307-4"><a href="intoduction-to-statistical-tests.html#cb307-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb307-5"><a href="intoduction-to-statistical-tests.html#cb307-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Use GLM (generalized linear model) and specify the family as binomial</span></span>
<span id="cb307-6"><a href="intoduction-to-statistical-tests.html#cb307-6" aria-hidden="true" tabindex="-1"></a><span class="co"># This tells GLM to run a logistic regression</span></span>
<span id="cb307-7"><a href="intoduction-to-statistical-tests.html#cb307-7" aria-hidden="true" tabindex="-1"></a>log.res <span class="ot">=</span> <span class="fu">glm</span>(Smoker <span class="sc">~</span> GA, <span class="at">family =</span> <span class="st">&quot;binomial&quot;</span>, <span class="at">data =</span> glm_data)</span>
<span id="cb307-8"><a href="intoduction-to-statistical-tests.html#cb307-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb307-9"><a href="intoduction-to-statistical-tests.html#cb307-9" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(log.res) <span class="co"># viewing the results</span></span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = Smoker ~ GA, family = &quot;binomial&quot;, data = glm_data)
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)  
## (Intercept)  1.26669    1.37042   0.924   0.3553  
## GA          -0.06764    0.03796  -1.782   0.0747 .
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 218.10  on 199  degrees of freedom
## Residual deviance: 214.89  on 198  degrees of freedom
## AIC: 218.89
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>Similar to the regression modeling analysis, we can also derive confidence intervals:</p>
<div class="sourceCode" id="cb309"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb309-1"><a href="intoduction-to-statistical-tests.html#cb309-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(log.res)[<span class="st">&quot;GA&quot;</span>,]</span></code></pre></div>
<pre><code>## Waiting for profiling to be done...</code></pre>
<pre><code>##       2.5 %      97.5 % 
## -0.14301103  0.00640128</code></pre>
</div>
<div id="answer-to-environmental-health-question-5-1" class="section level3 hasAnchor">
<h3>Answer to Environmental Health Question 5<a href="intoduction-to-statistical-tests.html#answer-to-environmental-health-question-5-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="question">
<p><em>With this, we can answer <strong>Environmental Health Question #5</strong></em>: Are there statistically significant differences in maternal education level based on whether they are a non-smoker or a smoker?</p>
</div>
<div class="answer">
<p><strong>Answer</strong>: Collectively, these results show a non-significant p-value relating gestational age to smoking status. The confidence intervals also overlap across zero. Therefore, these data do not demonstrate a significant association between gestational age and smoking status.</p>
</div>
<p><br></p>
</div>
</div>
<div id="statistical-evaluations-of-categorical-data-using-the-chi-squared-test-and-fishers-exact-test" class="section level2 hasAnchor">
<h2>Statistical Evaluations of Categorical Data using the Chi-Squared Test and Fisher’s Exact Test<a href="intoduction-to-statistical-tests.html#statistical-evaluations-of-categorical-data-using-the-chi-squared-test-and-fishers-exact-test" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Chi-squared test and Fisher’s exact tests are used primarily when evaluating data distributions between two categorical variables.
The difference between a Chi-squared test and the Fisher’s exact test surrounds the specific procedure being run. The <a href="https://en.wikipedia.org/wiki/Chi-squared_test">Chi-squared test</a> is an approximation and is run with larger sample sizes to determine whether there is a statistically significant difference between the expected vs. observed frequencies in one or more categories of a contingency table. The <a href="https://en.wikipedia.org/wiki/Fisher%27s_exact_test">Fisher’s exact test</a> is similar, though is an exact measure that can be run on any sample size, including smaller sample sizes.</p>
<p>The number of samples or subjects (<em>n</em>) considered to be sufficiently large enough is subjective, contingent upon the research question being asked, and the experimental design. However, smaller sample sizes can be more permissible if the sample is normally distributed, but generally speaking having <em>n</em> &gt; 30 is a common convention in statistics (<a href="https://datepsychology.com/no-the-sample-size-is-not-too-small/">Alexander, 2022</a>).</p>
<p>For this example, we are interested in evaluating the potential relationship between two categorical variables: smoking status (using the <code>Smoker</code> variable) and categorical BMI group (using the <code>BMIcat</code> variable) to address <strong>Environmental Health Question 6</strong>: Is there a relationship between smoking status and BMI?</p>
<p>To run these categorical statistical tests, let’s first create and view a 2-way contingency table describing the frequencies of observations across the categorical BMI and smoking groups:</p>
<div class="sourceCode" id="cb312"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb312-1"><a href="intoduction-to-statistical-tests.html#cb312-1" aria-hidden="true" tabindex="-1"></a>ContingencyTable <span class="ot">&lt;-</span> <span class="fu">with</span>(full.data, <span class="fu">table</span>(BMIcat, Smoker))</span>
<span id="cb312-2"><a href="intoduction-to-statistical-tests.html#cb312-2" aria-hidden="true" tabindex="-1"></a>ContingencyTable</span></code></pre></div>
<pre><code>##              Smoker
## BMIcat        NS  S
##   Normal      43 14
##   Overweight  87 22
##   Underweight 23 11</code></pre>
<p>Now let’s run the Chi-squared test on this table:</p>
<div class="sourceCode" id="cb314"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb314-1"><a href="intoduction-to-statistical-tests.html#cb314-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(ContingencyTable)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  ContingencyTable
## X-squared = 2.1849, df = 2, p-value = 0.3354</code></pre>
<p>Note that we can also run the Chi-squared test using the following code, without having to generate the contingency table:</p>
<div class="sourceCode" id="cb316"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb316-1"><a href="intoduction-to-statistical-tests.html#cb316-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(full.data<span class="sc">$</span>BMIcat, full.data<span class="sc">$</span>Smoker)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  full.data$BMIcat and full.data$Smoker
## X-squared = 2.1849, df = 2, p-value = 0.3354</code></pre>
<p>Or:</p>
<div class="sourceCode" id="cb318"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb318-1"><a href="intoduction-to-statistical-tests.html#cb318-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(full.data, <span class="fu">chisq.test</span>(BMIcat, Smoker))</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  BMIcat and Smoker
## X-squared = 2.1849, df = 2, p-value = 0.3354</code></pre>
<div id="answer-to-environmental-health-question-6" class="section level3 hasAnchor">
<h3>Answer to Environmental Health Question 6<a href="intoduction-to-statistical-tests.html#answer-to-environmental-health-question-6" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="question">
<p>Note that these all produce the same results. <em>With this, we can answer <strong>Environmental Health Question #6</strong></em>: Is there a relationship between smoking status and BMI?</p>
</div>
<div class="answer">
<p><strong>Answer</strong>: This results in a p-value = 0.34, demonstrating that there is no significant relationship between BMI categories and smoking status.</p>
</div>
<p><br>
We can also run a Fisher’s Exact Test when considering sample sizes. We won’t run this here due to computing time, but here is some example code for your records:</p>
<div class="sourceCode" id="cb320"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb320-1"><a href="intoduction-to-statistical-tests.html#cb320-1" aria-hidden="true" tabindex="-1"></a><span class="co">#With small sample sizes, can use Fisher&#39;s Exact Test</span></span>
<span id="cb320-2"><a href="intoduction-to-statistical-tests.html#cb320-2" aria-hidden="true" tabindex="-1"></a><span class="co">#fisher.test(full.data$BMI, full.data$Smoker)</span></span></code></pre></div>
</div>
</div>
<div id="concluding-remarks-11" class="section level2 hasAnchor">
<h2>Concluding Remarks<a href="intoduction-to-statistical-tests.html#concluding-remarks-11" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In conclusion, this training module serves as a high-level introduction to basic statistics and visualization methods. Statistical approaches described in this training module include tests for normality, t-test, analysis of variance, regression modeling, chi-squared test, and Fisher’s exact test. Visualization approaches include boxplots, histograms, scatterplots, and regression lines. These methods serve as an important foundation for nearly all studies carried out in environmental health research.</p>
<p><br></p>
<p><label class="tykfont">
Test Your Knowledge
</label></p>
<div class="tyk">
<ol style="list-style-type: decimal">
<li>If we’re interested in investigating if there are significant differences in birth weight based on maternal education level, which statistical test should you use?</li>
<li>Is that relationship considered to be statistically significant and how can we visualize the distributions of these groups?</li>
</ol>
</div>

</div>
</div>



<!-- ################################################## -->
<!-- ################################################## -->
<!-- START SECTION ONE  -->
<!-- ################################################## -->
<!-- ################################################## -->
</div>
            </section>

          </div>
        </div>
      </div>
<a href="normality-tests-and-data-transformations.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="overview-of-experimental-design-and-example-data.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf", "_main.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
